### ISSUE TITLE
When can we expect the next release?

### ISSUE THREAD

**Issue by endianjoakim** [eclipse/hawkbit#1005]
Hi there, 

We're looking into using Hawkbit, but need postgresql support. I understand it has been added to master but it's not yet released. 

We can probably build it ourselves, but would like a formal release. Is there one planned?

Thanks

**Comment by schabdo** [comment]
Glad to hear that you're looking into hawkBit! Exactly, support is in place and tested but not yet released. It will be part of the next milestone. We are currently waiting for the PR to bump Spring Boot to version 2.3.x. It's expected soon. After that we can start with the paper work and file the next milestone or even a full release. I added the preconditions to the release task to make it more transparent (cf. https://github.com/eclipse/hawkbit/issues/784). Hope this helps and is no blocker for you

**Comment by schabdo** [comment]
Next milestone tag [0.3.0M7](https://github.com/eclipse/hawkbit/releases/tag/0.3.0M7) containing PostgreSQL support is now available. Expect to see the milestone available on Maven Central beginning of next week
