### ISSUE TITLE
Update hawkBit's license to EPL 2.0

### ISSUE THREAD

**Issue by laverman** [eclipse/hawkbit#1008]
As requested by the EMO, we want to update the project from EPL 1.0 to EPL 2.0. 

**Why?**
> The EPL-1.0 has been deprecated; and in order to reduce license proliferation, the Eclipse open source project community will begin to migrate to the new EPL-2.0.

cf. https://www.eclipse.org/legal/epl-2.0/faq.php#h.60mjudroo8e5 

**What are the major changes between EPL-1.0 and EPL-2.0?**
The term of art is now referred to as "file" rather than "module";
* The choice of law provisions has been removed;
* The license is now suitable for scripting languages such as JavaScript; and
* The license now includes an option to add a secondary license for GPL-2.0+ compatibility.
cf. https://www.eclipse.org/legal/epl-2.0/faq.php#h.a0eux401qus

**Comment by avgustinmm** [comment]
done
