### ISSUE TITLE
UI bug with Action History table header

### ISSUE THREAD

**Issue by Sergey-G-dev** [eclipse/hawkbit#1014]
Hi everyone,

I've noticed a small but annoying UI bug. In Deployment View, Action History table header, when I select the target ID by double clicking on the ID string, the word "for" gets selected as well. This looks like a bug, since only one word should be selected by double clicking on it. It is possible to fix in a couple of ways, for example, by adding a colon to "for" or by inserting a dummy label with empty caption in between, but there should be a better/cleaner solution. Any ideas?

![Header caption](https://i.imgur.com/AEoWHp8.png)

**Comment by schabdo** [comment]
Thanks for bringing this up. I think this issue was there even before the Vaadin 8 upgrade. Nevertheless, of course we should fix this

**Comment by Sergey-G-dev** [comment]
This looks like a Chrome specific issue. It does not occur with MS Edge and Firefox.

**Comment by Harshitjoshi133** [comment]
can i work on it

**Comment by avgustinmm** [comment]
Vaadin 8 UI is discontinued - https://eclipse.dev/hawkbit/blog/2023-11-22-vaadin8_ui_discontinuation/
