### ISSUE TITLE
Drop support for MySQL 5.6

### ISSUE THREAD

**Issue by schabdo** [eclipse/hawkbit#1036]
MySQL 5.6 will reach EOL in 2021. Flyway `5.2.4` is the latest version still supporting MySQL 5.6. We won't be able to upgrade to a more recent version of Flyway until we discontinue support for MySQL 5.6 and move on to MySQL 5.7+.   

Furthermore new version of Flyway will have better support for MariaDB by means forcing the JDBC driver to report MariaDB as a MySQL is not required anymore (cf. `useMysqlMetadata` in [MariaDB connector parameters](https://mariadb.com/kb/en/about-mariadb-connector-j/#essential-parameters)) in order to get it running:   
```
org.flywaydb.core.api.FlywayException: Unsupported Database: MariaDB 10.5
```

**Comment by avgustinmm** [comment]
Obsolete, hawkBit already uses mysql 8.0
