### ISSUE TITLE
Allow changing tenant configuration and gateway token as properties

### ISSUE THREAD

**Issue by lab-w** [eclipse/hawkbit#1065]
**Problem**
I'm interested in setting the option "Allow a gateway to authenticate and manage multiple targets through a gateway security token" and in setting this token in a .yml file. Details are described in issue #1062 .

**Proposed Solution**
Allow setting the tenant configuration and the gateway token as environment variable properties. That way they could be picked up by Spring Boot during startup.

**Comment by schabdo** [comment]
It took a while but I found a way to set gateway token via environment properties (setting via `application.properties` works, too). This should do the trick:

```
HAWKBIT_SERVER_DDI_SECURITY_AUTHENTICATION_GATEWAYTOKEN_ENABLED=true
HAWKBIT_SERVER_DDI_SECURITY_AUTHENTICATION_GATEWAYTOKEN_KEY=<token>
```

Please let me know if it's working out for you or not

**Comment by maovidal** [comment]
Hi everyone:

Hope it is okay to mention this on a closed issue.

I just tested the current version with:

> ```
> HAWKBIT_SERVER_DDI_SECURITY_AUTHENTICATION_GATEWAYTOKEN_ENABLED=true
> HAWKBIT_SERVER_DDI_SECURITY_AUTHENTICATION_GATEWAYTOKEN_KEY=<token>
> ```

However, it didn't worked. The container keeps the previous key.

I also tried passing them via
> SPRING_APPLICATION_JSON: '{
>       ...
>       "hawkbit.server.ddi.security.authentication.gatewaytoken.enabled": true,
>       "hawkbit.server.ddi.security.authentication.gatewaytoken.key": "<token>",
>       ...
>  }

And I got the same result. 

I opted updating the Gateway Token via the API as my deployed devices already have a value.

Thank you!
