### ISSUE TITLE
SecurityToken Auth works per default without enabeling it in de Management UI

### ISSUE THREAD

**Issue by MrMedTech** [eclipse/hawkbit#1066]
Hi,
I use Hawkbit for the first time and in an explorative way.
Reading the docs, one should enable the usage of security token in the Authentication Configuration in the system config. 
In my case, this flow works without enabeling it.
Is that a default behaviour right now?
Because in the docs it is explicitly menioned that this feature has to be enabled.

**Comment by schabdo** [comment]
I double-checked behaviour and you're right. Currently it's possible to send a valid target token header even the setting is not enabled by default. However as soon as you enable/disable it within the UI everything is working as expected. I'll provide a fix for that asap ...
