### ISSUE TITLE
Getting error while transferring single artifact from host to target

### ISSUE THREAD

**Issue by abhi-84** [eclipse/hawkbit#1068]
Hi all
I am creating single file swu image and trying to send simple hello.py file from host machine to target board via hawkbit server. Suricatta is running on my target board.
I used following script to create swu image:

IMG_FILES="sw-description sw-description.sig hello.py"

for f in ${IMG_FILES} ; do
	echo ${f}
done | cpio -ovL -H crc > update.swu

Hawkbit and suricatta communicate and following error message is received on suricatta terminal. 
To my surprise, hello.py file is also transferred to desired location!

* [ERROR] : SWUPDATE failed [0] ERROR suricatta/server_hawkbit.c : server_hawkbit_error : 184 : No suitable .swu image found
Found bundle for host 10.168.2.58: 0xd0100 [serially]
[ERROR]* Re-using existing connection! (#1) with host 10.168.2.58
* Connected to 10.168.2.58 (10.168.2.58) port 8080 (#1)
> POST /DEFAULT/controller/v1/u54/deploymentBase/1/feedback HTTP/1.1
Host: 10.168.2.58:8080
User-Agent: libcurl-agent/1.0
Content-Type: application/json
Accept: application/json
charsets: utf-8
Content-Length: 197

 : SWUPDATE failed [0] ERROR suricatta/server_hawkbit.c : server_install_update : 1393 : Error processing update chunk named 'single-file', version 1.0, part bApp

Is their any specific swu format required by suricatta? I used same swu file with Mongoose web server and it works perfectly! 

Thanks

Abhishek

**Comment by schabdo** [comment]
> I used same swu file with Mongoose web server and it works perfectly

Have you tried to use `curl` in order to rule the server side out? 

> Is their any specific swu format required by suricatta?

I'm afraid I can't help out much here. You'd better raise this question within the [SWUpdate community](https://github.com/sbabic/swupdate#community-support)

**Comment by abhi-84** [comment]
Thanks for reply.
I am able to transfer artifact but as Application and not as OS. 
Thanks
