### ISSUE TITLE
Disable HTTP method

### ISSUE THREAD

**Issue by AalokSharma** [eclipse/hawkbit#1071]
Hi,

Is there any way to disable Http delete and trace methods ?

**Comment by schabdo** [comment]
Could you please elaborate a bit more on that (e.g. background of your question, which API, ...)?

**Comment by AalokSharma** [comment]
Hey Dominic,

Thanks for replying, my question was if it was possible to completely remove any  sort of HTTP TRACE or HTTP DELETE methods. So in short if these methods are invoked they shouldn't provide any response or maybe just reply with a "Forbidden" response. For both DDI and Management API's. 
Will this require a filter in the code?

Any guidance would be appreciated.
Thanks.

**Comment by schabdo** [comment]
I see, thanks for clarification. I think you'd have multiple options here: First put a reverse proxy in front of hawkBit and block all unwanted methods (e.g. via NGINX [limit](https://nginx.org/en/docs/http/ngx_http_core_module.html#limit_except)). This won't require any code change. Next option (as you already mentioned) would be to register custom filter/interceptor in the code. Last but not least leveraging Spring Security config ( e.g. `...antMatchers(HttpMethod.DELETE, "/myPath").denyAll()`) should do the trick as well but haven't tried it out myself. Hope this helps to get you started
