### ISSUE TITLE
ManagementApi: Action does not have property containing rollout name

### ISSUE THREAD

**Issue by reppners** [eclipse/hawkbit#1103]
Hi, when experimenting with Hawkbit, the UI and the Management-Api I've noticed that the UI does show the rollout name if the action is created by a rollout, but the Action that can be retrieved via Management-Api does not have this property. Is this intentional?

**Comment by stefbehl** [comment]
Hello @reppners, thanks for pointing out this inconsistency between the Mgmt UI and Mgmt API. We agree that this should be fixed by adding the reference to the enclosing rollout (probably name and link). We'll keep you posted...

Thanks and regards
Stefan

**Comment by stefbehl** [comment]
Our proposal would be to not only add the missing 'rolloutName' property but also provide a link to the rollout. Both, the new property and the link, would be optional.

Example:
`
{
  "createdBy" : "bumlux",
  "createdAt" : 1617968307580,
  [..]
  "rolloutName": "My 1st rollout",
  "_links" : {
    "self" : {
      "href" : "https://management-api.host.com/rest/v1/targets/137/actions/17"
    },
    "distributionset" : {
      "href" : "https://management-api.host.com/rest/v1/distributionsets/16"
    },
    "status" : {
      "href" : "https://management-api.host.com/rest/v1/targets/137/actions/17/status?offset=0&limit=50&sort=id:DESC"
    },
    "rollout" : {
      "href" : "https://management-api.host.com/rest/v1/rollouts/12"
    }
  },
  "id" : 17,
  "forceType" : "timeforced"
}
`

Are you interested in contributing to Eclipse Hawkbit (find more details in the [Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#contributing)? This might be a good task to start with. We could also provide help (pointers to the code) if needed.

This is only an option. If you are not interested, it is also fine. Then we will provide a pull request for this issue.

Thanks and regards
Stefan

**Comment by reppners** [comment]
Since this is day-job related and I'm basically swamped with work I'll check back with the team to decide if time can be allocated to implementing this PR :)

**Comment by reppners** [comment]
I'm sorry but due to time constraints I'm unable to work on a PR.
