### ISSUE TITLE
Rest Api For Validate queries in Target Filters

### ISSUE THREAD

**Issue by KOTTIRAMSAI** [eclipse/hawkbit#1149]
Can anyone help me! in figuring out the Rest Api for validating a querie While creating a filter in **target filter Screen**

![Target Filter Query](https://user-images.githubusercontent.com/26092894/126940454-bb39b425-9652-4613-b804-4a886af9df5e.png)

**Comment by bogdan-bondar** [comment]
The answer is already provided under #1163
