### ISSUE TITLE
Rest Api For getting list of Targets based on Filters in Target Filter Screen

### ISSUE THREAD

**Issue by KOTTIRAMSAI** [eclipse/hawkbit#1150]
can any one help me! in figuring out Rest Api To getting list of Tragets Based On Filter Value 

![image](https://user-images.githubusercontent.com/26092894/126940896-0547548a-7715-4535-a487-4199a4bec305.png)

**Comment by singrob** [comment]
You can use the targets REST API and pass the filter as a query:

Using the filter from your screenshot the REST call would look like this: 
`curl --request GET 'https://hawkbit.eclipseprojects.io/rest/v1/targets?q=updatestatus==registered' \
--header 'Authorization: Basic ZGVtbzpkZW1v'`

Further information regarding the targets API can be found in the documentation:
[](https://www.eclipse.org/hawkbit/apis/mgmt/targets/)

**Comment by KOTTIRAMSAI** [comment]
@singrob Thanks For Your Response! 
    Now We are able to get the list of targets based on query.Can you Please Help Me! Validating the query Api
![image](https://user-images.githubusercontent.com/26092894/127511826-c937b5fe-4000-4aa1-b4a3-37c9351accf0.png)

**Comment by bogdan-bondar** [comment]
The answer is already provided under #1163
