### ISSUE TITLE
Unable to log in after the docker container is up for some random time

### ISSUE THREAD

**Issue by ycsin** [eclipse/hawkbit#1153]
Hi all,

I'm new to this. Following #1139 from #1138, I'm able to do [#b](https://www.eclipse.org/hawkbit/gettingstarted/#b-run-hawkbit-update-server-with-services-as-docker-compose) and log in to the Hawkbit UI. But after a random period of time I wouldn't be able to log in again and the purple progress bar will stuck at ~80%.

![image](https://user-images.githubusercontent.com/1563974/127087086-6f083746-a9b3-4e84-be23-f2516e21189c.png)

![image](https://user-images.githubusercontent.com/1563974/127087123-c2c51237-7a6b-4b46-abb8-cee35ba88574.png)

![image](https://user-images.githubusercontent.com/1563974/127088168-bb8308de-a62a-4c07-b28d-927f5a38f427.png)

`docker stop` and `docker restart` these containers wouldn't help, I have to `rm` them and do `docker-compose up -d` all over again before I can login.

Any clue? Thanks.

## Extra context

I mapped the hawkbit external port from the default 8080 to 9010 and have this behind nginx reverse proxy so that I can access it through `hawkbit.mydomain.com`.

## Log
[docker log.txt](https://github.com/eclipse/hawkbit/files/6882349/docker.log.txt)

I'm not sure what's this
```
Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=mysql)(port=3306)(type=master) : (conn=50) Access denied for user 'root'@'172.18.0.3' (using password: NO)
```

172.18.0.3 isn't the IP of the server nor the connecting client.

**Comment by ycsin** [comment]
Likely due to the deprecated variable in [docker-compose.yaml](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/docker/docker-compose.yml#L19), seems to run fine after removing it.

**Comment by bogdan-bondar** [comment]
@ycsin could if I got it correct your issue is resolved. So I will close it for now, feel free to re-open it in case you face further problems
