### ISSUE TITLE
About the hawkbit security vulnerability using java 8.

### ISSUE THREAD

**Issue by harami-eng** [eclipse/hawkbit#1155]
I'm worried about hawkbit using java8, because it has been pointed out that there is a security vulnerability in java 8. (Issue #964) 
Will this problem be solved by updating the java runtime to the latest version?
If I don't use the security features of hawkbit, what other steps can I take?

**Comment by bogdan-bondar** [comment]
@harami-eng starting from https://github.com/eclipse/hawkbit/commit/ed9a4b1bb31f4cd996e8af8867d67cdcda682d00 Hawkbit is able to be built/run with jdk/jre 11. Additionally, most of Hawkbit security features are based on Spring Boot http controller filters. Could you elaborate on particular vulnerabilities you are concerned with?
