### ISSUE TITLE
Force Quit  an Action in Deployment Page

### ISSUE THREAD

**Issue by KOTTIRAMSAI** [eclipse/hawkbit#1163]
Hi! Can Anyone Help Me! In Figuring out the Rest Api for force quiting an action in deployment page
![force](https://user-images.githubusercontent.com/26092894/128974117-d7a4b356-d58c-4b7f-8d49-ba86f708f910.png)

**Comment by floruschbaschan** [comment]
Hey @KOTTIRAMSAI, you can find the necessary information in our documentation of the [MGMT API - cancel an active action](https://www.eclipse.org/hawkbit/rest-api/targets-api-guide/#_delete_rest_v1_targets_targetid_actions_actionid). The request query parameter `force` defines if the action will be force canceled or not.

**Comment by KOTTIRAMSAI** [comment]
@floruschbaschan Thanks You!

I am having One more doubt regarding in Traget Filter screen! can we have any rest api for query validation 
![Target Filter Query](https://user-images.githubusercontent.com/26092894/129666215-66586203-c4bf-4c04-b723-c7c038453818.png)

**Comment by floruschbaschan** [comment]
Hey @KOTTIRAMSAI, yes you can make use of the `query` parameter for several requests. E.g. retrieving all available `targets` ([see details here](https://www.eclipse.org/hawkbit/apis/mgmt/targets/)) that match your query:
`GET https://my-hawkbit/rest/v1/targets?q=name==` would result in:
```
{
    "exceptionClass": "org.eclipse.hawkbit.repository.exception.RSQLParameterSyntaxException",
    "errorCode": "hawkbit.server.error.rest.param.rsqlParamSyntax",
    "message": "The given search parameter is not well formed"
}
```
while `https://hawkbit.eclipseprojects.io/rest/v1/targets?q=name==*` would give you all existing targets.

**Comment by KOTTIRAMSAI** [comment]
@floruschbaschan Thanks for your support!

**Comment by KOTTIRAMSAI** [comment]
hi @floruschbaschan!
<img width="817" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/26092894/129906482-b6858aca-e7dd-408a-ad78-663e8e57eeee.png">
 I have a doubt then how can we get the count we are using rest api for integarting?

**Comment by floruschbaschan** [comment]
Hey @KOTTIRAMSAI, I have already answered that. Sorry that this answer was not very understandable. The auto assignment is based on a target filter. Similar to a target filter query, you make use of the `query` parameter for several REST requests. This would help you to see e.g. how many targets would be affected by such a query by checking the `total` amount in the reply.

Example:
Available target names: target1, target12, target23
`GET https://my-hawkbit/rest/v1/targets?q=name==*1*` would give you a response with 2 targets and a `total` of 2.

**Comment by bogdan-bondar** [comment]
@KOTTIRAMSAI There is no dedicated API to retrieve this information except of the way proposed by @floruschbaschan. I will close the issue for now, in case you need further clarifications please re-open/open another issue or post your question in official Gitter channel
