### ISSUE TITLE
Cancel an Action in deployment page

### ISSUE THREAD

**Issue by KOTTIRAMSAI** [eclipse/hawkbit#1164]
Hi! Can Anyone Help Me! In Figuring out the Rest Api for Cancel an action in deployment page
![cancel](https://user-images.githubusercontent.com/26092894/128974522-afc5cb54-7175-45f4-b0fa-a6eda9319472.png)

**Comment by floruschbaschan** [comment]
Hey @KOTTIRAMSAI, see https://github.com/eclipse/hawkbit/issues/1163.

**Comment by KOTTIRAMSAI** [comment]
@floruschbaschan Thanks for your Help
