### ISSUE TITLE
How can we get count in Target Filter  Screen! When we Auto Assign the Distrubution set 

### ISSUE THREAD

**Issue by KOTTIRAMSAI** [eclipse/hawkbit#1166]
Hi Can Any One Help me! How can we get the count when we assign distrubution set for targets can we have any Rest api related to that 

![Auto assign](https://user-images.githubusercontent.com/26092894/129667445-e27d0475-c77e-44f1-9192-4f8b4b7c0558.png)

**Comment by bogdan-bondar** [comment]
The answer is already provided under https://github.com/eclipse/hawkbit/issues/1163
