### ISSUE TITLE
typos in "entitiyAlreayExists" error

### ISSUE THREAD

**Issue by martinetd** [eclipse/hawkbit#1192]
Hello,

I'm writing some script hitting the management API and these typos hurt my eyes (entitiyAlreayExists -> entity, Already) ...
But if people are relying on it it might not be worth changing -- in which case a comment in hawkbit-core/src/main/java/org/eclipse/hawkbit/exception/SpServerError.java might be good?

(I'll just look at the exceptionClass instead of the errorCode for now)

Thanks,

**Comment by bogdan-bondar** [comment]
Hi! Yes, you are right, unfortunately we can't change it now as it would be an API breaking change. We would consider changing/fixing such issues within version 2 of the API or within a next milestone. However we can't do anything right now.
