### ISSUE TITLE
Update Status on Hawkbit Server

### ISSUE THREAD

**Issue by mamtasingh2304** [eclipse/hawkbit#1206]
I want to know that is there any other option instead of -c to update the pending status on server. actually I am running sw update via enabling suricatta daemon. I am able to succesfully update and install. but I found the status on server was still pending and after that I reboot the device and then restart the swupdate with  -c 2 option and sent confirmation on server then server status become finished so , I want to check is there any other or better way to do that .

**Comment by bogdan-bondar** [comment]
Hi! Sorry, but this question is not related to Hawkbit server. Hawkbit just reflects the feedback given by the client, thus client behaviour is transparent for the server. Please post your question in the used client(sw-update) thread/repo.
