### ISSUE TITLE
tl_sp_action ，exception   doesn't exist

### ISSUE THREAD

**Issue by Spymasters** [eclipse/hawkbit#1210]
init table only 26 ，not tl_sp_action ，error：
Exception on forEachTenant execution for tenant DEFAULT with error message [null; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: (conn=32111850) Table 'edge_hue.tl_sp_action' doesn't exist]. Continue with next tenant.

**Comment by bogdan-bondar** [comment]
Sorry, but I would need to close your issue as invalid. Please in the future provide the meaningful title and description with the used hawkbit versions, steps to reproduce, underlying set up, etc. 
Just a small remark regarding the plain log output: it seems you have defined your own DB schema and somehow the tables prefix, however Hawkbit expects the exact table names, e.g. `sp_action`. Please verify the correspondence and issue the well-defined issue in case you need further support
