### ISSUE TITLE
Operation is documented twice: DELETE /rest/v1/distributionsettypes/{distributionSetTypeId}/mandatorymoduletypes/{softwareModuleTypeId}

### ISSUE THREAD

**Issue by zyga** [eclipse/hawkbit#1245]
There are two separate fragments of documentation relating to removing a software module type from a distribution set type mandatory list:

https://www.eclipse.org/hawkbit/rest-api/distributionsettypes-api-guide/#_delete_rest_v1_distributionsettypes_distributionsettypeid_mandatorymoduletypes_softwaremoduletypeid

and 

https://www.eclipse.org/hawkbit/rest-api/distributionsettypes-api-guide/#_delete_rest_v1_distributionsettypes_distributionsettypeid_mandatorymoduletypes_softwaremoduletypeid_2

The documentation also differs between the two instances:
- 1st link documents the response type.
- different apparent permissions are required

It would be good to remove the one that is incorrect.

**Comment by superkartoffel** [comment]
At this point it is not documented anymore at all. The links are dead.

**Comment by strailov** [comment]
Hey @superkartoffel 
There seems to be problem with the hawkbit website update. I have created an issue in eclipse https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3538

**Comment by avgustinmm** [comment]
Actually the api documents (at least old versions) are available and could be seen with direct links, e.g.:
https://eclipse.dev/hawkbit/rest-api/distributionsettypes-api-guide.html

**Comment by superkartoffel** [comment]
Ha, that would have saved me some time building the documentation locally :wink: 
Thank you @strailov @avgustinmm

**Comment by avgustinmm** [comment]
Seem ok at the moment
