### ISSUE TITLE
Sandbox link on website not found

### ISSUE THREAD

**Issue by calohmn** [eclipse/hawkbit#1257]
On the "Getting Started" page (https://www.eclipse.org/hawkbit/gettingstarted/) the hawkBit sandbox is linked to https://hawkbit.eclipse.org/. This page is not found.

It looks like the link should be updated to https://hawkbit.eclipseprojects.io.

**Comment by Sherry112** [comment]
Yes, please.

**Comment by AndreRicardo-Zoetis** [comment]
Is this still an issue? The url looks correct now, it was fixed in https://github.com/eclipse/hawkbit/pull/1303/files. 

Can this issue be closed?
