### ISSUE TITLE
Docker deploy Hawkbit_msyql constantly stops each 24h and deletes "hakwbit" database

### ISSUE THREAD

**Issue by TopperBG** [eclipse/hawkbit#1264]
Already 5 deployed  docker install ([plan B](https://www.eclipse.org/hawkbit/gettingstarted/#b-run-hawkbit-update-server-with-services-as-docker-compose) and [plan C](https://www.eclipse.org/hawkbit/gettingstarted/#c-run-hawkbit-update-server-with-services-as-docker-stack)). With external volume for MySQL and w/o external mount both ways are tested.
Uploaded 100-150 test devices with .cvs import, created ONE deployment and ONE rollout. Made few test with SWUpdate on our devices.
Around 24h or so, not exactly but next day, Mysql container was stoped with "completed" (around 5 time till now) and log
[02gdg0qpj61r44xw2gsakyn4z_logs.txt](https://github.com/eclipse/hawkbit/files/9025279/02gdg0qpj61r44xw2gsakyn4z_logs.txt)
Container with such IP adress DOESNT exists !
Stack manager started new instance, inside which missing "hawkbit" data base:
[xrj24213cjalqfnmm0oo6b2nz_logs.txt](https://github.com/eclipse/hawkbit/files/9025287/xrj24213cjalqfnmm0oo6b2nz_logs.txt)

![image](https://user-images.githubusercontent.com/23097319/176829210-973ec017-a0c3-4223-9f17-8b344397e419.png)
What happens, stacks behavior like sandbox ?
Am I wrongly understand guide for install  ?

**Comment by TopperBG** [comment]
Hm btw is it normal to find in external mount to MySQL container such folder ?
```
Z_README_TO_RECOVER:
total 120
drw-rw-rw- 2 root             root              4096 Jun 30 20:27 ./
drwxr-xr-x 6 systemd-coredump root              4096 Jul  1 08:31 ../
-rw-r----- 1 systemd-coredump systemd-coredump    65 Jun 30 20:27 db.opt
-rw-r----- 1 systemd-coredump systemd-coredump  8560 Jun 30 20:27 RECOVER_YOUR_DATA.frm
-rw-r----- 1 systemd-coredump systemd-coredump 98304 Jun 30 20:27 RECOVER_YOUR_DATA.ibd
```
Or to consider there is vulnerability in Hawkbit manager and we are breached ?

**Comment by avgustinmm** [comment]
outdated and seems like nothing related to hawkBit docker files. also have in mind that these docker setups are just examples and nothing that shall be considered as stable / production ready
