### ISSUE TITLE
Image is outdated

### ISSUE THREAD

**Issue by kareemZarka** [eclipse/hawkbit#1268]
The hawkbit image is super outdated ..
it would be nice to get it updated so that we at least have the latest features ex Target-types ..
Thnaks

**Comment by jflambert** [comment]
do you mean the images on dockerhub?

If so I agree!!!

Who is @crunchyone on dockerhub?

https://hub.docker.com/r/hawkbit/hawkbit-update-server

**Comment by laverman** [comment]
We are happy to tell you, that the images have been updated, and the latest milestone 0.3.0M8 is available:
* latest
* latest-mysql
* 0.3.0M8
* 0.3.0M8-mysql

**Comment by kareemZarka** [comment]
great news @laverman ! thank you
