### ISSUE TITLE
Website redirects to projects.eclipse.org/projects/iot.hawkbit

### ISSUE THREAD

**Issue by diegorondini** [eclipse/hawkbit#1300]
```
$ curl https://www.eclipse.org/hawkbit/
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://projects.eclipse.org/projects/iot.hawkbit">here</a>.</p>
</body></html>
```

**Comment by diegorondini** [comment]
Likely related to:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/732

@laverman You developed the hugo website, can you have a look?

**Comment by laverman** [comment]
Hi @diegorondini - I've got aware of it last week. I'll have a look, but not sure if I'll be able to solve it this year as my Christmas break is right around the corner.

Thanks for creating the issue 👍🏻

**Comment by shaig4** [comment]
is there a temporary workaround to view the hawkbit documentation?

Thanks, Enjoy you Christmas vacation!

**Comment by eclipsewebmaster** [comment]
@laverman we did not receive any feedback about the future of the hawkbit project website in ticket https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1804.

If you approve, we can move the original project website repository from https://git.eclipse.org/r/www.eclipse.org/hawkbit.git to https://github.com/eclipse/hawkbit-website and redirect to it from https://www.eclipse.org/hawkbit/.

**Comment by laverman** [comment]
@eclipsewebmaster that would be great, if you could do that 👍🏻

**Comment by eclipsewebmaster** [comment]
Done. Repo was moved to https://github.com/eclipse/hawkbit-website. The Gerrit repo will be set to read-only. Committers will gain access to the new repo once the sync script runs (~2-4h).

**Comment by eclipsewebmaster** [comment]
https://www.eclipse.org/hawkbit/ should work again. You might need to clear your browser cache.
