### ISSUE TITLE
hawkBit update stays pending with SWUpdate as client

### ISSUE THREAD

**Issue by ngoettin** [eclipse/hawkbit#1321]
I started using hawkBit together with SWUpdate and it all worked really well so far. However, after SWUpdate installs the provided updates, the hawkBit server still shows that the action is pending.

When watching the traffic between these two applications, I found two things:

 1. I get a `hawkbit.server.error.quota.tooManyEntries`, because SWUpdate sends many messages. I don't think this is the issue, but I'd be glad to hear how this quota can be increased.
 2. I get a `hawkbit.server.error.repo.constraintViolation` and assume that this might the reason for the issue.

This `constraintViolation` occurs, because one element of the `details` list in the message sent by SWUpdate is `"[channel_log_reply] : The error message is:  { exceptionClass : org.eclipse.hawkbit.repository.exception.AssignmentQuotaExceededException , errorCode : hawkbit.server.error.quota.tooManyEntries , message : Quota exceeded: Cannot assign 51 more Message entities to ActionStatus  <new> . The maximum is 50. } ",`. However, as hawkBit only allows `Safelist.none()`-clean strings, the `<new>` is a problem.

So, I believe the problem is that hawkBit sends an "unclean" string, which gets sent back as log and is then refused, because it's "unclean" in the sense that `cleaner.isValid(stringToDocument(string))` returns `false`.

Maybe it would be a good idea for hawkBit to only send clean strings? Are there any workarounds?

Thanks a lot!

**Comment by ngoettin** [comment]
Seems like I needed to manually POST the success message to hawkBit. The initial problem is therefore solved, so I'll close the issue. I still think, hawkBit should not send messages it considers unsafe, though.

**Comment by calliday** [comment]
> Seems like I needed to manually POST the success message to hawkBit. 

@ngoettin How did you perform a manual POST? Did you accomplish this through a Lua module? Did you need some external service?

**Comment by ngoettin** [comment]
I don't really remember what I did back then, but suricatta has a `-c` cli argument, with the possible values `1=AGAIN, 2=SUCCESS, 3=FAILED`. Just start with `-c 2` and the server knows that the update finished successfully
