### ISSUE TITLE
No new release after 0.3.0M7? 

### ISSUE THREAD

**Issue by Raven888888** [eclipse/hawkbit#1334]
Is this project still ongoing? I can see dev on master branch, but no releases?

**Comment by MartB** [comment]
See https://github.com/eclipse/hawkbit/pull/1320 and https://github.com/eclipse/hawkbit/milestone/23

**Comment by Raven888888** [comment]
Thanks very much @MartB 
Do you happen to know of the upcoming roadmap for this project, short or medium term? #889 was more than 3 years ago, and the team [stops](https://www.eclipse.org/hawkbit/community/) sending out community update since 2020.
Or is there other fork?

**Comment by MartB** [comment]
I'm not involved with Bosch, but I assume they did not get much time allocated to work on hawkbit. This has changed lately, as they clearly want to get things done CVE-fixing-wise. Some PRs from external authors were also merged, which was a problem in the past.
The spring framework upgrade is a worthwhile step and the new "consent flow" feature is a clear indicator that development is still important to Bosch.

That's admittedly far from a roadmap, but I would say we are in a healthier place than before.
No forks afaik, but I'm sure it will happen if the past repeats itself.

Maybe @stefbehl can chime in on this.

**Comment by Raven888888** [comment]
@MartB That's really great to hear!

Our company is at the end of hawkbit evaluation, and we are looking at 20k devices at the end of rollout (whenever that may be). So, your feedback certainly add positives to our evaluation. Thanks again!

**Comment by stefbehl** [comment]
Thanks for jumping in @MartB!

@Raven888888 The project is definitely alive! The new milestone release will contain lots of new features e.g.
* User Consent Flow
* Invalidation of distribution sets
* New resource collection /rest/v1/actions
* Manually trigger next rollout group
* Target types
* ...
And a lot more...

Our plan was to release M8 earlier, but it would not have made sense to release M8 based on Spring Boot 2.3. The boot migration is about to be finalized and then we will build and release 0.3.0.M8.

Thanks for your understanding and patience!

**Comment by Raven888888** [comment]
@stefbehl Thanks! We certainly understand and are patient too! :)

Closing this as I've got the answers.
