### ISSUE TITLE
How to update Action State status?

### ISSUE THREAD

**Issue by Sourabh-ALTEN** [eclipse/hawkbit#1342]
Hello All,

I am trying to chnage the "Action State" status to "Error" from a bash script. I am using below API call to update it.
`POST /{tenant}/controller/v1/{controllerid}/deploymentBase/{actionId}/feedback` 

```
response=$(curl -sS --location "${HEADERS[@]}" -w "%{http_code}\n" -X POST "$url" --header 'Content-Type: application/json' \
                        --data-raw  "{
                                \"id\" : \"$action_id\",
                                \"status\" : {
                                        \"result\" : {
                                                \"progress\" : {
                                                                \"of\" : 5,
                                                                \"cnt\" : 2
                                                },
                                        \"finished\" : \"failure\"
                                        },
                                \"execution\" : \"canceled\",
                                \"details\" : [ \"Failed\" ]
                                }
                        }")
```

I have also tried `\"execution\" : \"rejected\"`. But it doesn't work.
![image](https://user-images.githubusercontent.com/104615913/230038082-5c0d64ec-794d-42c9-bd72-c08cc596c337.png)

I am expecting something like this

![image](https://user-images.githubusercontent.com/104615913/230038519-c691a42c-efe2-43ec-8a2b-2a6cebc05421.png)

Which value should be used in `\"execution\" : \"rejected\"` to change the status to `Error` and and close the Action?

**Comment by strailov** [comment]
Hello @Sourabh-ALTEN ! 
For historical reasons the DDI has a different state machine and status messages than the Target State Machine of the hawkBit update server.
You can see the state machine mapping here https://www.eclipse.org/hawkbit/apis/ddi_api/ . 

To answer your question in order to get Error in the Hawkbit UI you should provide "finished" : "failure" in the request combined with "execution" : "closed". This way you tell hawkbit that the action is finished (by execution closed) and finished with failure - so this would mean error.

**Comment by Sourabh-ALTEN** [comment]
Hello @strailov yes, it worked.
Thank you

**Comment by Sourabh-ALTEN** [comment]
Hello @strailov sorry for re-opening the issue again. I wanted to know the functionality of 
```
                         \"progress\" : {
                                                                \"of\" : 5,
                                                                \"cnt\" : 2
                                                },
```

How to make use of `of` and `cnt` values? What effect will it have?

Thank you

**Comment by strailov** [comment]
Hello @Sourabh-ALTEN ! 
Basically it is something like an action fulfillment progress by means of gives the achieved amount of maximal of possible levels.
This is a way for the target to somehow report its software update progress. As far as I know it is not mandatory.
 `cnt` is the achieved amount (could be percent, or count of installed artefacts etc) and `of` is the maximum achievable amount.
