### ISSUE TITLE
Unable to authenticate using H2 database on 0.3.0M8 (Function "IDENTITY" not found)

### ISSUE THREAD

**Issue by zyga** [eclipse/hawkbit#1364]
It seems that there's some problem with the new milestone, at least when using the h2 database:

```
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]: Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Function "IDENTITY" not found; SQL statement:
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]: CALL IDENTITY() [90022-214]
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.message.DbException.getJdbcSQLException(DbException.java:632)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.message.DbException.get(DbException.java:223)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.message.DbException.get(DbException.java:199)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.command.Parser.getFunctionAliasWithinPath(Parser.java:2519)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.command.Parser.readTableFunction(Parser.java:2012)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.command.Parser.parseCall(Parser.java:6996)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.command.Parser.parsePrepared(Parser.java:765)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.command.Parser.parse(Parser.java:689)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.command.Parser.parse(Parser.java:661)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.command.Parser.prepareCommand(Parser.java:569)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1611)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.prepareStatement(DatabaseAccessor.java:1558)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.prepareStatement(DatabaseCall.java:762)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:628)
May 16 10:50:42 oxenfurt hawkbit.hawkbit[3756673]:         ... 234 common frames omitted
```

**Comment by strailov** [comment]
Hey @zyga ! 
Thanks for posting this issue. 
I tried to reproduce this but it seems to work with my local setup... Can you provide more info about your setup and when this happens and so on ? Is it happening on application start or when making a call to h2 ?

**Comment by zyga** [comment]
The error shows up immediately when I try to log in. I tried reproducing it on the 0.3.0M8 jar and then it worked? I suspect something in my system is causing this but I have no idea yet.

**Comment by zyga** [comment]
I can reproduce this on a vanilla release jar as well.

**Comment by zyga** [comment]
I've managed to reduce the problem to defining a persistent H2 database:

```
spring.datasource.url=jdbc:h2:file:/home/zyga/hawkbit-database;MODE=MySQL
```

The path doesn't matter, with this in place I cannot log in. With this removed (using H2 in memory) I can log in.

**Comment by zyga** [comment]
Looking at H2 docs: http://www.h2database.com/html/features.html#compatibility this comes to mind: 

> REGULAR Compatibility mode
>
> This mode is used by default.
>
>     Empty IN predicate is allowed.
>     TOP clause in SELECT is allowed.
>     OFFSET/LIMIT clauses are allowed.
>     MINUS can be used instead of EXCEPT.
>     IDENTITY can be used as a data type.
>     Legacy SERIAL and BIGSERIAL data types are supported.
>     AUTO_INCREMENT clause can be used instead of GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY. 

I'm not a database person but it seems that the MODE= suggestion (that used to be MySQL for hawkbit) is now wrong?

**Comment by zyga** [comment]
I can login with `spring.datasource.url=jdbc:h2:file:/home/zyga/hawkbit-database;MODE=LEGACY`

**Comment by zyga** [comment]
It seems that LEGACY mode doesn't really work as well, there's an error related to IDENTITY whenever I try to create any database records.

**Comment by strailov** [comment]
> Looking at H2 docs: http://www.h2database.com/html/features.html#compatibility this comes to mind:
> 
> > REGULAR Compatibility mode
> > This mode is used by default.
> > ```
> > Empty IN predicate is allowed.
> > TOP clause in SELECT is allowed.
> > OFFSET/LIMIT clauses are allowed.
> > MINUS can be used instead of EXCEPT.
> > IDENTITY can be used as a data type.
> > Legacy SERIAL and BIGSERIAL data types are supported.
> > AUTO_INCREMENT clause can be used instead of GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY. 
> > ```
> 
> I'm not a database person but it seems that the MODE= suggestion (that used to be MySQL for hawkbit) is now wrong?

Well MODE=MySQL still seems to be present into the h2 docs it seems ... Not sure what is happening yet tho ...

**Comment by zyga** [comment]
Can you reproduce that with MODE=MySQL?

**Comment by zyga** [comment]
Thank you for trying. I wonder what else differs.

**Comment by strailov** [comment]
According to the commits of @stefbehl  when he was doing the spring boot migration - https://github.com/eclipse/hawkbit/pull/1320/commits/f4ced616e4b7163496ace75598e42f9266d2607f
in hawkbit-jpa-defaults.properties he changed 
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL; 
to 
spring.datasource.url=jdbc:h2:mem:testdb;MODE=LEGACY;
Seems that my property wasn't overridden for some reason and it was taken from there ... But now I tried MySQL but I didn't get any exception I just cannot login, but it seems everything to be ok with LEGACY mood which probably should be used.

**Comment by zyga** [comment]
@strailov bump logging to DEBUG to see the failures. 

I tried using LEGACY mode but that crashes when you try to create any records.

**Comment by strailov** [comment]
Yes, this should be even enabled by default.
