### ISSUE TITLE
Is clustering still considered experimental?

### ISSUE THREAD

**Issue by marcel-ithinx** [eclipse/hawkbit#1365]
In https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/hawkbit-update-server/README.md clustering is mentioned as still being experimental. Is that still true? The clustering section in the README got introduced in 2016 and the experimental hint is there since then. (https://github.com/eclipse/hawkbit/commit/866bc721148ffda8cc9aec23db443551b7dcb905)

I'm asking since in our company we're arguing to use Hawkbit but people find the "experimental" hint concerning.

**Comment by strailov** [comment]
Hey @marcel-ithinx ! 
It is not considered "experimental" . Not sure why it is said so in the README ... Probably we have forgotten to update this.

**Comment by marcel-ithinx** [comment]
Alright, thanks for the info! Feel free to close the issue :)

**Comment by frjonsen** [comment]
@strailov Could you expand on this? My company is currently running a single instance, but want to be able to run it in a cluster for horizontal scaling. I was already trying to figure out the implication of the [known issues](https://www.eclipse.org/hawkbit/guides/clustering/), but it doesn't mention any potential issues with the distribution lock. Or is that a part of the issues mentioned about schedulers?

**Comment by strailov** [comment]
Yes I think it is exactly the part about schedulers ...
