### ISSUE TITLE
Artifact URL generator does not respect SERVER_SERVLET_CONTEXT_PATH

### ISSUE THREAD

**Issue by frjonsen** [eclipse/hawkbit#1372]
For context, we are hosting Hawkbit behind an AWS API Gateway and are using path routing at `/hawkbit`. Passing in `SERVER_SERVLET_CONTEXT_PATH=/hawkbit` mostly works fine, as the Spring Boot framework will properly handle it. However, this environment variable is not taken into account in [`ArtifactUrlHandlerProperties`](https://github.com/eclipse/hawkbit/blob/eb8d5597805e57109a0615c94bfaa3e688d7abdc/hawkbit-core/src/main/java/org/eclipse/hawkbit/api/ArtifactUrlHandlerProperties.java#L60), so the URLs are generated without the extra context paths, resulting in 404's.

For anyone else who encounters this, we found a workaround in setting `hawkbit.artifact.url.protocols.download-http.ref={protocol}://{hostnameRequest}:{portRequest}${SERVER_SERVLET_CONTEXT_PATH:}/{tenant}/controller/v1/{controllerId}/softwaremodules/{softwareModuleId}/artifacts/{artifactFileName}.`, which seems to work well so far.

**Comment by avgustinmm** [comment]
Hi @frjonsen, 
I think that it would be good if hawkBit start to consider SERVER_SERVLET_CONTEXT_PATH by default. It seems that only change that this would require would be to change the default [ArtifactUrlHandlerProperties#ref](https://github.com/eclipse/hawkbit/blob/master/hawkbit-core/src/main/java/org/eclipse/hawkbit/api/ArtifactUrlHandlerProperties.java#L61) value to:
```
private String ref = "{protocol}://{hostname}:{port}${SERVER_SERVLET_CONTEXT_PATH:}/{tenant}/controller/v1/{controllerId}/softwaremodules/{softwareModuleId}/artifacts/{artifactFileName}";
```
Would you like to make a PR for that fix? Alternatively, I could add this change.

**Comment by frjonsen** [comment]
If you don't mind, it may be best if you do it. I rarely write Java and am not too comfortable with the appropriate way of reading properties in Spring.

**Comment by avgustinmm** [comment]
It was a little bit more complex but the support is added with https://github.com/eclipse/hawkbit/pull/1433.
Your current approach with setting ref with _${SERVER_SERVLET_CONTEXT_PATH:}_ will still work - spring replace that path with a constant. But if you don't override ref (and use default one) it will have holder {contextPath} which will be replaced with ${SERVER_SERVLET_CONTEXT_PATH:} .
