### ISSUE TITLE
Switch to Tomcat

### ISSUE THREAD

**Issue by avgustinmm** [eclipse/hawkbit#1378]
Currently hawkBit explicitly removes the default Spring Boot web server Tomcat and uses Jetty. It seems that there is no explicit reason to do that?

Also, soon 2.7 line of Spring Boot would reach its EOL - [Spring Boot - EOL](https://endoflife.date/spring-boot). So, until 18 Nov 2023, hawkBit shall be migrated to Spring Boot 3.0. However, Jetty doesn't support Servlet 6.0 and a downgrade is needed if migrating to 6.0 - [Spring-Boot-3.0-Migration-Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide). 

> Jetty does not yet support Servlet 6.0. To use Jetty with Spring Boot 3.0, you will have to downgrade the Servlet API to 5.0. You can use the jakarta-servlet.version property to do so.

So, some hacks might be needed in order to keep Jetty. Jetty could release a version with Servlet 6.0 support but anyway it seams that Jetty and Spring Boot are not in complete sync. 

Been the default web server for Spring Boot I would expect that Tomcat will be always the best fit for hawkBit which uses Spring Boot extensively.

So, maybe hawkBit shall switch to Tomcat?

**Comment by strailov** [comment]
Hey Avgustin, 
I completely agree with that.
