### ISSUE TITLE
Switch to EPL 2.0 License

### ISSUE THREAD

**Issue by avgustinmm** [eclipse/hawkbit#1393]
It would be good to switch to the newer EPL version 2.0.
Some clarification about how to could be found at [How Do I Re-license from EPL-1.0 to EPL-2.0](https://www.eclipse.org/legal/epl-2.0/faq.php#h.tci84nlsqpgw).
It seems that just modification in the pom files, file header and notification to the community is needed.

**Comment by avgustinmm** [comment]
Since no objections here and in gitter I think we shall do this. 
Any objections?

**Comment by strailov** [comment]
I think it is okay if we proceed with it.

**Comment by avgustinmm** [comment]
Actually such task already exist since 2020 - https://github.com/eclipse/hawkbit/issues/1008
And there were no objections yet.
So, I'm starting work on it

**Comment by avgustinmm** [comment]
done
