### ISSUE TITLE
Deleted Distributions/Rollouts are not actually deleted from the database

### ISSUE THREAD

**Issue by nealjack** [eclipse/hawkbit#1395]
Using the hawkbit UI, creating a distribution or a rollout seems to be permanently added to the mysql database, even if those elements are later deleted.

For example, if I create a test distribution and run a rollout using this distribution:

<img width="793" alt="image" src="https://github.com/eclipse/hawkbit/assets/5566471/bcdddaf6-1b8f-4f30-9129-2867b8a672f2">

And then I cancel the rollout delete it and the distribution, and try to recreate the distribution and/or rollout, I get the following error:

<img width="801" alt="image" src="https://github.com/eclipse/hawkbit/assets/5566471/b7d44d37-da08-47e5-9a59-9511eb3ec3c7">

Even though the distribution/rollout list is empty and does not contain an entry for `test 0.0.1`.

**Comment by strailov** [comment]
Hello @nealjack  
Yes, this is the so called soft delete ... 
HawkBit does not remove the entity from the database because of its historical dependencies ...

**Comment by nealjack** [comment]
Thanks for the response!

Can you expand on the historical dependencies?

If a rollout or distribution is completed - all clients have either installed and confirmed the image, or cancelled their updates, what are the remaining dependencies?

If rollouts and distributions are permanent, it seems like there shouldn't even be a UI element to delete them, or if so, the elements should remain and have a visual indication (i.e. grayed out) that indicates they still exist in the system.

**Comment by strailov** [comment]
I get your point. 
The idea here is to ensure the completeness of a device’s software update history. Therefore, some data entities still need to be persisted even though they got deleted by the user.
