### ISSUE TITLE
Hawkbit closes connection with file streaming failed after partial download

### ISSUE THREAD

**Issue by nealjack** [eclipse/hawkbit#1396]
I am trying to use hawkbit with constrained client devices (using Zephyr) that can download updates only at a very slow bitrate. My devices have been unable to complete the update reliably as the connection is closed by the server after what I am assuming to be a timeout of 5 minutes.

When the connection is closed I get the following warning in the hawkbit logs:
```
2023-07-14 18:56:33.292  WARN 1 --- [tp1562249660-20] org.eclipse.jetty.io.AbstractConnection  :

java.lang.NullPointerException: null
        at org.eclipse.jetty.io.AbstractConnection.lambda$failedCallback$0(AbstractConnection.java:92)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Unknown Source)

2023-07-14 18:56:33.302  WARN 1 --- [tp1562249660-22] o.e.h.r.e.ResponseExceptionHandler       : File streaming failed: fullfileRequest app_update.bin
```

I found [this](https://github.com/eclipse/hawkbit/blob/bcc2616e739e005daaf361f1f4334df28b1b94f6/hawkbit-ui/src/main/resources/hawkbit-ui-defaults.properties#L15) Spring Boot variable for the hawkbit UI configuration and tried extending it to 30 minutes in the spring configuration json in my docker-compose.yml:

```
environment:
      SPRING_APPLICATION_JSON: '{
          ...
          "server.servlet.session.timeout": "30m"
}'
```
However, it doesn't seem to have had an effect.

So a couple of questions:
1. Does the hawkbit artifact download have a timeout?
2. If so, how is this timeout configured?
3. If there is not a timeout, what are potential reasons that could be causing the null pointer exception and connection closure?

**Comment by strailov** [comment]
Hey @nealjack  
It seems that hawkBit cannot open a InputStream to your file, not sure why tho ... The IOException is handled and a FileStreamingFailedException is propagated. 
Regarding for the timeout - I don't think we have a timeout for download ... 
This property that you have found is session related - when should the session expire when a user logs in.

**Comment by nealjack** [comment]
It seems hawkbit is able to read the file just fine up until the file is 45% downloaded by the client, so I'm not sure what could have changed.

Is there a way to increase logging verbosity in the hawkbit docker image? Or could you point me to where in the code the file streaming is handled?

Thanks!

**Comment by strailov** [comment]
This he FileStreamingFailedException is handled in 
handleFileStreamingFailedException method in 
org.eclipse.hawkbit.rest.exception.ResponseExceptionHandler class

And the exception itself is thrown in FileStreamingUtil class... So maybe the IOException here could be of use.

**Comment by nealjack** [comment]
Okay, so I've been able to resolve this problem by completely tearing down the hawker docker container and deleting all external volumes for the set of containers. This isn't ideal, as all device security tokens are forgotten and any in the field will be unable to authenticate with the server.

I have been using the following docker-compose.yml, with some modifications to save the database state (`/var/lib/mysql`) and hawkbit artifacts (`/opt/hawkbit/artifactrepo`), so they aren't lost if the containers are terminated.

```
version: '3'

services:

  # ---------------------
  # RabbitMQ service
  # ---------------------
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"

  # ---------------------
  # MySQL service
  # ---------------------
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: "hawkbit"
      # MYSQL_USER: "root" is created by default in the container for mysql 5.7+
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    labels:
      NAME: "mysql"

  # ---------------------
  # HawkBit service
  # ---------------------
  hawkbit:
    image: "hawkbit/hawkbit-update-server:latest-mysql"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mariadb://mysql:3306/hawkbit",
          "spring.rabbitmq.host": "rabbitmq",
          "spring.rabbitmq.username": "guest",
          "spring.rabbitmq.password": "guest",
          "spring.datasource.username": "root",
          "hawkbit.server.im.users[0].username": "admin",
          "hawkbit.server.im.users[0].password": "{noop}password",
          "hawkbit.server.im.users[0].firstname": "Eclipse",
          "hawkbit.server.im.users[0].lastname": "HawkBit",
          "hawkbit.server.im.users[0].permissions": "ALL",
          "hawkbit.artifact.url.protocols.download-http.port": 80,
          "server.port": 80,
          "server.servlet.session.timeout": "30m"
        }'
    restart: always
    ports:
      - "80:80"
    volumes:
      - /opt/hawkbit/artifactrepo:/opt/hawkbit/artifactrepo
    labels:
      NAME: "hawkbit"
```

Without deep knowledge of hawkbit internals, I think the original issue stems likely stems from two possibilities:
1. The volumes I've set up in my docker-compose.yml do not encompass all the persistent state required for hawkbit artifact management, resulting in failures in reading artifact files. If so, what are all the paths that are required to preserve state across a `docker-compose down` and `docker-compose up`?
2. The process of testing, where I repeatedly deleted and replaced artifact binary files with the same name but different contents, led to some conflict in artifact management. If this is the problem, it should be easy to recreate by deleting and uploading new artifacts.

**Comment by nealjack** [comment]
I am able to recreate this issue with the following steps:

1. I start fresh, bringing any containers down, and deleting their state from the volumes mentioned in the compose script above.
2. `docker compose up -d`
3. I configure the hawkbit console to allow devices to authenticate with tokens, I issue the rest requests to make a new device, copy that token to my device, and ensure it is able to reach the hawkbit server.
5. I set up a new software module with a new upload, as well as a new distribution and new rollout to a device.
6. I observe a successful download by the device.
7. `docker compose down && docker compose up -d`
8. I log into the console and observer that my device is still in the database, and the old software module/distribution/rollout exist.
9. I redo step 5 but with new firmware, a new distribution, and a new rollout
10. hawkbit repeatedly throws the exception mentioned:
```
2023-07-17 20:56:40.426  WARN 1 --- [tp1573125303-17] org.eclipse.jetty.io.AbstractConnection  :

java.lang.NullPointerException: null
        at org.eclipse.jetty.io.AbstractConnection.lambda$failedCallback$0(AbstractConnection.java:92)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Unknown Source)

2023-07-17 20:56:40.427  WARN 1 --- [tp1573125303-18] o.e.h.r.e.ResponseExceptionHandler       : File streaming failed: fullfileRequest app_update.bin
```

So it seems pretty clear that the issue is bringing the containers down and up again.

How can I ensure that state is preserved if the hawkbit and database containers are brought down, while also avoiding this issue?

**Comment by nealjack** [comment]
I was able to resolve this issue by pulling a more recent commit (#b28e232) that uses tomcat instead of jetty, building the .jar myself, and building my own docker image.
