### ISSUE TITLE
Version control questions

### ISSUE THREAD

**Issue by lizziemac** [eclipse/hawkbit#1399]
Hi there, I'm looking into using hawkBit as my company's update server in tandem with swupdate.  Currently I've been messing around with a raspberry pi 4 and just the application updates.  There are a couple questions I still have unanswered:

1. Let's say you flash an image on the manufacturing line with a specific application/OS version combination that is a distribution in hawkbit.  How do you advertise that to hawkbit on the device joining the server via DDI? Is there a specific API for inform hawkbit of the device's current version, prior to any updates from the server?
2. On a related note, if an application update fails, the version is then blank in hawkbit. What is the recommended approach for ensuring that the version is never empty? Is there a way to configure a rollback update request from the device, or from the management UI? Is there a way to flag a device that doesn't have a version, so that we can understand it's in an unknown state?

Hawkbit seems pretty solid so far, was just hoping to tie up these few loose ends.

**Comment by avgustinmm** [comment]
Hi @lizziemac,
thanks for your interest in hawkBit.
Targets have installedDS and assignedDS distribution sets. I suppose what you are searching for is to set installedDS for your devices while you register them. Unfortunately, this is read only value in Management API and is not supposed to be set by northbound systems. However, it seems reasonable to add support for setting initial installedDS.
Regarding the second question - you mean that if you already have installedDS version it is cleared after failed update?

**Comment by lizziemac** [comment]
Hi @avgustinmm, thanks so much for getting back to me so quickly

1. Is there a recommended way to track versions outside of the assigned DS (for example do folks usually use the metadata for that?)
2. Yes, if I already had an assigned/installedDS that the server is aware of, and then attempt to update a device with a package that fails, the installedDS is no longer populated.  This is specifically for application updates, I haven't worked with OS updates yet.

**Comment by lizziemac** [comment]
It looks like there is a (new?) query parameter for assigning a distribution set called `offline` [link](https://eclipse.dev/hawkbit/rest-api/targets-api-guide.html#_request_query_parameter_4) that enables you to set it for factory defaults, manual updates, etc.

For example 
```bash
curl 'https://management-api.host.com/rest/v1/targets/137/assignedDS?offline=true' -i -X POST \
    -H 'Content-Type: application/json' \
    -d '{
  "id" : 3
 }'
```

**Comment by avgustinmm** [comment]
This method is pretty old. The offline parameter was added to implement https://github.com/eclipse/hawkbit/issues/242 issue. 
This covers a scenario that is little bit similar, for something that happen offline. But the version that is installed on device is actually installedDS which you could not change.

**Comment by real-tintin** [comment]
Hi @lizziemac,

Did you end up using the endpoint which you provided? We are in a similar situation and wonder what the best practices are for handling versions of newly manufactured devices.

I believe that it would be preferable to have a device endpoint, which it can use to report and set its own version.

**Comment by lizziemac** [comment]
@real-tintin Yes, I did end up using that endpoint, and it's working well. There's also a [bulk endpoint](https://eclipse.dev/hawkbit/rest-api/mgmt/index.html#tag/Distribution-Sets/operation/createAssignedTarget) if you need to use that instead.
