### ISSUE TITLE
How to view the logs produced by the ControllerPreAuthenticatedSecurityHeaderFilter.java Module

### ISSUE THREAD

**Issue by Yusufss4** [eclipse/hawkbit#1406]
Hello, 

In the given module, there are logs like given. 

`LOGGER.trace("Found commonNameHeader {}={}, using as credentials", caCommonNameHeader, commonNameValue);`

How can I see these log messages through the Docker Container Logs interface?

I have built the application via following the given steps, 

```
$ git clone https://github.com/eclipse/hawkbit.git
$ cd hawkbit/hawkbit-runtime/docker
$ docker-compose up -d
```
In the file named, `hawkbit-test-defaults.properties`, for the setting called `logging.level.root=TRACE`, I have made the log level to TRACE but still can't see the logs from the docker interface.

Currently I can only see the few of the logs that is related to only the start phase of the Hawkbit as it is included in the attachment. I want to see all of them. 

[current_log_messages.txt](https://github.com/eclipse/hawkbit/files/12240145/current_log_messages.txt)

The module I'm referring is here : [ControllerPreAuthenticatedSecurityHeaderFilter.java](https://github.com/eclipse/hawkbit/blob/master/hawkbit-security-integration/src/main/java/org/eclipse/hawkbit/security/ControllerPreAuthenticatedSecurityHeaderFilter.java)

I'm new to application development, so any help is greatly appreciated regarding this issue. 

Thanks!

**Comment by Yusufss4** [comment]
Thank you for your answer. 

I have added the given line at the end of the module,  

`log.level.org.eclipse.hawkbit=TRACE`

To the module named, 

`\hawkbit\hawkbit-runtime\hawkbit-update-server\src\main\resources\application.properties`

But when I restart the services from the Docker, I still cant see the log messages after service starts. 

![image](https://github.com/eclipse/hawkbit/assets/54643540/974a9671-405f-4154-9f9c-6a140e74ed6b)

Am I looking the wrong place to see the log messages?

**Comment by avgustinmm** [comment]
Sorry, 
the correct prefix is "logging.level.", just a typo. I'll modify my previous reply

**Comment by Yusufss4** [comment]
Thanks for the information. I closed the case.
