### ISSUE TITLE
The rollout startAt is always null

### ISSUE THREAD

**Issue by Delete-S** [eclipse/hawkbit#1416]
I create a rollout ,and set  the option start by hand .
I start it, but found the startAt cloumn in mysql is null .  
I find the code is 
```java
  @Override
    @Transactional
    @Retryable(include = {
            ConcurrencyFailureException.class }, maxAttempts = Constants.TX_RT_MAX, backoff = @Backoff(delay = Constants.TX_RT_DELAY))
    public Rollout start(final long rolloutId) {
        LOGGER.debug("startRollout called for rollout {}", rolloutId);

        final JpaRollout rollout = getRolloutAndThrowExceptionIfNotFound(rolloutId);
        RolloutHelper.checkIfRolloutCanStarted(rollout, rollout);
        rollout.setStatus(RolloutStatus.STARTING);
        rollout.setLastCheck(0);
        return rolloutRepository.save(rollout);
    }
``` 
how can I update the startAt column

**Comment by avgustinmm** [comment]
"startAt" is actually a marker saying when to start the rollout. 
* If you create auto-started (to start right now) or scheduled (to start at specific time) rollout then the startAt is set to the current or desired time (correspondently) 
* if you create manual (i.e. you'll start it later) rollout it is set to null
It is not designed as a property of the rollouts that could be used to check when the rollout has been started. Analogically, AFAIK, you don't have finish time or whatever.
It's not supposed to update it after the rollouts has been created.

**Comment by Delete-S** [comment]
thanks you answer.I've another question.
why startAt is null when I start rollout manual?
actual auto-started (to start right now) or scheduled (to start at specific time)  startAt cloumn  is not null.

**Comment by avgustinmm** [comment]
the scheduler check if there is set startAt time. if so and current time is >= it starts the rollout. 
when null - as for manual - it won't start rollout until you explicitly start it.
maybe it could be set to start time when you manually start the rollout but since start/end time of rollouts statistics is currently not covered by the hawkBit maybe it hasn't much sense
