### ISSUE TITLE
Api documentation is not show information

### ISSUE THREAD

**Issue by KonstantinBYvitebsk** [eclipse/hawkbit#1420]
For example: [DELETE /rest/v1/targets/{targetId}](https://eclipse.dev/hawkbit/rest-api/targets-api-guide.html#_delete_restv1targetstargetid)
![image](https://github.com/eclipse/hawkbit/assets/8515668/82b685b5-74d7-4bae-9891-0683c37d1543)

It is appeared here https://github.com/eclipse/hawkbit-website/commit/504e19d628b2b6288206725ff355e1860fa851c3#diff-2209c21e792021fb5f9bf859fd58fca64f7e2f8b8c2c9538085e4484568aba45

Actually the ad590ff03d8e8b4d7ab99bd9745a9b6c2ae7d0f1 commit is the last working for this section.

**Comment by strailov** [comment]
Hey @KonstantinBYvitebsk  ! 
Thanks for using hawkBit and this issue. 
I will check what is going on and come back to you.

**Comment by strailov** [comment]
Hey @KonstantinBYvitebsk  ! 
I have provided a fix [here](https://github.com/eclipse/hawkbit-website/commit/35930d81755cf78dc5851cdc31de0519d6a7cccf) . Seems like I generated the documentation wrong last time ... sorry for that. I hope now the side should be updated in a few minutes .

**Comment by KonstantinBYvitebsk** [comment]
Hi @strailov 
It cool you have fixed it. Now it shows the information properly.
BTW: I had to refresh it by ctrl+F5. It works for me.
Thank you.
