### ISSUE TITLE
 how to resync the rollout in local hawkbit server , so that if any new targets is present , so target will be added to that rollout

### ISSUE THREAD

**Issue by manojams** [eclipse/hawkbit#1529]
how to resync the rollout in local hawkbit server , so that if any new targets is present , so target will be added to that rollout

**Comment by avgustinmm** [comment]
It's not possible at the moment. There are discussions about having "dynamic" rollouts but at the moment such a feature is not implemented.
Once you create a rollout it remains static regarding the involved devices.
If you want to apply a distribution set also on the newly registered devices matching a filter you could create so-called "auto-assignment" feature. You could define a target filter and start auto-assignment for it.
See more at: https://eclipse.dev/hawkbit/ui/#target-filter-management -> "Auto assignments"

PS: as noted [here](https://eclipse.dev/hawkbit/community/#ask-a-question) please don't ask questions as issues but use StackOverflow
