### ISSUE TITLE
Managing/Signing Artifacts?

### ISSUE THREAD

**Issue by epac-tom** [eclipse/hawkbit#1534]
I've run up the hawkBit Docker image and been running some updates on a QEMU image built with Yocto, using RAUC for updates. All working well so far.

The piece of the puzzle I haven't quite got my head around is how/where the artifacts should be signed. As far as I see there's no functionality in hawkBit to sign updates, more I would need to sign the update and associate it to a specific target after I've signed it.

In that case, are there a common tools to manage the keys and creating the signed artifacts or is everyone rolling their own management solution?

I realise this isn't an issue with hawkBit but thought this must be a common problem that is solved by most/all hawkBit users, so any pointers are much appreciated.

**Comment by avgustinmm** [comment]
At the moment hawkBit is something like a framework for building production-grade solutions and doesn't cover all functionality needed in production. Encryption and signing files are not something that is in the scope. Moreover, in different cases, there will be different requirements. There is an edge device involved which implies various capabilities and languages. So, it seems to me, that signing and encryption are more like edge integration problem. 
If hawkBit starts to provide some kind of SDKs for device implementations (for instance for Java) then implementing a prototype sign and encript might be a good feature.

**Comment by epac-tom** [comment]
@avgustinmm thanks for your response. For my own clarification, this is what I originally had in mind, or something similar:

![image](https://github.com/eclipse/hawkbit/assets/63097910/67ca1e82-bd20-4e63-a148-ea6694979045)


From your description, are you suggesting it could/should look something more like this?

![image](https://github.com/eclipse/hawkbit/assets/63097910/0107d960-88dc-4b1a-b3f4-f94cf5664bf8)

**Comment by avgustinmm** [comment]
My point was more about who should implement signing/verification. And that, it seems to me, should be the end device integrator. Where the backed (signature) logic should reside - in your architecture I'm not sure.
Especially in the sign case (it could be different for encrypt) I suppose that your signed artifacts will be the same for all devices - so you don't have to have different signed artifacts for device1 and device2. 
So, in my opinion, the best would be something like the approach depicted in your first diagram:
1. raw artifact is created
2. using PKI single signed image is created (by custom integration logic)
3. it is imported into hawkBit artifact repository (no PKI - hawkbit integration) - the signature is transparent for the hawkBit
4. this image is downloaded and verified by the device(by custom integration logic)

**Comment by epac-tom** [comment]
Thank you both, that has help tremendously. I now have a much better idea of the how and where.

To your point @vigier, I think I need to take a step back and rather than looking at it like, we must sign everything differently, I need to look at what we're trying to achieve. Do we want to make sure our software only goes onto our devices, do we want to make sure only our software goes onto our devices, etc, once that's nailed down we can then look at the how.

Thanks again.
