### ISSUE TITLE
Software Module & Distribution Set lock / immutable

### ISSUE THREAD

**Issue by avgustinmm** [eclipse/hawkbit#1580]
At the moment there exists a kind of implicit locking of distribution sets. For instance, you cannot add/remove a software module from a distribution set if it is assigned. I am not sure if the assignment check is even 100% correct - it checks actions - but you may have it installed on target but have deleted the action. Or it may have been replaced on all targets and not in use anymore.
Nothing, however, prevents you from modifying artifacts of software modules which, e.g. if part of rollouts, could lead to very instance results - e.g. half targets get 2 artifacts and the rest 4.  
IMO it is good to think of SW and DS as something pretty static/immutable. Once ready and prepared they must never be changed.
So, I think about locking:
1. You create empty DS/SW (i.e. no SW/artifacts respectively) 
2. you prepare them - add SW/artifacts
3. then they are locked - can't be modified anymore (at least some part of them as SW/artifacts)
4. only after they are locked - they could be assigned to targets, or - the assignment will directly lock them - thus nothing will be required by the current integrations (with the exception that modifications won't be possible after - but none shall do that anyway)
5. they could never be unlocked anymore (is there a case we want to do that, any opinions)?
This will make things much cleaner and predicted.
We could also add an atomic DS/SW create option in APIs - i.e. create DS/SW with set of SWs/artifacts and become directly locked. At further API versions where we could break compatibility, I would even drop the possibility to create "unlocked" DS/SW".

Any opinions on this?

**Comment by vigier** [comment]
Looks good :-)

**Comment by avgustinmm** [comment]
I'm starting work on a PR for this feature. The feature will be implemented as follows:
1. add _locked_ field to both Software Module and Distribution Set (initially _false_)
2. API for _lock_ (set _locked_ to true) - no option for _unlock_
3. _lock_ for DS will check if the target DS is _complete_ 
4. A _locked_ SM or DS could not be _functionally_ changed - e.g. to add/remove artifacts/software modules
5. add _implicity lock_ - i.e. :
    * when a distribution set is being locked all its software modules are implicitly locked (if not locked already)
    * when a distribution set is being assigned it is implicitly locked (if not locked already) - including its software modules (according to the previous implicit lock)

**Comment by vigier** [comment]
Just a point which comes into my mind with this implicit lock on assignment:

In case that you do have some kind of "release workflow" which includes the installation on some test-devices it might be not desirable to lock the DS, as then you need to recreate it in case something must be fixed. Still - it would not be possible to re-use the version number given to the previous DS or SW Modules.

Ideas:
* Don't lock on assignment / or provide an option to avoid it ("test-assignment")
* Have an unlock option
* Make "locked" to a state (incomplete <-> complete <-> test --> released) In test modifications are not possible - but assignments, after switching it to released a move back is not possible. Usage of an complete-DS moves it onto test-state. Maybe the usage in campaigns and autoassigments is only possible for released DS...  (too complicated?)
* 
any other ideas?

**Comment by avgustinmm** [comment]
What about introducing special behavior for some tags (e.g. TEST) for DS that will allow you to bypass implicit lock?
i.e. while you are testing you tag your DS with TEST. Then you test it without locking. Once you are ready, you remove TEST tag and then lock it explicitly or implicitly by creating a rollouts / auto assignment with it. 
What do you think?

**Comment by vigier** [comment]
Feels like using a tag for something where he is not meant for... ;-) What do you think about an option not-to-lock on assignment (Like a checkbox in the confirmation dialog/UI) indicating "I know what I am doing"?

**Comment by avgustinmm** [comment]
Tags are generally used for search. But they also have semantics. So, why not, based on semantics have some differences in the treatment? This will allow you not only to have a "test" distribution set concept applied but also having an option to search easily. 
Also, such approach is extensible and would allow you to provide, as meta information, other concepts - like `required migration step` which currently overbird entities with flags, API with methods, and after all are not very likely to use.

I agree having "not-to-lock" option is also something we could do.  However, if we go for it it shall be "lock by default" in order to propagate the safety approach. And the drawback of this approach would be again pollution, at least of the API, with some "flags" - which could be well hidden with the declarative / contract -based tag approach.

**Comment by avgustinmm** [comment]
The feature is implemented without the open question of how to support user-friendly test mode, which is a relatively decoupled feature (having that anyway user could do testing by following 1.0.RC1 -> test -> 1.0.RC2 -> test -> 1.0 approach).
So, I've created an additional issue for this - [Distribution Set implicit lock: Support testing mode](https://github.com/eclipse/hawkbit/issues/1651) - which aims to handle discussions and collect ideas about that feature, and eventually be implemented.
