### ISSUE TITLE
Management API to access the externalRef property of deployment actions

### ISSUE THREAD

**Issue by stefbehl** [eclipse/hawkbit#1650]
Currently the ["externalRef"](https://github.com/eclipse/hawkbit/blob/master/hawkbit-repository/hawkbit-repository-api/src/main/java/org/eclipse/hawkbit/repository/model/Action.java#L132) property of deployment actions is not exposed via the Management API of Eclipse hawkBit.

Since `externalRef ` is a useful concept to correlate actions with other entities (for example in integration scenarios), it would be great, if the property is exposed as part of the JSON-based API representation of actions. The following Management API endpoints are affected:
- HTTP GET /rest/v1/actions
- HTTP GET /rest/v1/actions/:action-id
- HTTP GET /rest/v1/targets/:target-id/actions

Furthermore, it would be great if the "/rest/v1/actions" resource collection allows to filter actions based on their externalRef property:
- HTTP GET /rest/v1/actions?q=externalref==myRef

Feedback is appreciated. Thanks a lot for your support!

**Comment by avgustinmm** [comment]
@stefbehl, thanks for the observation and the feature request.

It seems to me pretty reasonable. Since the Management REST API is the only external Northbound interface it shall provide access to all action attributes including externalrefs.
