### ISSUE TITLE
Management API documentation broken

### ISSUE THREAD

**Issue by ajechort14** [eclipse/hawkbit#1699]
WHen trying to reference the Management API docs, a 404 appears
<img width="1218" alt="Screenshot 2024-03-29 at 11 05 11 AM" src="https://github.com/eclipse/hawkbit/assets/47900785/08558b88-6f97-4d3b-a20d-6f67cb3d6b00">

**Comment by strailov** [comment]
Hey @ajechort14 ! 
Thanks for your interest in hawkBit. 
I found the problem, find it and now the documentation should be okay.
