### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by k-gostev** [eclipse/hawkbit#1701]
Currently the `eclipse.dev/hawkbit` website is looking like this for some reason:

![Screenshot 2024-04-09 at 10 26 10](https://github.com/eclipse/hawkbit/assets/115063155/ffaa33fe-1348-4b6c-924e-e4aafbee89d0)

**Comment by strailov** [comment]
Hey @k-gostev ! 
Thanks for your interest in hawkbit ! 
I was playing with the website and I must have misgenerated some content ... 
Now seems to be okay. Can you try ? 
But pleases reset your browser cache before that (or try in private session) .
