### ISSUE TITLE
Question: Force updating to the same image twice on device

### ISSUE THREAD

**Issue by lizziemac** [eclipse/hawkbit#1703]
Hi there!

I have a device that has an A/B partitioning schema.  Currently, if both partitions need a mandatory update, for example, if partition A is updated to 0.0.1, then partition B cannot be updated because the device is already updated. Is there a way to force the update twice in a row? As far as I know, hawkBit doesn't know what partition the device is running on.  The only workaround I can think of is somehow reporting the device twice to hawkBit, once for each partition, but that isn't ideal and could lead to longer-term issues.

Thanks!
Liz

**Comment by strailov** [comment]
Hey @lizziemac ! 
Thanks for your interest in hawkBit! 
Unfortunately hawkBit does not know anything about device partitions ... 
One thing I could think of is to play with the versions of the Distribution Sets e.g. 0.0.1_A 0.0.1_B and based on that the device implementation to handle it ... but yeah ... not sure if this is possible in your case.

**Comment by lizziemac** [comment]
Great point! I think that might work for my use case. Thanks!

Plan of attack:
- Create a Distribution Set for each partition with the same Software Module(s). I'll use colons to keep consistency with the hawkBit Action history UI of `<distribution set name>:<version>` (e.g. `Release:0.0.0` -> `Release:0.0.1:A`
  - 0.0.1:A (required migration step ✅ )
  - 0.0.1:B (required migration step ✅ )
- Deploy both to the device at the same time. Since they are both required migration steps, neither should be canceled by the other.
