### ISSUE TITLE
Can't access Management UI

### ISSUE THREAD

**Issue by xaqbr** [eclipse/hawkbit#1746]
I'm unable to access any part of the web dashboard from both the public sandbox and local Docker setups of hawkbit. I thought going to the root URL would show me a login screen or something, but instead I'm presented with a Swagger REST dashboard:

<img width="1540" alt="Screenshot 2024-06-10 at 4 14 47 PM" src="https://github.com/eclipse/hawkbit/assets/3822492/4b96fe7f-92ee-4467-93eb-781ce941f547">

I thought maybe accessing /UI or some other URL would lead me to it but I just get a 404 error each time:

<img width="582" alt="Screenshot 2024-06-10 at 4 15 45 PM" src="https://github.com/eclipse/hawkbit/assets/3822492/3de9c471-6f26-4b2e-a1db-a98110a894c4">

This happens for me on https://hawkbit.eclipseprojects.io/ as well. Have the URLs for accessing the management UI changed somewhere?

**Comment by strailov** [comment]
Hello @xaqbr ! 

The vaadin 8 hawkBit UI was shut down ... Currently If you need UI urgently you can use the Simple UI which was added for demo purposes, or use Swagger.
Please check  [this](https://github.com/eclipse/hawkbit/issues/1510) and [this](https://github.com/eclipse/hawkbit/issues/1376)
