### ISSUE TITLE
can it work without websocket, any impact?

### ISSUE THREAD

**Issue by lengkristy** [eclipse/hawkbit#1797]
version: 0.2.0-SNAPSHOT

springboot version: 1.4.7.RELEASE

I use zuul 1.x gateway proxy hawkbit, but zuul 1.x gateway can't support websocket. Because the path "/UI/PUSH?v-uiId=4&v-csrfToken=28023825-ce9e-49be-90ea-1b56a46ddff7&X-Atmosphere-tracking-id=" use websocket, if use zuul gateway, it will change http.

the payload without zuul :

wss://xxxxxx/UI/PUSH?v-uiId=4

```
v-uiId: 6
v-csrfToken: cc867826-082b-4b2b-b671-c555c94d145b
X-Atmosphere-tracking-id: d277b07a-8e44-472e-b7a2-0b7a8e77b73c
X-Atmosphere-Framework: 2.2.13.vaadin5-javascript
X-Atmosphere-Transport: long-polling
X-Atmosphere-TrackMessageSize: true
Content-Type: application%2Fjson%3B%20charset%3DUTF-8
X-atmo-protocol: true
_: 1722505768012
```

the payload with zuul gateway proxy:
http://xxxx/UI/PUSH?v-uiId=6&v-cs

```
v-uiId: 6
v-csrfToken: cc867826-082b-4b2b-b671-c555c94d145b
X-Atmosphere-tracking-id: d277b07a-8e44-472e-b7a2-0b7a8e77b73c
X-Atmosphere-Framework: 2.2.13.vaadin5-javascript
X-Atmosphere-Transport: long-polling
X-Atmosphere-TrackMessageSize: true
Content-Type: application%2Fjson%3B%20charset%3DUTF-8
X-atmo-protocol: true
_: 1722505768012
```

What impact does it have?

can i do this?

**Comment by avgustinmm** [comment]
hawkbit 0.2.0 is too old release
UI is not supported anymore from hawkBit
