### ISSUE TITLE
Duplication in URL returned when using certain clients requesting updates

### ISSUE THREAD

**Issue by Silvanoc** [eclipse/hawkbit#180]
I'm sorry, this issue is weird, but we are suffering it...

Depending on the client using to request the Hawkbit REST-API for updates for a device we are getting URLs with "duplicated parts". For example:

> http://localhost:8080/default/controller/v1/IntegrationTestTargetID/**default/controller/v1/IntegrationTestTargetID/**configData

removing the duplicated part

> http://localhost:8080/default/controller/v1/IntegrationTestTargetID/~~default/controller/v1/IntegrationTestTargetID/~~configData

remains the right URL

> http://localhost:8080/default/controller/v1/IntegrationTestTargetID/configData

We found the issue when using Python "requests" module and the command line tools curl and wget.

For reproducibility, as answer to this wget request:
`wget -S -q --header "Accept: application/json" -O - 'http://localhost:8080//default/controller/v1/IntegrationTestTargetID/'`

we get this

```
  HTTP/1.1 200 OK
  Server: Apache-Coyote/1.1
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  ETag: "0a93b87de3a6db0a5f6078450569c953f"
  Content-Type: application/json;charset=UTF-8
  Content-Length: 203
  Date: Tue, 17 May 2016 09:55:12 GMT
{"config":{"polling":{"sleep":"00:05:00"}},"_links":{"configData":{"href":"http://localhost:8080/default/controller/v1/IntegrationTestTargetID/default/controller/v1/IntegrationTestTargetID/configData"}}}
```

See the duplication?

**Comment by michahirsch** [comment]
Hi @Silvanoc 

I can verify this behavior as you explained. This duplicate path comes from the double slashes you are having in your URL. 

If you are using a single slash after the port it will return the correct result:

>
wget -S -q --header "Accept: application/json" -O - 'http://localhost:8080/default/controller/v1/IntegrationTestTargetID/'

```
  HTTP/1.1 200 OK
  Server: Apache-Coyote/1.1
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  X-XSS-Protection: 1; mode=block
  ETag: "0448a8dc4b6eecdb8c5de32b031bed1a4"
  Content-Type: application/json;charset=UTF-8
  Content-Length: 157
  Date: Tue, 17 May 2016 12:17:01 GMT
  Proxy-Connection: keep-alive
  Connection: keep-alive
{"config":{"polling":{"sleep":"00:05:00"}},"_links":{"configData":{"href":"http://localhost:8080/default/controller/v1/IntegrationTestTargetID/configData"}}}
```

**Comment by Silvanoc** [comment]
You're right! Thank you!

The Python script generating the URL for the requests probably generated the duplicated slash and we copied it when testing with curl and wget.

Although using double slashes is not allowed by the corresponding RFC specification, most web-services have no issue at all handling it. Therefore I wouldn't consider it a bug, but an unexpected behavior.

I don't know if it's an issue that can be easily fixed within Hawkbit or if it's a Tomcat issue and therefore out of scope.

**Comment by michahirsch** [comment]
I totally agree with you. I'm also not considering as a bug but it would be nicer if the double slash would be ignored in this case. I'm guessing this is a spring-framework behavior, because spring-framework is rendering this URL based on the request information and base-path information. 

I'll have a look into it if this can be easily fixed, thanks for reporting.
