### ISSUE TITLE
[Enhancement] check offered download URL works

### ISSUE THREAD

**Issue by Silvanoc** [eclipse/hawkbit#182]
It would be nice if Hawkbit could check if artifacts uploaded via Hawkbit are reachable via the offered URL before offering the download to the devices.

We missconfigured Hawkbit to offer both HTTP and HTTPS downloads, although only HTTP is being supported. The devices try first to use HTTPS, but since only HTTP is supported, they fail. We are adding some checks on the device software to be more robust against these kind of missconfigurations. But it would make the whole system more robust if Hawkbit could check it too.

**Comment by kaizimmerm** [comment]
I don't think that this functionality should go into hawkBit as there is nothing the server could do about it. Lets assume the server finds out that the configured download URL is unreachable. Should is refuse to send the update to the client? I guess it would take users forever to figure out while the update has not been shipped. I guess a simple monitoring on the artefact hosting service should be sufficient
