### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by Walking-Walker** [eclipse/hawkbit#1822]
I followed the step B: Run hawkBit Update Server (Monolith) with services as Docker compose.

After running hawkBit update server as described in step B.
I saw hawkBit/hawkbit-update-server, rabbitmq:3-management, mysql:8.0 were running.

When I tried to login using the url http://localhost:8080/ui, I saw the message like below.

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

If I use URL http://localhost:8080/ then it is redirect to http://localhost:8080/swagger-ui/index.html?attribute=redirectWithRedirectView.
And hawkBit REST APIs page was displayed.

If someone can find what I did wrong, please let me know.

**Comment by strailov** [comment]
Hello @Walking-Walker ! 
Thanks for using hawkBit.

You did nothing wrong. Please check [this issue](https://github.com/eclipse/hawkbit/issues/1376) . 

The legacy Vaadin UI was removed from hawkbit... Instead for now you could use our Swagger Endpoint which I believe you already found it, and our Simple UI which is really basic (You can find it under hawkbit/hawkbit-simple-ui in DockerHub)
