### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by ddewaele** [eclipse/hawkbit#187]
While playing around with Hawkbit I noticed a lot of session timeouts even after a couple of minutes, forcing me to login again very frequently.

**Comment by michahirsch** [comment]
That's weird, because hawkBit is using a websocket connection to keep the session alive. Which browser did you use?

**Comment by ddewaele** [comment]
Was using chrome .... happened a number of times yesterday. Sometimes less than 5 minutes after logging in I got the UI banner indicating that no data could be retrieved and I needed to login again. 

Will keep an eye out for it and see if I can reproduce it.

**Comment by mkwatson** [comment]
I can reproduce it. It's happening when I run the sample device (using http polling) on the same host.

**Comment by mkwatson** [comment]
Can we re-open this?
