### ISSUE TITLE
[Enhancement] Error msg when assignment of module to distribution set fails

### ISSUE THREAD

**Issue by ddewaele** [eclipse/hawkbit#188]
From gitter : 

_When you are creating a distribution set type you need to specify which software module types are allowed to include in this type and this will be validated when you try to assign software modules against a specific instance of a distribution set based on its type_

I noticed that sometimes when assign software modules that aren't compatible with the distribution set you either get
- a generic error message saying : X SW Module Type cannot assign to Distribution Y
- UnsupportedModuleExceptionForThisDistributionSet

I missed the part on software distribution set types (I assumed they were just simple tags to filter distribution sets). 

Perhaps error msg can be more clearer : 
- module type X not supported by distribution set type, only Y,Z,... allowed
- check your distribution set type

**Comment by kaizimmerm** [comment]
Fixed in #540
