### ISSUE TITLE
DDI API defines custom string time in body which is not specified

### ISSUE THREAD

**Issue by michahirsch** [eclipse/hawkbit#191]
The DDI-API uses a `time` field in the feedback channel which is intend for clients to write the time of message creation in it. [DDI-API](https://github.com/eclipse/hawkbit/wiki/Direct-Device-Integration-API)

Example

```
{
    "id": 1,
    "time": "20140511T121314",
    "status": {
        "execution": "closed",
        "result": {
            "finished": "success",
            "progress": {}
        }
    }
}
```

Unfortunately this `time` field is not really documented in which format the time is. Furthermore it might make sense to use a standard ISO time format like ISO 8601 standard for JSON dates.

**Comment by singh-himanshu** [comment]
I guess from time to time contributors may want to submit documentation changes. Is the documentation source shared on GitHub already? If not what is the suggested mechanism to submit the documentation changes?

**Comment by gdesmott** [comment]
This ticket has been closed but I did not find any documentation of the expected time format.
Did I miss anything?

**Comment by schabdo** [comment]
You don't missed anything. Back in the days `time` field was specified in API but never implemented/evaluated by hawkBit (cf. [Gitter](https://gitter.im/eclipse/hawkbit?at=5c8b88fdf6999130a00bd751)). So we removed the field from documentation in order to avoid confusion. However it will still be accepted by hawkBit

**Comment by gdesmott** [comment]
Thanks for the clarification. Shouldn't it be removed from https://www.eclipse.org/hawkbit/apis/ddi_api/ as well then?

**Comment by schabdo** [comment]
True, good catch! Removed. Docs will be updated with next milestone.
