### ISSUE TITLE
When hitting a (valid) URL while not logged in, user is redirected to login page over http

### ISSUE THREAD

**Issue by kartben** [eclipse/hawkbit#192]
When hitting a (valid) URL while not logged in, user is redirected to login page over http, even if the original request has been done over HTTPS. It does not seem to be a problem on bluemix, but e.g on Predix, the unsecured http access is simply not enabled, so the redirect would need to use the same protocol to prevent this defect.

**Comment by michahirsch** [comment]
Yes same on bluemix sandbox, the login gets re-directed to `http`. Shouldn't be, you can enforce SSL by using the property `security.require-ssl=true` but when accessing hawkBit with `https` the login re-direct should keep `https`

**Comment by kaizimmerm** [comment]
I adapted this for the [sandbox](https://github.com/eclipse/hawkbit/blob/master/examples/hawkbit-example-app/src/main/resources/application-cloudsandbox.properties) That should do the trick on predict as well.
