### ISSUE TITLE
Allow setting controller attributes via DMF API

### ISSUE THREAD

**Issue by michahirsch** [eclipse/hawkbit#214]
Currently the controller attributes can only be provided via the DDI-API by putting the data via HTTP after a controller registration as documented [DDI-API configData](https://github.com/eclipse/hawkbit/wiki/Direct-Device-Integration-API).

The DMF-API should also be able to allow putting controller attributes via the API, e.g. using the AMQP-Headers to allow putting attributes at `THING_CREATED` event.

**Comment by kaizimmerm** [comment]
This fixed and in the M3 milestone
