### ISSUE TITLE
Download and deferred installation in a maintenance window

### ISSUE THREAD

**Issue by stormc** [eclipse/hawkbit#245]
Currently, hawkBit's mode is download+install/activate, i.e., as soon as a distributionset is assigned to a target, the target device gets to know about the available update upon its next poll operation, subsequently downloading, installing, and activating the update.
Although one can orchestrate the start time of announcing updates via, e.g., rollout management, it would be nice to have, e.g., connectivity-constrained devices to download the update artifact beforehand and then to install the downloaded artifact once the defined maintenance window is reached.

This may be achieved by splitting download and installation/activation into two steps, thereby putting the burden of keeping track of the maintenance window upon hawkBit. As a result -- although not strictly required as the artifact should have been downloaded by then -- devices need to be online in order to receive the install/activate order from hawkBit. Furthermore, this would be a (major) API change.
As an alternative, the maintenance window may be communicated to the device which downloads the artifact but defers installation/activation until the maintenance window is reached. This would require to extend the feedback options in hawkBit to reflect the "downloaded but waiting for maintenance window" state. If no maintenance window is specified, the current behavior is maintained.

**Comment by kaizimmerm** [comment]
I wrote my thoughts together how this could be done: https://github.com/eclipse/hawkbit/wiki/Concept---Separation-of-Download-and-Install

I really like the idea and we could use that feature over here as well.

**Comment by StBurcher** [comment]
How is creating the Action Downloaded? 
I think the device is sending that change via deploymentBaseActionFeedback, but than we have to extend ExecutionStatus with downloaded.

**Comment by StBurcher** [comment]
I was wondering. Is there a possibility to set update to ski at the moment?

>   "deployment" : {
>     "download" : "forced",
>     "update" : "skip",

Using the management REST interface with SOFT or FORCE result in 

>   "deployment" : {
>     "download" : "forced",
>     "update" : "force",

or

>   "deployment" : {
>     "download" : "attempt",
>     "update" : "attempt",

In order to allow later download, we should introduce a new MangementUpdateType.

**Comment by kaizimmerm** [comment]
No its actually not possible as of now. The wiki link above leads to a document where I explained my thoughts on this.

**Comment by singh-himanshu** [comment]
Our current thought is not to add additional UpdateType to Action, but do a check if update is due based on the start and end time for the action.

If its due, change the ETAG in response for getControllerRoot and for getControllerBasedeploymentAction, respond with:
"download" : "forced",
"update" : "forced",

Start and End time is also sent as part of the response, if present. This is to enable controller to poll before start to check if there is any change to the action.

For change in action status from DOWNLOADED to RUNNING, rely on the action feedback from controller.
