### ISSUE TITLE
sandbox broken?

### ISSUE THREAD

**Issue by jkaa** [eclipse/hawkbit#307]
Hi,

it seems the hawkbit sandbox is currently not working.

- login to management console fails
- REST interface error:
<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Oct 04 13:32:34 UTC 2016</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>Tenant DEFAULT does not exists, cannot create entity class org.eclipse.hawkbit.repository.jpa.model.JpaSoftwareModuleType with id null</div></body></html>

Can you confirm/fix it please?

Cheers,
Johannes

**Comment by michahirsch** [comment]
Yes, is working again.

**Comment by jkaa** [comment]
No data present in sandbox anymore / on purpose?

**Comment by jkaa** [comment]
Great! :+1:
