### ISSUE TITLE
Unable to run hawkBit Example Application

### ISSUE THREAD

**Issue by ringgelerch** [eclipse/hawkbit#319]
Actually I'm trying to run the example application to evaluate hawkbit with no success.

It seems that the hawkbit UI is not compatible with the hawkbit update server anymore. 

After installing everything the web ui comes up and I can login successfully. When the next screen is shown the following error message pops up:

"Communication Problem Take note of any unsaved data, and click here or press ESC to continue.     Invalid JSON from Server."

I tried it with the latest master (commit e1557b257d0ed72d965646ece72caead7dd029fa) and the 0.2.0M2 tag with the same result.

**Comment by kaizimmerm** [comment]
That is strange. I have never seen that behaviour. I guess this happens when the UI upgrades to Websocket.

**Comment by ringgelerch** [comment]
Thank you for the fast response!

In the meantime I've done some more tests with an easy setup on one machine with direct access over localhost and everything is fine.

My previous try was on a GUI-less machine with a redirection via a reverse proxy. I guess the cause of the problem is located in this area.

Is there an easy way with the example app to make the UI available via an external interface (not localhost) as well?

**Comment by kaizimmerm** [comment]
Well, I don't know your reverse proxy but I guess it is not supporting upgrades to web socket.

InNginx for instance would look like this:

```
location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
```
