### ISSUE TITLE
[RFC] : Binary delta

### ISSUE THREAD

**Issue by sbabic** [eclipse/hawkbit#331]
Hi everybody,

not a real issue, but I want to ask if thie approach with binary deltas was already investigated (or maybe solved ?). I have SWUpdate as updater agent working together with the Hawkbit server and it works as full image updater.
There are some discussions on SWUpdate's ML how to provide binary deltas, that can reduce download time and size, but at the end without dropping the full image concept: at the end, the whole image is still installed.
At the end, there were some concepts to do this, but a possible way requires much more interaction with the backend server. In fact, a delta can grow in size and becoming very large if target is not running the last release. But on the basis of the running version on the target, the backend could compute on the fly the delta. Something like:
- target sends version of running software, maybe with configData API
- Hawkbit checks the version and compute the binary delta
  If the size is bigger as in case of the full image, the full image is provide
- Hawkbit makes the new computed image available as usual, and target can start to downloadi it when polling cycle expires.
  Of course, this means a specialized image pro device (or per group of devices of the same type and running the same version).

Is there already some thought in this direction or maybe is it implemented in Hawkbit in some other ways ?

Thanks,
Stefano

**Comment by kaizimmerm** [comment]
Hi Stefano,

the strategy so far has been that binary deltas are pre-genrated and uploaded into hawkBit as part of the same software module, e.g. a software module contains a file full.tar and delta-12345-to-5678.tar (s) The client than knows which delta it needs and downloads the fitting file accordingly. This is hinted [here](https://docs.bosch-iot-rollouts.com/slides/introduction.html#/10). It no fitting delta file exists it falls back to full.

It was always our principle that hawkBit should have nothing to do with artefact generation as every device (manufacturer/category) has different mechanisms there.

However, another idea has been (though never implemented) that a when a client requests a file from hawkBit that does not exist there, hawkBit forwards this request to a 3rd party system which is able to generate artefacts accordingly, e.g. the request download/delta-forDeviceXXXType-12345-to-5678.tar is forwarded to the third party system which recognises the file name pattern and generates accordingly. The important part of course is the hook here. The choice is course up to the hawkBit based implementation if the generation is done inside hawkBit's runtime or by a remote service.

The advantage of the two mechanisms where device and delta generation service exchange the delta  request information through the filename is that we do not need a protocol extension for hawkBit and device to figure out which file might fit to which delta request.

Kai

**Comment by sbabic** [comment]
Hi Kai,

On 03/11/2016 06:26, Kai Zimmermann wrote:
> Hi Stefano,
> 
> the strategy so far has been that binary deltas are pre-genrated and
> uploaded into hawkBit as part of the same software module, e.g. a
> software module contains a file full.tar and delta-12345-to-5678.tar (s)

ok, understood.

> The client than knows which delta it needs and downloads the fitting
> file accordingly. This is hinted here
> <https://docs.bosch-iot-rollouts.com/slides/introduction.html#/10>. It
> no fitting delta file exists it falls back to full.
> 
> It was always our principle that hawkBit should have nothing to do with
> artefact generation as every device (manufacturer/category) has
> different mechanisms there.

Fully agree - build system and deployment system are separate.

> However, another idea has been (though never implemented) that a when a
> client requests a file from hawkBit that does not exist there, hawkBit
> forwards this request to a 3rd party system which is able to generate
> artefacts accordingly, e.g. the request
> download/delta-forDeviceXXXType-12345-to-5678.tar is forwarded to the
> third party system which recognises the file name pattern and generates
> accordingly. The important part of course is the hook here. The choice
> is course up to the hawkBit based implementation if the generation is
> done inside hawkBit's runtime or by a remote service.
> 
> The advantage of the two mechanisms where device and delta generation
> service exchange the delta request information through the filename is
> that we do not need a protocol extension for hawkBit and device to
> figure out which file might fit to which delta request.

Thanks for clarification !

Regards,
Stefano


-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by kaizimmerm** [comment]
You are welcome 😄 Let us know if you have a need for the second mechanism. It is on my mind for quite some time but in reality no customer seems to need it.

**Comment by ghost** [comment]
@sbabic rauc handles delta updates via [adaptive updates](https://rauc.readthedocs.io/en/latest/advanced.html#adaptive-updates) via [http(s) streaming](https://rauc.readthedocs.io/en/latest/advanced.html#http-streaming) to save [bandwidth](https://pengutronix.de/de/blog/2022-10-12-rauc-adaptive-updates.html) nowadays. There is nothing on the hawkbit server side to consider, correct?
