### ISSUE TITLE
Wrong Maven parent for Maven "extensions" modules

### ISSUE THREAD

**Issue by kartben** [eclipse/hawkbit#347]
As the extensions modules specify hawkbit-parent as their parent POM, this fail when building hawkbit on a system that does not have it yet.

**Comment by michahirsch** [comment]
yeah that's true, there is a pull-request: https://github.com/eclipse/hawkbit/pull/348 which should fix that problem by correcting the parent.

**Comment by kartben** [comment]
oops, i should have mentioned I was going to send a PR

**Comment by kartben** [comment]
I should say, a better PR, even ;-)

**Comment by michahirsch** [comment]
That's true :+1:  awesome !
