### ISSUE TITLE
Cannot run the hawkbit-example-app

### ISSUE THREAD

**Issue by faif** [eclipse/hawkbit#371]
Not sure what the system/software requirements are, but after doing `mvn clean install` trying to execute the example app fails.

Maven version: Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Java version: Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
System: macOS sierra 10.12.1

Command: `java -jar ./examples/hawkbit-example-app/target/hawkbit-example-app-0.2.0-SNAPSHOT.jar`

Main stack trace error
`Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat servlet container`

**Comment by faif** [comment]
Just noticed that I was running another service at port 8080, so stopping it helped. Now the application boots fine, but I see connection errors:

`org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:62)`

Can this be firewall-related?

**Comment by kaizimmerm** [comment]
This is rhe DMF connector. You can disable it with the property hawkbit.dmf.rabbitmq.enabled=false . Or ignore it, its no harm.

**Comment by faif** [comment]
That helps, thanks.
