### ISSUE TITLE
Management API returns error

### ISSUE THREAD

**Issue by faif** [eclipse/hawkbit#372]
Connecting at https://hawkbit.eu-gb.mybluemix.net/rest/v1/targets and providing admin:admin as auth returns the following error:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Dec 01 09:25:12 UTC 2016
There was an unexpected error (type=Internal Server Error, status=500).
Tenant DEFAULT does not exists, cannot create entity class org.eclipse.hawkbit.repository.jpa.model.JpaSoftwareModuleType with id null

Similar error when using the DDD API:

`{"exceptionClass":"org.eclipse.hawkbit.repository.exception.TenantNotExistException","errorCode":"hawkbit.server.error.repo.tenantNotExists","message":"Tenant DEFAULT does not exists, cannot create entity class org.eclipse.hawkbit.repository.jpa.model.JpaTarget with id null"}`

**Comment by michahirsch** [comment]
I've restarted the demo-service and now you should be able to login as well to use the rest-api. The demo data will be re-generated soon. Thanks for the information that with the demo-server is something wrong.

**Comment by kaizimmerm** [comment]
Demo data is re-generated.
