### ISSUE TITLE
DDI API: Ability to get informed about update execution status

### ISSUE THREAD

**Issue by stormc** [eclipse/hawkbit#381]
Currently, a device is only able to send its update execution status but is not able to query it from hawkBit. 
Such a functionality may prove useful, for example, when the client software running on the device loses this information prior to reporting a final execution status such as `closed` to hawkBit. This may happen, e.g., due to a power cycle or simply a crash. Upon the client software restarting, it installs the same payload again as advertised by hawkBit (as the device has not sent a final update execution status). Instead, if the last feedback sent to hawkBit would be reported back to the device, the client may resume installation.

For the implementation, the DDI API response to a [`GET /{tenant}/controller/v1/{targetid}/deploymentBase/{actionId}`](https://docs.bosch-iot-rollouts.com/documentation/rest-api/rootcontroller-api-guide.html#_get_tenant_controller_v1_targetid_deploymentbase_actionid) could include the previously sent feedback via [`POST /{tenant}/controller/v1/{targetid}/deploymentBase/{actionId}/feedback`](https://docs.bosch-iot-rollouts.com/documentation/rest-api/rootcontroller-api-guide.html#_post_tenant_controller_v1_targetid_deploymentbase_actionid_feedback). 
In particular, `status.result.progress` and `status.details` for `status.execution`=`proceeding` is interesting here.

**Comment by kaizimmerm** [comment]
I like the idea 👍  We have this currently only in the Management API but I see your point
