### ISSUE TITLE
Horizontal scrollbar is not visible in the Rollout Management View

### ISSUE THREAD

**Issue by EugenWiens** [eclipse/hawkbit#384]
When I played around in the Rollout Management View with the columns width I get a gray rectangle but no horizontal scrollbar in site. My first suspicion was that my theme settings are wrong but on the demo Server https://hawkbit.eu-gb.mybluemix.net/UI/#!rollout this bug also presented.

It would be great to see on the Page the current version for reporting. May be somewhere in a corner.

**Comment by michahirsch** [comment]
That's true, there is no scroll-bar showing when increase the with of the columns. There is a [Vaadin-Grid Demo](https://vaadin.com/grid) which actually showing it. When you increase the with of the columns a horizontal scroll-bar shows up.

**Comment by EugenWiens** [comment]
This bug appears only in the RolloutView. I tested the some other Views but I don't see this bug.

**Comment by EugenWiens** [comment]
Hi @michahirsch I checked this Bug this morning with the Git ID ac85996eb67ca9bb73fe5680292374bd584ac68c and now the scroll-bar is visible.
