### ISSUE TITLE
How can I remove old Rollouts

### ISSUE THREAD

**Issue by EugenWiens** [eclipse/hawkbit#386]
In the the Rollout Management View is no way to remove old Rollouts. Is it possible to add an delete button to each Row ?

**Comment by michahirsch** [comment]
This has not been implemented yet but it's definitely a missing feature for the `RolloutView`.

**Comment by EugenWiens** [comment]
Ok thank you for the Info I will wait 😁

Michael Hirsch <notifications@github.com> schrieb am Do., 8. Dez. 2016,
17:18:

**Comment by michahirsch** [comment]
You are also more the welcome to contribute this missing feature :) :+1:

**Comment by EugenWiens** [comment]
Sorry but I'm not a web developer. This stuff is black magic for me. I'm a
embedded Linux developer.

Michael Hirsch <notifications@github.com> schrieb am Do., 8. Dez. 2016,
17:26:

You are also more the welcome to contribute this missing feature :) 👍

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eclipse/hawkbit/issues/386#issuecomment-265783969>, or mute
the thread

**Comment by kaizimmerm** [comment]
Help is on the way btw. https://github.com/eclipse/hawkbit/pull/436

**Comment by michahirsch** [comment]
#436 is merged on the master
