### ISSUE TITLE
Software download link provided has "localhost" as server

### ISSUE THREAD

**Issue by peterdewitte** [eclipse/hawkbit#393]
Hi,

I ran swupdate in combination with hawkbit. In the logs of swupdate I noticed that the download link provided from hawkbit has "localhost" as server. This fails of course.

In the swupdate log appended in [attachment](https://github.com/eclipse/hawkbit/files/651992/localhost.txt), line 23 shows a correct link to my server (REST API link) and line 27 shows the answer of the hawkbit server. In that answer, "localhost" is provided as download server.

Where can I fix this issue?

Best regards

Peter De Witte
[localhost.txt](https://github.com/eclipse/hawkbit/files/651992/localhost.txt)

**Comment by sbabic** [comment]
Hi Peter,

On 14/12/2016 15:35, Peter De Witte wrote:
> Hi,
> 
> I ran swupdate in combination with hawkbit. In the logs of swupdate I
> noticed that the download link provided from hawkbit has "localhost" as
> server. This fails of course.
> 
> In the swupdate log appended in attachment, line 23 shows a correct link
> to my server (REST API link) and line 27 shows the answer of the hawkbit
> server. In that answer, "localhost" is provided as download server.
> 
> Where can I fix this issue?
> localhost.txt
> <https://github.com/eclipse/hawkbit/files/651992/localhost.txt>
> 


I ran the same issue and I start the property at startup, with java
--jar ....
--spring.config.location=examples/hawkbit-example-app/src/main/resources/application.properties
--hawkbit.url=patito.fritz.box:8080

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by kaizimmerm** [comment]
We are actually pretty bad concerning the configuration options. We will look into it through.
