### ISSUE TITLE
Downloading artifacts fails

### ISSUE THREAD

**Issue by peterdewitte** [eclipse/hawkbit#411]
Hi,

Hawkbit fails to download the update artefacts. If I download the uploaded artifact via the UI, I get this error:

Download link: _http://serverip:8080/DEFAULT/controller/v1/25/softwaremodules/1/artifacts_/inose_551020161216140356.swu
Response: 

>{"exceptionClass":"org.eclipse.hawkbit.repository.exception.GridFSDBFileNotFoundException","errorCode":"hawkbit.server.error.artifact.loadFailed","message":"23c5cdd7850b903e10b1dcf8df0554f9d466d3c7"}

If I ask the available artefacts, I get the correct download link:
Download link: http://serverip:8080/DEFAULT/controller/v1/25/softwaremodules/1/artifacts
Response: 

> [{"filename":"inose_551020161216140356.swu","hashes":{"sha1":"23c5cdd7850b903e10b1dcf8df0554f9d466d3c7","md5":"161637a8682ee1706463ed896670f99e"},"size":78853632,"_links":{"download-http":{"href":"http://serverip:8080/DEFAULT/controller/v1/25/softwaremodules/1/artifacts/inose_551020161216140356.swu"},"md5sum-http":{"href":"http://52.16.170.80:8080/DEFAULT/controller/v1/25/softwaremodules/1/artifacts/inose_551020161216140356.swu.MD5SUM"}}}]

This is a copy of the log token from the example app with the --debug flag enabled:
> 2017-01-05 12:48:04.753  INFO 31193 --- [executor-pool-1] o.e.h.r.jpa.rollout.RolloutScheduler     : Checking creating rollouts for 1 tenants
> 2017-01-05 12:48:04.760  INFO 31193 --- [executor-pool-0] o.e.h.r.jpa.rollout.RolloutScheduler     : Checking starting rollouts for 1 tenants
> 2017-01-05 12:48:05.910 DEBUG 31193 --- [qtp367967231-19] o.s.b.c.web.OrderedRequestContextFilter  : Bound request context to thread: Request(GET /DEFAULT/controller/v1/25/softwaremodules/1/artifacts/inose_551020161216140356.swu)@a4d2e14
> 2017-01-05 12:48:05.910 DEBUG 31193 --- [qtp367967231-19] o.s.b.a.e.mvc.EndpointHandlerMapping     : Looking up handler method for path /DEFAULT/controller/v1/25/softwaremodules/1/artifacts/inose_551020161216140356.swu
**> 2017-01-05 12:48:05.912 DEBUG 31193 --- [qtp367967231-19] o.s.b.a.e.mvc.EndpointHandlerMapping     : Did not find handler method for [/DEFAULT/controller/v1/25/softwaremodules/1/artifacts/inose_551020161216140356.swu]**
> 2017-01-05 12:48:05.936 DEBUG 31193 --- [qtp367967231-19] o.s.b.c.web.OrderedRequestContextFilter  : Cleared thread-bound request context: Request(GET /DEFAULT/controller/v1/25/softwaremodules/1/artifacts/inose_551020161216140356.swu)@a4d2e14
> 2017-01-05 12:48:06.757  INFO 31193 --- [executor-pool-2] o.e.h.r.jpa.rollout.RolloutScheduler     : Checking creating rollouts for 1 tenants
> 2017-01-05 12:48:06.763  INFO 31193 --- [executor-pool-1] o.e.h.r.jpa.rollout.RolloutScheduler     : Checking starting rollouts for 1 tenants

Somebody knows what the root cause can be?

Thx

Peter

**Comment by SirWayne** [comment]
Are there any repository/rollout management tests for the feature?

**Comment by SirWayne** [comment]
Sorry for the late reply. I will check this issue.

**Comment by SirWayne** [comment]
Your download link is wrong. After `/artifacts` there is a additonal`_`.
Compare the two download links:
Your:`.../controller/v1/25/softwaremodules/1/artifacts**_**/inose_551020161216140356.swu`
Json:`controller/v1/25/softwaremodules/1/artifacts/inose_551020161216140356.swu`

**Comment by SirWayne** [comment]
For you information. In the meantime, there are no `org.eclipse.hawkbit.repository.exception.GridFSDBFileNotFoundException` anymore. 
In the example application, the files are stored on disk.Would you like to use a mongo db, you have to add the [hawkbit mongo db extension](https://github.com/eclipse/hawkbit/tree/master/extensions/hawkbit-extension-artifact-repository-mongo)

**Comment by kaizimmerm** [comment]
No feedback in 21 days
