### ISSUE TITLE
Sandbox is down?

### ISSUE THREAD

**Issue by kartben** [eclipse/hawkbit#413]
The login fails when clicking on "Demo", but the login somehow succeeds nevertheless since one can access "https://hawkbit.eu-gb.mybluemix.net/" properly afterthat
*however* virtually no operation works, since everything in the UI (e.g create a new target) seems to fail with the following exception:

```
The operation cannot be fulfilled due to TenantNotExistException. Please contact administrator
```

**Comment by kaizimmerm** [comment]
Fix is online

**Comment by fedenunez** [comment]
@kaizimmerm now it is offline :(
