### ISSUE TITLE
UAA Extension doesn't work as described in readme

### ISSUE THREAD

**Issue by mattmcla** [eclipse/hawkbit#414]
After having followed the instructions in ./extensions/hawkbit-extension-uaa with the example app we were unable to see hawkbit make a connection to UAA. It appeared to default to the admin:admin credentials. 

1. Make changes as described here extensions/hawkbit-extension-uaa/README.md in the example app
2. mvn clean install
3. java -jar examples/hawkbit-example-app/target/hawkbit-example-app-0.2.0-SNAPSHOT.jar
4. Logging in with UAA credentials results in a failed login attempt. It does not appear any attempt was made to reach UAA and the admin:admin credentials still work.

**Comment by mattmcla** [comment]
Actually I failed to notice the login point was /uaalogin. Worked as expected. thanks!

**Comment by michahirsch** [comment]
Thanks, :1:
