### ISSUE TITLE
C Based sample device implementation for very small microcontrollers?

### ISSUE THREAD

**Issue by ryanmmmmm** [eclipse/hawkbit#431]
Is there going to be a C based sample device or library to use on smaller microcontrollers?

**Comment by kaizimmerm** [comment]
Not as I know But I recommend to look into https://github.com/eclipse/leshan with https://github.com/eclipse/wakaama. However, leshan is not yet integrated with hawkBit.

**Comment by michahirsch** [comment]
There is a C implementation for Yocto based linux available: https://github.com/sbabic/swupdate

**Comment by sbabic** [comment]
On 17/03/2017 09:53, Michael Hirsch wrote:
> There is a C implementation for Yocto based linux available:
> https://github.com/sbabic/swupdate
> 

It is true, but it should be very interesting to know which is Ryan's
target. SWUpdate is a POSIX application (I avoided to use some more
comfortable library that makes a possible porting very difficult), but
it requires libraries for accessing internet (libcurl) and parsing the
JSON answer from the server (json-c). At least replaces for these two
libraries are required. Ryan, can you tell which is your target ? Do you
have a bare-metal app, or you are using FreeRTOS, a proprietary OS,
uclinux, ... ?

Best regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by michahirsch** [comment]
Thanks @sbabic  for the clarification.

**Comment by stefferber** [comment]
@michahirsch @michahirsch Could you add this to the "standard" hawk bit documentation. This is a question for almost every embedded developer.

**Comment by kaizimmerm** [comment]
Good point. I added a link to Readme with #473
