### ISSUE TITLE
Problem with Distribution View

### ISSUE THREAD

**Issue by EugenWiens** [eclipse/hawkbit#437]
After uploading an 110 MB artifact I try to create a Distribution. When I select the view in the left "navigation bar" I get an error 
![image](https://cloud.githubusercontent.com/assets/7880602/22889824/ba5703a6-f20a-11e6-8dc1-d3af00c14902.png)

Log:
`Feb 13 16:40:31 es-lxserver mvn[2052]: 2017-02-13 16:40:31.261  INFO 2052 --- [executor-pool-2] o.e.h.r.jpa.rollout.RolloutScheduler     : Checking starting rollouts for 1 tenants
Feb 13 16:40:33 es-lxserver mvn[2052]: 2017-02-13 16:40:33.266  INFO 2052 --- [executor-pool-2] o.e.h.r.jpa.rollout.RolloutScheduler     : Checking starting rollouts for 1 tenants
Feb 13 16:40:33 es-lxserver mvn[2052]: 2017-02-13 16:40:33.266  INFO 2052 --- [executor-pool-0] o.e.h.r.jpa.rollout.RolloutScheduler     : Checking creating rollouts for 1 tenants
Feb 13 16:40:35 es-lxserver mvn[2052]: 2017-02-13 16:40:35.166  WARN 2052 --- [tp1180749082-30] v.s.e.i.ScopedEventBus$DefaultUIEventBus : Listener [org.eclipse.hawkbit.ui.distributions.disttype.CreateUpdateDistSetTypeLayout@227b546] did not contain a single listener method!
Feb 13 16:40:35 es-lxserver mvn[2052]: 2017-02-13 16:40:35.189  WARN 2052 --- [tp1180749082-30] v.s.e.i.ScopedEventBus$DefaultUIEventBus : Listener [org.eclipse.hawkbit.ui.artifacts.smtype.CreateUpdateSoftwareTypeLayout@74300fcf] did not contain a single listener method!
Feb 13 16:40:35 es-lxserver mvn[2052]: 2017-02-13 16:40:35.270  INFO 2052 --- [executor-pool-0] o.e.h.r.jpa.rollout.RolloutScheduler     : Checking creating rollouts for 1 tenants
Feb 13 16:40:35 es-lxserver mvn[2052]: 2017-02-13 16:40:35.270  INFO 2052 --- [executor-pool-2] o.e.h.r.jpa.rollout.RolloutScheduler     : Checking starting rollouts for 1 tenants
Feb 13 16:40:37 es-lxserver mvn[2052]: 2017-02-13 16:40:37.274  INFO 2052 --- [executor-pool-2] o.e.h.r.jpa.rollout.RolloutScheduler     : Checking starting rollouts for 1 tenants
`

**Comment by EugenWiens** [comment]
The same Error occurs when I uplode the file.

My Version is GitId c03114290631eaf813154b40a55401f4a867128f

**Comment by EugenWiens** [comment]
I go back to the Version 59f218e841611f8a6dfd6e5c1e8601d7d863c82e and now it works

**Comment by EugenWiens** [comment]
At first sight it looks like the error #319 but I'm not using forwarding. I will test some other GitIds and will come back with results.

**Comment by EugenWiens** [comment]
Ok now I found the commit that cause the problem. 
GitID: 21181bc6f857edf3b3c2b4153f4ca078e3bed5c1
Update Spring Boot & Hateoas (#430)
 * Upgrade spring boot 1.4.4 and hateoas 0.23. Removed unneded dependency
...

Is there a migration step that I missed ?

**Comment by kaizimmerm** [comment]
You are right. Something breaks when using the upload. Let me look into this.

**Comment by kaizimmerm** [comment]
Seems to be related to the Jetty upgrade that came with Boot 1.4.4 . Going back with the `<jetty.version>9.3.14.v20161028</jetty.version>` property in the hawkBit parent pom should do the trick. Can you confirm this?

**Comment by EugenWiens** [comment]
Cool it works. Set the version of jetty solves the problem.
What can be the next steps?

**Comment by kaizimmerm** [comment]
Fis is on master https://github.com/eclipse/hawkbit/pull/438
