### ISSUE TITLE
Global Action History

### ISSUE THREAD

**Issue by EugenWiens** [eclipse/hawkbit#441]
The "Action History Widget" in the deployment view is in the normal size (not maximized) to small to view all information. Would not it be better if the widget would get its own view. This view could contains all devices and other views (e.g. Rollout) can refer to the item in this view.

**Comment by michahirsch** [comment]
One improvement we are going to bring to the action history is, in case of maximizing the action history to split the tree into three different lists.  see https://github.com/eclipse/hawkbit/pull/420
* Action
* Action Status
* Action Status Messages

To get a quick overview about a one specific deployment without the need to expand the single action in the tree. 

Another approach is to reference all the entities in the UI by linking. So in case you having an action which is created by an rollout you can press on the rollout of this specific action and you jump to the rollout view. But this idea is not implemented yet.

**Comment by EugenWiens** [comment]
Ok. I will check the #420 after the pull request is merged into master.

We have done some test with some devices and see this enhancement and wanted to share this idea.

**Comment by michahirsch** [comment]
We are happy to get feedback of use-cases and hawkBit usage. We are aware that the deployment-view is showing a lot of information at once but all of the information is necessary though :). So hard to compromise and split the UI in the different use-cases to enable a quick power-use without many view changes. 

Thanks.

**Comment by EugenWiens** [comment]
@michahirsch we have looked at #420 it looks better. Basically it looks good. Is it possible to put more as one device to the view ? Is it plant ? If not for what is the the idea behind the left column currently it can only handle one device.

**Comment by michahirsch** [comment]
@EugenWiens the improve #420 is already on the master and yes currently there is only support for checking action history details for one **selected** device. I'm not sure how you would show action details with message for multiple devices at the same time. 

I guess to improve the useability of the action history details is to allow quicker switching devices instead of minimize the detail action history again, select another device and maximize the action history again. 

Feedback welcome :)
Cheers,
Michael

**Comment by avgustinmm** [comment]
Vaadin 8 UI is discontinued - https://eclipse.dev/hawkbit/blog/2023-11-22-vaadin8_ui_discontinuation/
