### ISSUE TITLE
Empty guide reference in Readme

### ISSUE THREAD

**Issue by marziman** [eclipse/hawkbit#444]
The link in the readme at compile, run etc. "guide" brings up an empty wiki page (https://github.com/eclipse/hawkbit/wiki/Run-hawkBit).
I just wanted to set it up and make myself ready to contribute and found this.
BR Mehmet

**Comment by michahirsch** [comment]
We currently moving the documentation to the hawkBit project page. You found a dead link in the readme.md, thanks.
The documentation  is moved here 
http://www.eclipse.org/hawkbit/documentation/guide/runhawkbit.html

**Comment by kaizimmerm** [comment]
Fixed in #461
