### ISSUE TITLE
Is there any plan to support MQTT?

### ISSUE THREAD

**Issue by jiangyuhe123** [eclipse/hawkbit#449]
Since RabbitMQ is also support MQTT by plugs, is there any plan for hawkbit to support MQTT besides AMQP?

MQTT is more and more widely used in device communication.

**Comment by kaizimmerm** [comment]
Hi, we plan to integrate hawkBit with https://github.com/eclipse/hono for that kind of connectivity. However, hono currently does not support bi-directional communication which is however required by hawkBit. We will look into this as soon as hono is ready.

**Comment by kaizimmerm** [comment]
No response

**Comment by tpaul1611** [comment]
@kaizimmerm I am currently evaluating hawkBit as an OTA solution for an IoT project and have a difficult time understanding if MQTT is supported or not. Is there any news to this topic?

**Comment by gunnarpieter** [comment]
@tpaul1611 @kaizimmerm same here
