### ISSUE TITLE
Problems with the feedback chanel

### ISSUE THREAD

**Issue by EugenWiens** [eclipse/hawkbit#467]
During the update procedure our update agent reports the status to the hawkbit update server. We use following `URL POST /{tenant}/controller/v1/{targetid}/deploymentBase/{actionId}/feedback.` to report the status. After some feedback message we get an error back from hawkbit.
`errorcode:206 {\"exceptionClass\":\"org.eclipse.hawkbit.repository.exception.ConcurrentModificationException\",\"errorCode\":\"hawkbit.server.error.repo.concurrentModification\",\"message\":\"The given entity has been changed by another user/session\"}"`

![image](https://cloud.githubusercontent.com/assets/7880602/24545566/e7a041bc-1607-11e7-8bc0-bb251ee9c54e.png)

![image](https://cloud.githubusercontent.com/assets/7880602/24545651/41407318-1608-11e7-9963-ad3350c0979c.png)

**Comment by kaizimmerm** [comment]
Well the exception said what the problem is. Two changes were pushed on the target at the same time. 

Is that possible in your scenario? One other question, your screenshot looks like that the feedback did arrive successfully? Is that correct?

**Comment by EugenWiens** [comment]
> Well the exception said what the problem is. Two changes were pushed on the target at the same time.
What means at the same time. We report feedback with out queuing every event that occurs is directly pushed to the server. We don't wait for the HTTP OK of the last feedback message. Is this a problem ?

> Is that possible in your scenario? One other question, your screenshot looks like that the feedback did arrive successfully? Is that correct?
In the screenshot you can see the messages that arrived successfully. During the whole procedure we get 3 Errors during sending and the corresponding messages are missing on the server.

**Comment by kaizimmerm** [comment]
This explains the behaviour. Multiple changes at the same time will result in this response. hawkBit has to ensure that one change does not override the other. For instance, one feedback reports successful, one reports error. You are not doing this obviously but hawkBit cannot tell and as a result rejects the update that came in later.

Imho you have the option to report in a synchronised fashion as you said or leave it that way. In this case your client has to consider this error and maybe react with a retry. I would go with this option as the risk that two changes happen on a target might also have other causes and its always good for a client to handle it.

**Comment by EugenWiens** [comment]
Thank you for the information. We will check if we can add a que. We did not think that hawkBit has a problem with this scenario.

**Comment by kaizimmerm** [comment]
You are welcome 😎
