### ISSUE TITLE
hawkbit-device-simulator fails to start

### ISSUE THREAD

**Issue by joeythesaint** [eclipse/hawkbit#495]
I'm trying out the canned scenarios for a update server (using the docker image at https://hub.docker.com/r/hawkbit/hawkbit-update-server/) and the hawkbit-device-simualtor.  The update server comes up fine for me (both in the docker configuration and native on my workstation, for what it's worth) but running the device simulator fails with a number of error messages.  The ones that stick out for me are "connection refused" and "application startup failed".  I captured the full log here:  https://gist.github.com/8827cd1c7dd389d4174c5af5490d929e

This is on a Debian 8.5 machine with Oracle's JDK 8 installed not as the default java environment, but as you can see in the gist I'm running Oracle's Java with `JAVA_HOME` set.  This is the same compiler I pointed Maven at while building the top-level and examples and while I didn't examine all the output from the build, the end results of both the top-level and the `examples/` build indicated success.

Can anyone help me understand what's happening here?

**Comment by kaizimmerm** [comment]
Hi, 

check out the README: https://github.com/eclipse/hawkbit/tree/master/examples/hawkbit-device-simulator By default AMQP DMF API is enabled. `hawkbit.device.simulator.amqp.enabled=false` should do the trick.

Kai

**Comment by michahirsch** [comment]
In case you want to use the DMF functionality in the device-simulator you'll need to setup a rabbitMQ (e.g. also with docker) where the device-simulator and the hawkbit-update-server can connect to.

**Comment by ujagaga** [comment]
Hi, I have the same error on XUbuntu16. Following the suggested solution, I changed awkbit.device.simulator.amqp.enabled=false but now I get an error:

Field spSenderService in org.eclipse.hawkbit.simulator.DeviceSimulatorUpdater required a bean of type 'org.eclipse.hawkbit.simulator.amqp.DmfSenderService' that could not be found.
	- Bean method 'dmfSenderService' not loaded because @ConditionalOnProperty (hawkbit.device.simulator.amqp.enabled) found different value in property 'enabled'

Did anyone solve this?

**Comment by jabelshauser** [comment]
anyone solved this in the mean time ? I have the same issue

**Comment by schabdo** [comment]
@ujagaga @jabelshauser should be fixed in the meanwhile on `master`
