### ISSUE TITLE
Suricatta doesn't update until restarted

### ISSUE THREAD

**Issue by voltatindell** [eclipse/hawkbit#502]
I upload and define a distribution in hawkBit while a Scuicatta daemon is running, assign the distribution to the target, but it doesn't update until I stop and restart the daemon.  What's up with this?

**Comment by michahirsch** [comment]
I guess this issue is related to the https://github.com/sbabic/swupdate project so I guess @sbabic can help out with this.

**Comment by sbabic** [comment]
Hi Mike,

On 05/05/2017 07:56, voltatindell wrote:
> I upload and define a distribution in hawkBit while a Scuicatta daemon
> is running, assign the distribution to the target, but it doesn't update
> until I stop and restart the daemon. What's up with this?
> 
> —

Please send SWUpdate's questions to SWUpdate ML, too, else just people
reading the Hawkbit ML can read them.

I am not expecting that the update is started as soon as you assign a
distribution to a target. In fact, the suricatta daemon does something
just when the polling interval timer expires. The polling interval is
set via the Hawkbit's GUI, but it can overridden (at the startup) using
SWUpdate's configuration file.

SWUpdate does one action per polling cycle: when it starts, first checks
for the deviceInfo on server, then sends a configData message with own
data, and just afterwards (that means at least a polling cycle later)
checks for an update. Are you sure you have not waited enough ?

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by voltatindell** [comment]
The arguments I give to swupdate are:

          -l 5 -u '-t default -u http://localhost:8080 -i 1'

There are a few issues that puzzle me:
* The 'Last poll' time in hawkBit UI does not continue to update after the daemon was started and 
  downloaded the .swu file.
* Update always downloads immediately after daemon is started, even if it was previously downloaded.
* Assigning a new distribution to a target does not cause a download while the daemon is running.

Daemon is sleeping for 30s with late setting in hawkBit set to 1m.  The Suricatta ain loop processes SERVER_ID_REQUESTED messages, but doesn't seem to get the message when a distribution is assigned to that target.

**Comment by voltatindell** [comment]
Waited a day for new distribution yo be downloaded.  The EC2 instance is still running.

**Comment by sbabic** [comment]
I am having problems with integrating hawkBit and SWUpdate.  The arguments 
I give to swupdate are:

      -l 5 -u '-t default -u http://localhost:8080 -i 1'

There are a few issues that puzzle me:

   - The 'Last poll' time in hawkBit UI does not continue to update after 
   the daemon was started and
   downloaded the .swu file, even if the page is reloaded.
   - Update always downloads immediately after daemon is started, even if 
   it was previously downloaded.
   - Assigning a new distribution to a target does not cause a download 
   while the daemon is running.

Daemon is sleeping for 30s with late setting in hawkBit set to 1m. The 
Suricatta main loop processes SERVER_ID_REQUESTED messages, but doesn't get 
the SERVER_UPDATE_AVAILABLE message when a distribution is assigned to that 
target.


I'd really appreciate some feedback from others who are successfully using 
hawkBit and SWUpdate.


Many thanks,

--Mike Tindell

**Comment by sbabic** [comment]
Hi Mike,

On 08/05/2017 18:11, mike.tindell@voltacharging.com wrote:
> I am having problems with integrating hawkBit and SWUpdate.  The
> arguments I give to swupdate are:
> 
> |-l 5 -u '-t default -u http://localhost:8080 -i 1' |
> 

Is your device even running Hawkbit ?

> There are a few issues that puzzle me:
> 
>   * The 'Last poll' time in hawkBit UI does not continue to update after
>     the daemon was started and
>     downloaded the .swu file, even if the page is reloaded.
>   * Update always downloads immediately after daemon is started, even if
>     it was previously downloaded.
>   * Assigning a new distribution to a target does not cause a download
>     while the daemon is running.
> 
> Daemon is sleeping for 30s with late setting in hawkBit set to 1m. The
> Suricatta main loop processes SERVER_ID_REQUESTED messages, but doesn't
> get the SERVER_UPDATE_AVAILABLE message when a distribution is assigned
> to that target.
> 
> 
> I'd really appreciate some feedback from others who are successfully
> using hawkBit and SWUpdate.

Try to start with -v (verbose) and post the resulting log.

Best regards,
Stefano


-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by sbabic** [comment]
Hi SWupdaters and Hawkbitters!

On Friday, May 5, 2017 at 10:12:50 AM UTC+2, Stefano Babic wrote:
>
> Hi Mike, 
>
> On 05/05/2017 07:56, voltatindell wrote: 
> > I upload and define a distribution in hawkBit while a Scuicatta daemon 
> > is running, assign the distribution to the target, but it doesn't update 
> > until I stop and restart the daemon. What's up with this? 
> > 
> > — 
>
> Please send SWUpdate's questions to SWUpdate ML, too, else just people 
> reading the Hawkbit ML can read them. 
>
> I am not expecting that the update is started as soon as you assign a 
> distribution to a target. In fact, the suricatta daemon does something 
> just when the polling interval timer expires. The polling interval is 
> set via the Hawkbit's GUI, but it can overridden (at the startup) using 
> SWUpdate's configuration file. 
>
> SWUpdate does one action per polling cycle: when it starts, first checks 
> for the deviceInfo on server, then sends a configData message with own 
> data, and just afterwards (that means at least a polling cycle later) 
> checks for an update. Are you sure you have not waited enough ? 
>

I'm posting to this thread as I think I've been hitting the same problem, 
and I've been trying to debug the problem in the last couple of days.
For clarity, I'm using SWUpdate 2017.01, so the code I refer to is picked 
from that tag.

DESCRIPTION OF THE PROBLEM:
If you assign an update to a target and *then* start the swupdate daemon, 
swupdate picks up the update.
If you start the swupdate daemon and *then* assign an update to a target, 
swupdate regularly polls but doesn't pick the update (unless a swupdate.cfg 
with "identify" section is provided).

(POSSIBLE) SOURCE OF THE PROBLEM:
When the "start_suricatta" loop checks for pending actions in 
"has_pending_action", server_hawkbit.c immediately checks if it has to send 
config date. "has_to_send_configData" is true after the first time 
"server_has_pending_action" is called, as "server_set_config_data" is 
generally called. As a consequence "server.send_target_data()" is called in 
suricatta.c. In "server_send_target_data", "server_hawkbit.configdata" is 
empty if no "identify" section is specify in swupdate.cfg, thus "len" is 0. 
As a consequence the call to "server_send_target_data" returns SERVER_OK 
immediately, and the "has_to_send_configData" remains true.

WORKAROUND:
On the contrary defining a "identify" section in swupdate.cfg causes 
"server_hawkbit.configdata" to be populated at server start by the 
"dict_set_value" calls in "suricatta_configdata_settings". This causes 
"server_hawkbit.configdata" to execute fully, triggering a correct fetch of 
updates from the Hawkbit server.

I hope my analysis is correct, let me know if this is to be considered a 
bug or somehow an expected behaviour.

Bests,
Diego

**Comment by sbabic** [comment]
Hi Diego,

On 08/05/2017 19:59, diego.rondini@kynetics.com wrote:
> Hi SWupdaters and Hawkbitters!
> 
> On Friday, May 5, 2017 at 10:12:50 AM UTC+2, Stefano Babic wrote:
> 
>     Hi Mike,
> 
>     On 05/05/2017 07:56, voltatindell wrote:
>     > I upload and define a distribution in hawkBit while a Scuicatta
>     daemon
>     > is running, assign the distribution to the target, but it doesn't
>     update
>     > until I stop and restart the daemon. What's up with this?
>     >
>     > —
> 
>     Please send SWUpdate's questions to SWUpdate ML, too, else just people
>     reading the Hawkbit ML can read them.
> 
>     I am not expecting that the update is started as soon as you assign a
>     distribution to a target. In fact, the suricatta daemon does something
>     just when the polling interval timer expires. The polling interval is
>     set via the Hawkbit's GUI, but it can overridden (at the startup) using
>     SWUpdate's configuration file.
> 
>     SWUpdate does one action per polling cycle: when it starts, first
>     checks
>     for the deviceInfo on server, then sends a configData message with own
>     data, and just afterwards (that means at least a polling cycle later)
>     checks for an update. Are you sure you have not waited enough ?
> 
> 
> I'm posting to this thread as I think I've been hitting the same
> problem, and I've been trying to debug the problem in the last couple of
> days.
> For clarity, I'm using SWUpdate 2017.01, so the code I refer to is
> picked from that tag.
> 
> DESCRIPTION OF THE PROBLEM:
> If you assign an update to a target and *then* start the swupdate
> daemon, swupdate picks up the update.
> If you start the swupdate daemon and *then* assign an update to a
> target, swupdate regularly polls but doesn't pick the update (unless a
> swupdate.cfg with "identify" section is provided).
> 
> (POSSIBLE) SOURCE OF THE PROBLEM:
> When the "start_suricatta" loop checks for pending actions in
> "has_pending_action", server_hawkbit.c immediately checks if it has to
> send config date.

Right. SWupdate tries once to get the deviceInfo, and if the server is
found and answers, it will send a configData message.

No other action are taken until the Hawkbit server accepts (HTTP 200)
the configData message.

> "has_to_send_configData" is true after the first time
> "server_has_pending_action" is called, as "server_set_config_data" is
> generally called. As a consequence "server.send_target_data()" is called
> in suricatta.c. In "server_send_target_data",
> "server_hawkbit.configdata" is empty if no "identify" section is specify
> in swupdate.cfg, thus "len" is 0. As a consequence the call to
> "server_send_target_data" returns SERVER_OK immediately, and the
> "has_to_send_configData" remains true.

Ok, got it. It can be checked if identities are read from the
configuration file, and if there are not, the step with configData can
be skipped.

> 
> WORKAROUND:
> On the contrary defining a "identify" section in swupdate.cfg causes
> "server_hawkbit.configdata" to be populated at server start by the
> "dict_set_value" calls in "suricatta_configdata_settings". This causes
> "server_hawkbit.configdata" to execute fully, triggering a correct fetch
> of updates from the Hawkbit server.

Right, it works exactly as you described.

> 
> I hope my analysis is correct, let me know if this is to be considered a
> bug or somehow an expected behaviour.
> 

The behavior is what I implemented - at least, I expect it :-). But it
can be checked if configData is empty and step can be skipped.

Best regards,
Stefano


-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by voltatindell** [comment]
So it looks like I can get the behavior I want by using having something loaded from swupdate.cfg.  How do I run swupdate to use a .cfg file?  The fname is NULL by default.

**Comment by sbabic** [comment]
On 09/05/2017 01:30, voltatindell wrote:
> So it looks like I can get the behavior I want by using having something
> loaded from swupdate.cfg. How do I run swupdate to use a .cfg file? The
> fname is NULL by default.
> 

The -f option is used to pass a configuration file. You find an exampe
in examples/configuration

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by diegorondini** [comment]
I think the hawkbit bug can be closed, as this is not an hawkbit problem.

**Comment by michahirsch** [comment]
Yeah seems like, closing it thx.
