### ISSUE TITLE
Sonar Rules Download Link gives 404

### ISSUE THREAD

**Issue by stormc** [eclipse/hawkbit#503]
In the [CONTRUBUTING.md](https://github.com/eclipse/hawkbit/blob/master/CONTRUBUTING.md), the hawkBit Sonar rule set is mentioned as being available under http://sonar.eu-gb.mybluemix.net/ which however gives a 404. Would you mind to make the rule set available again?

As a side note, `CONTRUBUTING.md` should be renamed to `CONTRIBUTING.md`, which may then be my first source contribution to hawkBit :)

**Comment by michahirsch** [comment]
The link to the sonar is wrong in the `CONTRUBUTING.md` good point. The sonar currently used is http://sonar.ops.bosch-iot-rollouts.com/projects .

The `CONTRUBUTING.md` must be udpated! 

Good point,
Thanks,
Michael
