### ISSUE TITLE
REST API to set polling intervals?

### ISSUE THREAD

**Issue by EmbeddedAndroid** [eclipse/hawkbit#536]
Hi,

I've been using the management API to automate the testing of our OTA update solution. In our test environment, we deploy hawkbit with KVM + Docker (https://hub.docker.com/r/hawkbit/hawkbit-update-server/) along with our edge gateways, and IoT devices to perform end to end testing. Each time we deploy, all devices under test are bootstrap'd from metal, so we have a clean environment each time. 

The problem I am facing now is that the default five minute poll interval makes the testing take longer that I'd hoped. I've done some digging in the API documents, and can't see a way to set the polling interval, maybe I've missed something. Does such a feature exist? If not, would this be an API you are willing to support? Is there another way to programicially set this interval? 

Thanks in advance!

**Comment by kaizimmerm** [comment]
Actually there ist, but somehow we missed to document that resource. Maybe this helps to get started: https://github.com/eclipse/hawkbit/blob/master/hawkbit-mgmt-api/src/main/java/org/eclipse/hawkbit/mgmt/rest/api/MgmtSystemRestApi.java I will try to get some documentation done in the upcomming days.

**Comment by EmbeddedAndroid** [comment]
Great, thanks for the quick response. I figured this had to be implemented already.
