### ISSUE TITLE
Running the quickstart command runs server with missing style sheet

### ISSUE THREAD

**Issue by ctron** [eclipse/hawkbit#541]
Steps to reproduce:

1) Checkout sources
1) Run `mvn clean package -DskipTests`
1) Run `java -jar hawkbit-runtime/hawkbit-update-server/target/hawkbit-update-server-0.2.0-SNAPSHOT.jar`
1) Navigate to http://localhost:8080

This loads the Web UI, but missing all style sheet information. A look into the browser developer console shows that loading `styles.css?v=7.7.9` returns a 404.

Running the docker image works tough.

**Comment by jcEcaSinters** [comment]
I do not know VAADIN at all (nor java - i'm just a dumb user), but it seem that if you switch Ui to production=false, CSS will be generate on the fly. See [VAADIN forum](https://vaadin.com/forum#!/thread/2336811)
To test this answer you can change set `vaadin.servlet.productionMode=false` in `hawkbit-ui/src/main/resources/hawkbit-ui-defaults.properties`
I'm agree, a note in the documentation should be set to compile VAADIN CSS (did not had time to figure this out) for a production environment.

**Comment by kaizimmerm** [comment]
Sry for the late reply. I will look into this.

**Comment by kaizimmerm** [comment]
Hmm, I was running this exactly as you on current master but cannot reproduce the issue. Have you tried to reset your browser cache. Maybe something got mixed up there.

btw. hawkBit by default builds the theme. So disabling production mode should not be necessary.

You should see in your maven logs something like this:
```
INFO] --- vaadin-maven-plugin:7.7.9:update-theme (default) @ hawkbit-ui ---
[INFO] Updating theme VAADIN/themes/hawkbit
```

and find this file 

```
hawkbit-ui/target/classes/VAADIN/themes/hawkbit/styles.css
```

**Comment by ctron** [comment]
Ok, I will give it another try.

**Comment by ctron** [comment]
I can't reproduce it either. Issue closed 😀 

I simply did `git pull` and `mvn clean package` as before. I could also see it update the message you mentioned and the file in the right location.

I am not sure what went wrong the last time.
