### ISSUE TITLE
No Distributions shown on Deployment page

### ISSUE THREAD

**Issue by subhadippramanik** [eclipse/hawkbit#554]
Hello Team,

I followed the readme provided on master branch. Cloned the project and started both simulator and update server from eclipse. But after adding Distributions and SW modules I don't see them on Deployment page.
There is no proper documentation on how to start with..
Could someone help me to start with this? I would really appreciate if I get to know what exactly is missing on my setup.

![deployments](https://user-images.githubusercontent.com/16714252/27802798-99cc5080-6043-11e7-9ba1-01cec95faaa4.PNG)

![distributions](https://user-images.githubusercontent.com/16714252/27802849-e8f15610-6043-11e7-84e1-d85a8d2816c0.PNG)

I am running everything on Ubuntu.

Thanks,
Happy Coding

**Comment by kaizimmerm** [comment]
You need to assign modules to the DistributionSet according to what is defined as mandatory is the used distributions type. Based on your screen I would assume that your DS does not have a module of type "os". hawkBit then considers it incomplete and does not make it available for deployment.

**Comment by subhadippramanik** [comment]
Hello Kaizi,
thanks for your reply..and it's working now..
Nice work by the team..

Happy coding

**Comment by HuyKhac** [comment]
Hi all,

I got the same issue that a distribution is incomplete and it does not show off on Deployment Management page
![Screenshot from 2023-08-13 09-26-50](https://github.com/eclipse/hawkbit/assets/25993438/330d1d49-c014-4301-9f64-f41255c7ff27)

I created a (OS with apps) distribution  and a (OS) software module.
Can anybody help to troubleshoot this case?

Thank you,
Huy

**Comment by JelenaSehovac** [comment]
Drag the created software module into the created distribution in order to link them in 'Distributions Management' window. After that the distribution set is 'complete' and will be visible on Deployment page.

**Comment by HuyOptisigns** [comment]
I could make it works. Thanks JelenaSehovac!
