### ISSUE TITLE
Not able to use different Download URLs for each artifact

### ISSUE THREAD

**Issue by IagoFelipeTrentin** [eclipse/hawkbit#562]
Hello,

I am not being able to find a way to configure different URLs for each artifact.
I found the answer for Issue https://github.com/eclipse/hawkbit/issues/173, but it is not exactly what I need.

How can I send an update request with different URLs for **each** artifact ?
Or does HawBit server can only use one pre-defined URL (explained in https://github.com/eclipse/hawkbit/issues/173) for all artifacts ?

Thank you!

**Comment by michahirsch** [comment]
HI @IagoFelipeTrentin,

sorry for the late response. Somehow your issue slipt through.

hawkBit generates URLs based on a pattern you can configure as you found in the issue #173. Due the pattern contains also placeholders the generated URLs can also contain artifact specific information like `artifactFileName`, `artifactSHA1`, `artifactId`,....

The configured default `{protocol}://{hostnameRequest}:{portRequest}/{tenant}/controller/v1/{controllerId}/softwaremodules/{softwareModuleId}/artifacts/{artifactFileName}` uses the name of the artifact to generate into the download URL.

So you get different download URLs for the name of the artifact within a software module.

If all the placeholders and configureable download URL pattern is still not sufficient you can actually implement an own strategy within hawkBit by implementing the interface `ArtifactUrlHandler` do generate download URLs.

Hope this helps,
Cheers
Michael
