### ISSUE TITLE
Incorrect total size in GET /rest/v1/distributionsettags

### ISSUE THREAD

**Issue by Sarah1024** [eclipse/hawkbit#564]
Hi, 

I was trying the DistributionSetTags APIs with the sandbox https://hawkbit.eu-gb.mybluemix.net/UI/. It seems there is a bug in `GET /rest/v1/distributionsettags`:

The total number of entries is incorrect. The API is returning the total number of target tags instead of the total number of distribution set tags. (I tried to create more distribution set tags, the `total` field is still the same old value. But when I create more target tags, the value is updated. )

Thanks,
Sarah

**Comment by kaizimmerm** [comment]
I tried to reproduce this (even on the sandbox) but it always seems to work as expected. I will close the issue for know. Please let us know if you can still reproduce that and how.
