### ISSUE TITLE
Error when starting hawkbit-mgmt-simulator

### ISSUE THREAD

**Issue by komab** [eclipse/hawkbit#570]
Hi,
I'm following the steps outlined here
https://github.com/eclipse/hawkbit/tree/master/examples/hawkbit-example-mgmt-simulator

When I run 
$ java -jar hawkbit-example-mgmt-simulator-#version#-exec.jar
I end up with this error
```
Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
.................
Caused by: feign.FeignException: status 409 reading MgmtTargetTagClientResource#createTargetTags(List); content:
{"exceptionClass":"org.eclipse.hawkbit.repository.exception.EntityAlreadyExistsException","errorCode":"hawkbit.server.error.repo.entitiyAlreayExists","message":"The given entity already exists in database"}

```
Note: I'm successfully able to launch the update server and device simulator.

**Comment by ShravanReddy80** [comment]
Every time we run this command, entries are created in the hawkbit tables. I think you have run the command more than once without cleaning the tables.
