### ISSUE TITLE
Promote Gitter?

### ISSUE THREAD

**Issue by kartben** [eclipse/hawkbit#576]
I might be looking in the wrong place, but I learnt just today that the project team is using Gitter as kind of the main communication channel for questions etc. This is ok (although eclipse.org mailing list or forum would be preferred, I guess), but I wonder if this is even advertised somewhere? How are people supposed to know about the existence of the Gitter channel? Would be nice to promote it in the README? Probably also on the project's homepage?
FWIW if people look at the current official channel, which I believe is hawkbit-dev mailing list, they might have the wrong impression that the project is not as active as Gitter seems to show.

**Comment by michahirsch** [comment]
hey @kartben 

there are actually references to the gitter-chat on the hawkBits readme (check the `chat on gitter` label at the `Contact Us` header and also on the project page: http://www.eclipse.org/hawkbit/ at the bottom.

Unfortunately gitter doesn't offer some kind of statistic, would I love to see and show activties on the gitter-channel and make it more transparent. 

But I do get your point that there are not a lot of activities on the mailing-list.

**Comment by schabdo** [comment]
Hi Benjamin,

We placed the Gitter badge more prominent on the new [project homepage](https://eclipse.org/hawkbit), 
[landing page](https://github.com/eclipse/hawkbit) at GitHub and on the [community section](http://www.eclipse.org/hawkbit/community) as well.

Hope this helps to promote the use of Gitter.
