### ISSUE TITLE
distribution not loading on deployment page

### ISSUE THREAD

**Issue by aapurohit** [eclipse/hawkbit#579]
I am working with hawkbit update server with management UI and DDI API. The server is running on the local server of my machine.
The problem is after creating a distribution on distribution management page, the distribution is not available on deployment page. Below are the snapshots

![image](https://user-images.githubusercontent.com/31535768/30628810-260c2742-9df6-11e7-8c7b-9164d7d019a3.png)

![image](https://user-images.githubusercontent.com/31535768/30628830-4907f6e0-9df6-11e7-9c81-621c0d58899d.png)

Any help on this problem would be appreciated. I went through the documentation and was unable to find a solution.

**Comment by michahirsch** [comment]
Hi @aapurohit,

unfortunately I think there is missing a point in the documentation. 

A distribution-set is based on a distribution-set-type which defines which software-module-types needs to be included in the distribution-set before it's `complete` and can be rolled out. This ensures that a specific distribution-set-type has always the necessary software-modules packaged together before using it.

So in your case you used the distribution-set-type  `Os with app(s)` by means you need at least a software-module assigned to this distribution-set of an software-module-type `os`. I can see in your screenshot that you assigned an `application`-type to the distribution-set and so the distribution-set is not `complete` to be used and so it's not visible in the deployment view.

In you case you can either create and assign a software-module - based on software-module-type `os` - or creating a new distribution-set-type which desfines e.g. a custom created software-module-type or just the `application` software-module-type.

We need to enhance the documentation for that.
Cheers,
Michael

**Comment by aapurohit** [comment]
Okay thanks, I made it work eventually.
But good to know the reason behind it.

**Comment by HuyKhac** [comment]
Hi all, 

I got the same issue that a new distribution set is not loaded on Deployment page.
I create this distribution set:
   Type=OS Only    Name=rpi     Verion=v1
 and this software module:
   Type=OS   Name=rpi       Version=v1
Then I open the Deployment page and do not see distribution set "rpi:v1" there.

Please help how to fix the issue.
Thank you,
Huy
