### ISSUE TITLE
how to remove file size limit on upload artifact

### ISSUE THREAD

**Issue by aapurohit** [eclipse/hawkbit#589]
I am using hawkbit and getting the following error
![image](https://user-images.githubusercontent.com/31535768/31488930-dade930e-af5c-11e7-9c05-22e158daca22.png)

my application even after compression exceeds 1GB.
Why is this limit imposed in the first place?
Is there any work around for it.

Thanks

**Comment by michahirsch** [comment]
Hi @aapurohit 

You can configure the upload-file size limit within the hawkBit properties. E.g. changing the `application.properties` or setting it via environment-variable using the spring-boot external configuration mechanism.

Similiar issue to this you can see here: https://github.com/eclipse/hawkbit/issues/392

**Comment by duclongpl** [comment]
Hi @aapurohit,

You can configure like michahirsch's guide.
Please check file [https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/hawkbit-update-server/src/main/resources/application.properties] , line 39th.
And I saw you are using swupdate, you also should be carefully with maximum size of *.swu that SWupdate can handle. Please check that issue from this link below: [https://groups.google.com/forum/#!msg/swupdate/ABFNVf9hYOo/oyLWi6pTAwAJ]

Regards,
Long.

**Comment by aapurohit** [comment]
thanks a lot for your help..
application.properties change works for me
@duclongpl will check the maximum size of .swu file.

**Comment by kirana1996** [comment]
@aapurohit ,
Stating hawkbit server with docker, can please tell us how to change application.properties and where it is present.
