### ISSUE TITLE
Error while assigning a Distribution to Target

### ISSUE THREAD

**Issue by KrupaRajashekar** [eclipse/hawkbit#591]
Hi,

I have configured Hawkbit to use MariaDB for storage. I am able to create a distribution and assign a software module to it. But when I try to assign this distribution to a target device, it shows error on clicking 'save assign' button and Hawkbit hangs. 
Error: The operation cannot be fulfilled due to SQLException. Please contact administrator. 

Can you please let me know how to resolve this issue? 
![image](https://user-images.githubusercontent.com/32810114/31582750-cc01cc9e-b1a9-11e7-9f94-f2b221a00cce.png)

**Comment by kaizimmerm** [comment]
Could you post the stack trace from your log?
