### ISSUE TITLE
Sign out with hawkBit-UAA

### ISSUE THREAD

**Issue by subhadippramanik** [eclipse/hawkbit#593]
Hello,

I have integrated `hawkBit` with `UAA` using the extension. So far things are going good except the logout. On logout, it sends request to `/UI/logout` and then routes to `/UI/login/#`, which ideally should be `/uaalogin`. 
So far followed exactly what mentioned in the readme from the extension, but no idea how to solve this. Please suggest me how to solve this issue.

Possible solution:
- Make `Sign Out` link configurable via properties in class `org.eclipse.hawkbit.ui.menu.DashboardMenu.java`
- make the below mention code in class `org.eclipse.hawkbit.autoconfigure.security.SecurityManagedConfiguration.UISecurityConfigurationAdapter` configurable via properties
```java
            httpSec
                    // UI
                    .authorizeRequests().antMatchers("/UI/login/**").permitAll().antMatchers("/UI/UIDL/**").permitAll()
                    .anyRequest().authenticated().and()
                    // UI login / logout
                    .exceptionHandling().authenticationEntryPoint(new LoginUrlAuthenticationEntryPoint("/UI/login/#/"))
                    .and().logout().logoutUrl("/UI/logout").logoutSuccessUrl("/UI/login/#/");
```

Problem doing this locally is the code base doesn't compile on eclipse. The module `hawkbit-repository-jpa` fails to compile.
Thanks

**Comment by michahirsch** [comment]
Hi @subhadippramanik

yes I agree. We are still thinking to make the hawkBit security more configurable, maybe even to make it the default optional and users need to define their own security using spring-security for example. So users are able to define the whole management/UI security and authentication by their own. So in that case it would also be possible to define own implementations of login and logout handlers which handle the login and logout process totally different.

But the first step make the login and logout URLs configurable would be a good option, I agree. This would allow to re-direct to the external login (here to the /uaalogin) URL.

We would be happy if you contribute a configuration property and make it configurable if you already have something locally. 

Why the `hawkbit-repository-jpa` - is failing on your side I don't have a glue. The hawkBit master build is building fine. Not sure which local changes causing your build to fail.

Cheers,
Michael

**Comment by subhadippramanik** [comment]
Hi @michahirsch,

I would really enjoy contributing here..

The `hawkbit-repository-jpa` fails because of some classes not found. Here is the list of those classes..

`org.eclipse.hawkbit.repository.jpa.model.JpaActionStatus_`

`org.eclipse.hawkbit.repository.jpa.model.JpaAction_`

`org.eclipse.hawkbit.repository.jpa.model.JpaTarget_`

`org.eclipse.hawkbit.repository.jpa.model.JpaDistributionSetMetadata_`

`org.eclipse.hawkbit.repository.jpa.model.JpaDistributionSet_`

`org.eclipse.hawkbit.repository.jpa.model.JpaRolloutGroup_`

`org.eclipse.hawkbit.repository.jpa.model.JpaRollout_`

`org.eclipse.hawkbit.repository.jpa.model.RolloutTargetGroup_`

`org.eclipse.hawkbit.repository.jpa.model.JpaSoftwareModuleMetadata_`

`org.eclipse.hawkbit.repository.jpa.model.JpaSoftwareModule_`

`org.eclipse.hawkbit.repository.jpa.model.JpaSoftwareModuleType_`

`org.eclipse.hawkbit.repository.jpa.model.JpaDistributionSetTag_`

`org.eclipse.hawkbit.repository.jpa.model.JpaTargetFilterQuery_`

Just had cloned the repository and imported as `maven` project in `eclipse`, no idea where those classes can come from. 

Am I missing any step? Could you guide me?

**Comment by bobrigado** [comment]
@subhadippramanik These are generated classes, found in target/generated-sources/apt. For Eclipse, add this directory as a source path to Build Path.

**Comment by subhadippramanik** [comment]
Awesome.. this solves my problem. Thanks @bobrigado
