### ISSUE TITLE
Scrollbar disappears in "Configure Rollout" dialog

### ISSUE THREAD

**Issue by djfun** [eclipse/hawkbit#594]
When the height of the browser window is too small to display the whole "Configure Rollout" dialog it gets a vertical scrollbar. This works fine under normal circumstances. However when I try to create a new rollout that eg. has a name that already exists or has no targets and I get an error message after clicking on "Save", when I now scroll up and change the name, the scrollbar disappears. I can still navigate to the "Save" button with tab or change the browser height but that is not ideal and not easy to figure out.
![hawkbit_scrollbar_issue](https://user-images.githubusercontent.com/609660/31756509-c15812c8-b4a4-11e7-8dce-b4a54727d0cd.png)

**Comment by kaizimmerm** [comment]
we will look into this. Thanks for the hint.

**Comment by avgustinmm** [comment]
Vaadin 8 UI is discontinued - https://eclipse.dev/hawkbit/blog/2023-11-22-vaadin8_ui_discontinuation/
