### ISSUE TITLE
How to configure Hawkbit to run on https?

### ISSUE THREAD

**Issue by KrupaRajashekar** [eclipse/hawkbit#598]
Hi,

I have hawkbit update server running on http & port 8080. How can I configure it to use https protocol ?

Thanks.

**Comment by michahirsch** [comment]
Hi @KrupaRajashekar 

you should be able to setup HTTPS as described in the spring-boot documentation
https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-configure-ssl

Hope this helps,
Cheers,
Michael

**Comment by KrupaRajashekar** [comment]
Thanks for the quick help ! It worked .

**Comment by michahirsch** [comment]
👍

**Comment by mmseraj** [comment]
Hi,
Has the below document moved since Oct 26, 2017? 
https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-configure-ssl

Thanks,
Maryam

**Comment by laverman** [comment]
Hi @mmseraj,
it seems, they removed the `current` link, which has to be replaced by a certain version. Hawkbit uses spring-boot `1.4.7.RELEASE`. Hence, the link is: 
https://docs.spring.io/spring-boot/docs/1.4.7.RELEASE/reference/html/howto-embedded-servlet-containers.html#howto-configure-ssl

**Comment by huynq0911** [comment]
Hi, after try this solution, I can access to https, but still got the warning:"Connection Is Not Secure".
How to resolve this?

**Comment by schabdo** [comment]
@huynq0911 what kind of certificate do you put in the keystore? If it is a self-signed certificate your browser won't trust it, thus you'll get "Connection Is Not Secure" even if you use `HTTPS`.

**Comment by huynq0911** [comment]
> @huynq0911 what kind of certificate do you put in the keystore? If it is a self-signed certificate your browser won't trust it, thus you'll get "Connection Is Not Secure" even if you use `HTTPS`.

@schabdo  Oh, I got it! Does it mean that I need CA from some provider to secure connection?
I have one more question.  Does the Hawkbit run on an embedded-servlet-containers? If that is, how can I config SSL protocols like Nginx: [/etc/nginx/nginx.conf](https://www.linode.com/docs/web-servers/nginx/enable-tls-on-nginx-for-https-connections/)
```
http {
    ssl_ciphers         EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;
}
```

**Comment by a-sayyed** [comment]
> > @huynq0911 what kind of certificate do you put in the keystore? If it is a self-signed certificate your browser won't trust it, thus you'll get "Connection Is Not Secure" even if you use `HTTPS`.
> 
> @schabdo Oh, I got it! Does it mean that I need CA from some provider to secure connection?
> I have one more question. Does the Hawkbit run on an embedded-servlet-containers? If that is, how can I config SSL protocols like Nginx: [/etc/nginx/nginx.conf](https://www.linode.com/docs/web-servers/nginx/enable-tls-on-nginx-for-https-connections/)
> 
> ```
> http {
>     ssl_ciphers         EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
>     ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
>     ssl_session_cache   shared:SSL:10m;
>     ssl_session_timeout 10m;
> }
> ```

@huynq0911 you can check out https://letsencrypt.org/ for the CA

**Comment by schabdo** [comment]
> Does it mean that I need CA from some provider to secure connection?

Exactly. Otherwise you have to add your self-signed certificate as trusted source to all your peers. Usually this is not really an option so better go for an already trusted CA e.g. `letsencrypt.org`. 
In case you only need it for local development you may have a look at [mkcert](https://github.com/FiloSottile/mkcert). Haven't tried it myself but it's on my list 😄 

Regarding the TLS configuration: hawkBit is shipped with [Jetty](https://www.eclipse.org/jetty/documentation) by default. So you should be able to use standard Spring Boot properties for TLS setup. This should do the trick:  
```
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1,TLSv1.1,TLSv1.2
server.ssl.ciphers=EECDH+AESGCM,EDH+AESGCM,AES256+EECDH,AES256+EDH
```
Haven't tested it myself. Let me know whether or not this is working out for you

**Comment by huynq0911** [comment]
@schabdo : I'm trying to build a trusted CA (it's difficult for me). 
I'm also trying to config TLS as your suggestion, but it seems does not work.
Error [https://i.imgur.com/QDyEDyx.png](Error)

**Comment by schabdo** [comment]
@huynq0911 may I ask you to open a new issue for it? For further investigation please provide detailed SSL handshake output from client side and the steps how you built the certificates.

**Comment by huynq0911** [comment]
> @huynq0911 may I ask you to open a new issue for it? For further investigation please provide detailed SSL handshake output from client side and the steps how you built the certificates.

I have created new issue [here](https://github.com/eclipse/hawkbit/issues/839). Please help me to review  it :)
