### ISSUE TITLE
 Anonymous download authentication works like anonymous authentication

### ISSUE THREAD

**Issue by danielesergio** [eclipse/hawkbit#615]
The "Allow targets to download artifacts without security credentials" option in the "Authentication Configuration" section of the "System Config" page basically enables anonymous authentication and that devices can use any call defined in DDI api with this configuration, not just "download artifacts". 
This is a bug confirmed by @kaizimmerm   on Gitter.

**Comment by kaizimmerm** [comment]
Fixed by #616
