### ISSUE TITLE
Failed to execute goal com.ethlo.persistence.tools:eclipselink-maven-plugin:2.6.4.2:modelgen

### ISSUE THREAD

**Issue by bantibaghel** [eclipse/hawkbit#623]
Hi,
Can we execute 'hawkBit' on Java9.

Thanks!
Banti kumar

**Comment by michahirsch** [comment]
Hi,

hawkBit does currently not support Java9. @schabdo was already testing with Java9 (https://github.com/bsinno/hawkbit/tree/fix_first_preparation_for_jdk9) but there are still some problems. So currently it's not supported, sorry.

Cheers,
Michael

**Comment by schabdo** [comment]
It's not only a HawkBit issue. More or less at least Spring Boot 1.5 is required to fully support Java 9. If you'll take the branch mentioned above you'll be able to build it (without tests) based on JDK 9 - but still source level 8

**Comment by bantibaghel** [comment]
Thanks to reply.
If I skip all tests or execute this command **mvn clean install -DskipTests**, it fails to execute some modules. Please see logs for more clarification. 

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hawkBit :: Repository :: JPA Implementation 0.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ hawkbit-repository-jpa ---
[INFO] Deleting /home/tenwave/hono/hawkbit/hawkbit-repository/hawkbit-repository-jpa/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-no-snapshots) @ hawkbit-repository-jpa ---
[INFO] Skipping Rule Enforcement.
[INFO] 
[INFO] --- eclipselink-maven-plugin:2.6.4.2:modelgen (modelgen) @ hawkbit-repository-jpa ---
[INFO] JPA modelgen: Found 136 source files for potential processing
[INFO] JPA modelgen: Output directory: /home/tenwave/hono/hawkbit/hawkbit-repository/hawkbit-repository-jpa/target/generated-sources/apt
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] hawkBit :: Parent .................................. SUCCESS [  7.028 s]
[INFO] hawkBit :: Core .................................... SUCCESS [  8.164 s]
[INFO] hawkBit :: Core Security ........................... SUCCESS [  2.617 s]
[INFO] hawkBit :: Repository .............................. SUCCESS [  0.064 s]
[INFO] hawkBit :: Repository :: API ....................... SUCCESS [  5.359 s]
[INFO] hawkBit :: Repository :: Core Implementation Support SUCCESS [  1.641 s]
[INFO] hawkBit :: Artifact Repository :: Filesystem ....... SUCCESS [  0.552 s]
[INFO] hawkBit :: Repository :: Test Utilities ............ SUCCESS [  2.760 s]
[INFO] hawkBit :: Repository :: JPA Implementation ........ FAILURE [  4.825 s]
[INFO] hawkBit :: REST Core ............................... SKIPPED
[INFO] hawkBit :: Mgmt REST API ........................... SKIPPED
[INFO] hawkBit :: Security Integration .................... SKIPPED
[INFO] hawkBit :: HTTP Security ........................... SKIPPED
[INFO] hawkBit :: REST Mgmt Resources ..................... SKIPPED
[INFO] hawkBit :: DDI API ................................. SKIPPED
[INFO] hawkBit :: DDI Resources ........................... SKIPPED
[INFO] hawkBit :: DMF ..................................... SKIPPED
[INFO] hawkBit :: DMF :: API .............................. SKIPPED
[INFO] hawkBit :: DMF :: RabbitMq Test module ............. SKIPPED
[INFO] hawkBit :: DMF :: AMQP 0.9 Implementation .......... SKIPPED
[INFO] hawkBit :: Mgmt UI ................................. SKIPPED
[INFO] hawkBit :: Spring Boot Autoconfigure ............... SKIPPED
[INFO] hawkBit :: Test Report ............................. SKIPPED
[INFO] hawkBit :: Spring Boot Starters .................... SKIPPED
[INFO] hawkBit :: Spring Boot Starter DDI API ............. SKIPPED
[INFO] hawkBit :: Spring Boot Starter DMF API ............. SKIPPED
[INFO] hawkBit :: Spring Boot Starter Management API ...... SKIPPED
[INFO] hawkBit :: Spring Boot Starter Management UI ....... SKIPPED
[INFO] hawkBit :: Spring Boot Starter ..................... SKIPPED
[INFO] hawkBit :: Runtime ................................. SKIPPED
[INFO] hawkBit :: Runtime :: Update Server ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.750 s
[INFO] Finished at: 2018-01-18T12:23:32+05:30
[INFO] Final Memory: 94M/286M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.ethlo.persistence.tools:eclipselink-maven-plugin:2.6.4.2:modelgen (modelgen) on project hawkbit-repository-jpa: Execution modelgen of goal com.ethlo.persistence.tools:eclipselink-maven-plugin:2.6.4.2:modelgen failed: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException: javax.xml.bind.JAXBException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hawkbit-repository-jpa

Thanks|
Banti kumar

**Comment by schabdo** [comment]
Are you trying to build the mentioned branch => **fix_first_preparation_for_jdk9**?

```
$ git status
On branch fix_first_preparation_for_jdk9
Your branch is up to date with 'origin/fix_first_preparation_for_jdk9'
```
JAXB and especially `JAXBException` should be in place - have a look [here](https://github.com/bsinno/hawkbit/blob/fix_first_preparation_for_jdk9/hawkbit-repository/hawkbit-repository-jpa/pom.xml#L158)

**Comment by bantibaghel** [comment]
How to resolved the following problem?

[INFO] ------------------------------------------------------------------------
[INFO] Building hawkBit :: Repository :: JPA Implementation 0.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ hawkbit-repository-jpa ---
[INFO] Deleting /home/tenwave/hono/hawkbit/hawkbit-repository/hawkbit-repository-jpa/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-no-snapshots) @ hawkbit-repository-jpa ---
[INFO] Skipping Rule Enforcement.
[INFO] 
[INFO] --- eclipselink-maven-plugin:2.6.4.2:modelgen (modelgen) @ hawkbit-repository-jpa ---
[INFO] JPA modelgen: Found 136 source files for potential processing
[INFO] JPA modelgen: Output directory: /home/tenwave/hono/hawkbit/hawkbit-repository/hawkbit-repository-jpa/target/generated-sources/apt
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] hawkBit :: Parent .................................. SUCCESS [  0.825 s]
[INFO] hawkBit :: Core .................................... SUCCESS [  4.123 s]
[INFO] hawkBit :: Core Security ........................... SUCCESS [  1.707 s]
[INFO] hawkBit :: Repository .............................. SUCCESS [  0.022 s]
[INFO] hawkBit :: Repository :: API ....................... SUCCESS [  2.589 s]
[INFO] hawkBit :: Repository :: Core Implementation Support SUCCESS [  1.937 s]
[INFO] hawkBit :: Artifact Repository :: Filesystem ....... SUCCESS [  1.168 s]
[INFO] hawkBit :: Repository :: Test Utilities ............ SUCCESS [  0.834 s]
[INFO] hawkBit :: Repository :: JPA Implementation ........ FAILURE [  1.310 s]
[INFO] hawkBit :: REST Core ............................... SKIPPED
[INFO] hawkBit :: Mgmt REST API ........................... SKIPPED
[INFO] hawkBit :: Security Integration .................... SKIPPED
[INFO] hawkBit :: HTTP Security ........................... SKIPPED
[INFO] hawkBit :: REST Mgmt Resources ..................... SKIPPED
[INFO] hawkBit :: DDI API ................................. SKIPPED
[INFO] hawkBit :: DDI Resources ........................... SKIPPED
[INFO] hawkBit :: DMF ..................................... SKIPPED
[INFO] hawkBit :: DMF :: API .............................. SKIPPED
[INFO] hawkBit :: DMF :: RabbitMq Test module ............. SKIPPED
[INFO] hawkBit :: DMF :: AMQP 0.9 Implementation .......... SKIPPED
[INFO] hawkBit :: Mgmt UI ................................. SKIPPED
[INFO] hawkBit :: Spring Boot Autoconfigure ............... SKIPPED
[INFO] hawkBit :: Test Report ............................. SKIPPED
[INFO] hawkBit :: Spring Boot Starters .................... SKIPPED
[INFO] hawkBit :: Spring Boot Starter DDI API ............. SKIPPED
[INFO] hawkBit :: Spring Boot Starter DMF API ............. SKIPPED
[INFO] hawkBit :: Spring Boot Starter Management API ...... SKIPPED
[INFO] hawkBit :: Spring Boot Starter Management UI ....... SKIPPED
[INFO] hawkBit :: Spring Boot Starter ..................... SKIPPED
[INFO] hawkBit :: Runtime ................................. SKIPPED
[INFO] hawkBit :: Runtime :: Update Server ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.656 s
[INFO] Finished at: 2018-02-14T17:03:50+05:30
[INFO] Final Memory: 98M/328M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.ethlo.persistence.tools:eclipselink-maven-plugin:2.6.4.2:modelgen (modelgen) on project hawkbit-repository-jpa: Execution modelgen of goal com.ethlo.persistence.tools:eclipselink-maven-plugin:2.6.4.2:modelgen failed: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException: javax.xml.bind.JAXBException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hawkbit-repository-jpa


Please help me asap,
Thanks

**Comment by schabdo** [comment]
Please double-check if `pom.xml` of `/hawkbit-parent/hawkbit-repository/hawkbit-repository-jpa` looks like this one [here](https://github.com/bsinno/hawkbit/blob/fix_first_preparation_for_jdk9/hawkbit-repository/hawkbit-repository-jpa/pom.xml#L158)
