### ISSUE TITLE
DMF API extension to support standard device management protocol

### ISSUE THREAD

**Issue by rameshkhot08** [eclipse/hawkbit#627]
Hi Team,
Standard device management protocol that covers the software update part (TR-069, OMA-DM, LWM2M) is already implemented? if not then there any plan to extend? or do we need to extend it our own?

Is "Delta artifact hosting" feature is exist in current release (0.2.0M4)? any supporting examples

**Comment by kaizimmerm** [comment]
There are no opensoure DMF to DM protocol connectors. There are some commercial ones thought, e.g. https://www.bosch-iot-suite.com/remote-manager/ is DMF compatible and supports most DM standards.

Delta artefact hosting is in current master. You can upload delta files and the client can then select the right one.

**Comment by cars10w** [comment]
Hi @kaizimmerm , regarding Bosch's RM being DMF compatible,  do you have a pointer to a web resource describing this?  Or some information on how to hook up Hawkbit with their remote manager.  That would be very helpful for us.

Thanks a lot in advance.

**Comment by kaizimmerm** [comment]
@cars10w I am not with Bosch anymore but maybe @schabdo or @stefbehl can you help with this.

**Comment by schabdo** [comment]
> do you have a pointer to a web resource describing this

@cars10w afaik this is a commercial integration (cf. [here](https://www.bosch-iot-suite.com/service/bosch-iot-suite-for-software-updates))
