### ISSUE TITLE
Deleted DistributionSet name and version are blocked for ever

### ISSUE THREAD

**Issue by subhadippramanik** [eclipse/hawkbit#629]
Once a distribution set is deleted it doesn't allow to create another set with same name and version..but ideally the system should allow.

The same not true for software module..here it allows to create another software module having same name and version as the deleted one.

**Comment by kaizimmerm** [comment]
Works as designed. The "soft delete" applies of the DS is in use (i.e. assigned to a a target). Otherwise if you would create a new one with same name and version you could later not distinguish which one is applied to which target.
