### ISSUE TITLE
Take advantage of metadata to match target and distribution

### ISSUE THREAD

**Issue by diegorondini** [eclipse/hawkbit#635]
As discussed on gitter here:
https://gitter.im/eclipse/hawkbit?at=5a7dadd718f388e626816623
hawkbit is able to create custom filters for targets based on metadata, and targets matching the filter can be manually associated with a distribution.

It would be nice to use metadata from the distribution and the target to define compatibility between them.
E.g. think a target has a `product_name` and the distribution has metadata defining the compatible products, it would be nice to define rules to allow assignment only of compatible distributions to the targets.

**Comment by kaizimmerm** [comment]
Well, I think the method to do that would by the DS type, i.e. you could configure on a target compatible DS types.
