### ISSUE TITLE
Build Failure on hawkbit-examples

### ISSUE THREAD

**Issue by rakesh-pachawa** [eclipse/hawkbit#636]
Hi. 
I am trying to install hawkbit-examples. 
Checked out the latest code from Git master, followed the steps outlined to build examples.
on mvn clean install, I am running into build failure.
reason: Could not find artifact org.eclipse.hawkbit:hawkbit-dmf-api:jar:0.2.0-SNAPSHOT in vaadin-addons (http://maven.vaadin.com/vaadin-addons) 

I am running mvn in superuser privilege.

Below is the gist of the log.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] hawkBit :: Examples ................................ SUCCESS [ 42.667 s]
[INFO] hawkBit :: Examples :: Custom Theme Example App .... SUCCESS [03:21 min]
[INFO] hawkBit :: Examples :: Device Simulator ............ FAILURE [  6.889 s]
[INFO] hawkBit :: Examples :: Feign Core Client ........... SKIPPED
[INFO] hawkBit :: Examples :: DDI Feign Client ............ SKIPPED
[INFO] hawkBit :: Examples :: Management client API ....... SKIPPED
[INFO] hawkBit :: Examples :: Management feign client simulator SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:54 min
[INFO] Finished at: 2018-02-14T12:56:47-06:00
[INFO] Final Memory: 61M/327M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hawkbit-device-simulator: Could not resolve dependencies for project org.eclipse.hawkbit:hawkbit-device-simulator:jar:0.2.0-SNAPSHOT: Could not find artifact org.eclipse.hawkbit:hawkbit-dmf-api:jar:0.2.0-SNAPSHOT in vaadin-addons (http://maven.vaadin.com/vaadin-addons) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hawkbit-device-simulator

Attached is the complete log.
[hawkbit-examples build failure.log](https://github.com/eclipse/hawkbit/files/1725297/hawkbit-examples.build.failure.log)

Appreciate your help.

Thank you.

**Comment by michahirsch** [comment]
Hi,

the hawkbit core functionality are under the repository https://github.com/eclipse/hawkbit so you would need to build them first cause the SNAPSHOTs builds are not on maven-central, so it cannot be downloaded, only the releases are currently on maven-central available.

So if you checkout the https://github.com/eclipse/hawkbit project and build it locally first you are able to build the hawkbit-examples and hawkbit-extensions as well.

Hope this helps,
Cheers

**Comment by rakesh-pachawa** [comment]
Hi @michahirsch ,

I tried to build Hawkbit from source, I get Spring error and the process just stucks there with out any progress even after couple hours.

Attached is the log.

I am running this on AWS Linux AMI.
8GB Memory.
Java - 1.8 update 161.
Maven - 3.5.2.

Can you let me know where I might be wrong?

Thank you.

Appreciate it.

[Hawkbit error.log](https://github.com/eclipse/hawkbit/files/1772836/Hawkbit.error.log)
