### ISSUE TITLE
[Help] Customize the update process

### ISSUE THREAD

**Issue by sam1022** [eclipse/hawkbit#653]
Hi all, I'm investigating the hawkbit server and I have a question about customizing update process.
Can we set the time to update after downloading? 
i.e: immediately after downloading, at specified time (dd:hh:mm), or after reboot, ...

**Comment by kaizimmerm** [comment]
Take a look at this contribution: https://github.com/eclipse/hawkbit/pull/535 in addition you can provide metadata as part of a software module that can be made visible to the device.
