### ISSUE TITLE
[Help] Update devices concurrently 

### ISSUE THREAD

**Issue by sam1022** [eclipse/hawkbit#654]
Hi all, I found out the lines in source as:
https://github.com/eclipse/hawkbit/blob/master/hawkbit-autoconfigure/src/main/java/org/eclipse/hawkbit/autoconfigure/scheduling/AsyncConfigurerThreadpoolProperties.java

>30    /** 
   31      * Maximum thread pool size for central event executor.
   32      */
   33      private Integer maxthreads = 20; 

Is it mean we can update multi devices concurrently and this is the max parallel update device number?

**Comment by kaizimmerm** [comment]
Nope, has nothing to do with that. You can update in parallel as many as you want.

**Comment by kaizimmerm** [comment]
Nope, has nothing to do with that. You can update in parallel as many as you want.
