### ISSUE TITLE
hawkBit Update Server keeps refreshing

### ISSUE THREAD

**Issue by OmarAberkan** [eclipse/hawkbit#657]
After i pulled to the last version i keep getting this message:

The widgetset in use does not seem to be built for the Vaadin version in use. This might cause strange problems - a  recompile/deploy is strongly recommended.                                                                                                    
 Vaadin version: 7.7.13                                                                                                                                                             
 Widgetset version: 7.7.9

**Comment by kaizimmerm** [comment]
You have to delete the folder 'hawkbit-ui/src/main/resources/VAADIN/widgetsets' and then rebuild.

**Comment by OmarAberkan** [comment]
It worked thanks.
