### ISSUE TITLE
Where are the uploaded images stored?

### ISSUE THREAD

**Issue by OmarAberkan** [eclipse/hawkbit#662]

**Comment by schabdo** [comment]
HawkBit is using the file system by default (storage path `./artifactrepo`). This can be changed via property `org.eclipse.hawkbit.repository.file.path=<your custom path>`.

There are more storage implementations available. Have a look here => https://github.com/eclipse/hawkbit-extensions.

**Comment by OmarAberkan** [comment]
Thanks that's what i needed.

**Comment by schabdo** [comment]
You're welcome! By the way there is also a chat (https://gitter.im/eclipse/hawkbit) where you could ask questions. But GitHub issues are fine as well.
