### ISSUE TITLE
Values aren't deleted in the database

### ISSUE THREAD

**Issue by OmarAberkan** [eclipse/hawkbit#667]
When i use the management api values are only removed on the server, not in the database.

**Comment by schabdo** [comment]
Which "values" are you exactly referring to? There are some parts which are only marked as deleted in the database for consistency reasons over time e.g. when a distribution set was assigned to a target

**Comment by OmarAberkan** [comment]
When i use the management API the response says the module already exists, nothing is shown on the GUI but the fields are still in my mariaDB database.

**Comment by OmarAberkan** [comment]
`{'exceptionClass': 'org.eclipse.hawkbit.repository.exception.EntityAlreadyExistsException', 'errorCode': 'hawkbit.server.error.repo.entitiyAlreayExists', 'message': 'The given entity already exists in database'}`

**Comment by schabdo** [comment]
Yes indeed, that could be possible for a software module as well:

> When a user deletes a Software Module, the update server cannot simply remove all the corresponding data. Because when the Software Module is already assigned to a Distribution Set or was assigned to a Target in the past, the hawkBit server has to make sure that remains a clean and full update history for every target. The history contains all information (e.g. name, version) of the software, which was assigned to a specific Target. Obviously storing the binary data of the artifacts is not necessary for the history purpose.

>The delete process which is performed, when there are historical connections to targets is called SoftDelete. This process marks the Software Module as deleted and removes the artifact, but it won’t delete the meta data, which describes the SoftwareModule and the associated Artifacts. SoftwareModules, which are marked as delete won’t be visible for the user, when he is requesting all SoftwareModules.

_see:_ https://www.eclipse.org/hawkbit/documentation/architecture/datamodel.html

Since yesterday with the latest master the managment API is showing a "deleted" flag in the response if you very for distribution sets or software modules (https://github.com/eclipse/hawkbit/pull/665)

**Comment by OmarAberkan** [comment]
What is your suggestion for my issue?

**Comment by schabdo** [comment]
You can create a new software module with the same name but a different version. So e.g. if your first one was `mySoftwareModule` version `1.0` you could name it `mySoftwareModule` with a version of `1.1`. 

If you want to avoid this scenario were the "old" software module is still kept in DB, you have to delete the distribution set the module is assigned to first. From now on the software module has no dependency to a distribution set and as soon as you delete the software module it is gone on DB level as well. Keep in mind that if distribution set is assigned to a target distribution set will be marked as "deleted" in the DB (like software module in your case)

**Comment by OmarAberkan** [comment]
I still get the same issue. I am deleting in this order: rollouts -> distributions -> artifacts -> software modules. It would be perfect if i could just delete everything except the targets.

**Comment by subhadippramanik** [comment]
@schabdo Agreed that the system should retain the history, but in that case the `Delete` action is misguiding. As a user I expect delete means it's deleted. Make it `Hide` or `Inactivate` or something semantically matching.
