### ISSUE TITLE
How to make device(Raspberry pi or bosch xdk)  register to hawkbit

### ISSUE THREAD

**Issue by xdk-rachel** [eclipse/hawkbit#681]
Hello everyone,

I am new to use hawkbit.
I am trying to make device register to Bosch rollout or local hawkbit. But I don't know how to do that.

Thank you before.

**Comment by laverman** [comment]
Hi @xdk-rachel , 
the easiest way to register your device with your local hawkbit is to use the *Direct Device Integration* (DDI) API, by simply performing a GET to `http://localhost:8080/default/controller/v1/{controllerId}`. This will create a base poll resource (ref: [documentation](https://www.eclipse.org/hawkbit/documentation/interfaces/ddi-api.html)).

**Comment by schabdo** [comment]
... or you use the [Management UI ](https://www.eclipse.org/hawkbit/documentation/interfaces/management-ui.html) to create it manually

**Comment by xdk-rachel** [comment]
@laverman 
Hi,
Thank you very much. But I am still confused about it.
For example, if I want to download to Raspberry Pi, so raspberry pi will send the command :
curl 'https://rollouts-ms.apps.de1.bosch-iot-cloud.com/rest/v1/targets' -i -X POST -H 'Content-Type: application/json;charset=UTF-8' -d '[ {
  "securityToken" : "2345678DGGDGFTDzztgf",
  "address" : "https://192.168.0.1",
  "controllerId" : "123456",
  "name" : "raspberry pi",
  "description" : "test"
} ]'
and then raspberry pi will be registered to hawkbit. Is it right?
or can you give me an example?
Thank you very much.

**Comment by xdk-rachel** [comment]
@schabdo Thank you very much
![screenshot from 2018-05-14 16-59-18](https://user-images.githubusercontent.com/39120159/40005428-3385fb3a-5798-11e8-8d83-bf0944885b92.png)
![screenshot from 2018-05-14 16-59-32](https://user-images.githubusercontent.com/39120159/40005429-33bd8708-5798-11e8-98ab-a8ca5d71c715.png)
If i want to use DMF like fist picture, how can I connect?

**Comment by schabdo** [comment]
Well, there is no open source LWM2M connector for HawkBit I am aware of. The connector shown in your picture is proprietary so I am afraid I can't help you with that. HawkBit only offers [DMF](http://www.eclipse.org/hawkbit/documentation/interfaces/dmf-api.html) as a AMQP based message API

**Comment by xdk-rachel** [comment]
@schabdo Thank you again.
Could you tell me how to send messages through DMF? I read the document that said there is some function like sp.direct.exchange. But how to use that? Do I need to installing anything?

**Comment by laverman** [comment]
The DMF is based on RabbitMQ. Therefore, you need a RabbitMQ running which is connected to your HawkBit instance. This can be easily achieved by using the provided [docker-compose file](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/hawkbit-update-server/docker/docker-compose.yml).  

When I understood you correctly, you want to know _how a client uses the DMF_? A good example for this, is the [hawkbit-device-simulator](https://github.com/eclipse/hawkbit-examples/tree/master/hawkbit-device-simulator), especially the [DMF (amqp)](https://github.com/eclipse/hawkbit-examples/tree/master/hawkbit-device-simulator/src/main/java/org/eclipse/hawkbit/simulator/amqp) part.

**Comment by Blackrose** [comment]
Hi, recently, I noticed the docker image has upgraded.Now I am use '$ curl 'https://ddi-api.host.com/TENANT_ID/controller/v1/CONTROLLER_ID' -i -H 'Accept: application/hal+json'
' command and get the "401 Unauthorized" error message. @schabdo  said need use securityToken value.But the API doesn't have any description.Where can I found the latest document?
https://docs.bosch-iot-rollouts.com/documentation/rest-api/rootcontroller-api-guide.html#_get_tenant_controller_v1_controllerid

**Comment by laverman** [comment]
Hi @Blackrose - the corresponding documentation can be found here [1]. As described, you need to enable direct authentication via security token in the HawkBit settings. Afterwards, you need to provide an Authorization header (e.g. `-H "Authorization: TargetToken 123456"`). 

[1] https://www.eclipse.org/hawkbit/documentation/security/security.html

**Comment by Blackrose** [comment]
@laverman Thanks.I have already communicated with the server.

**Comment by laverman** [comment]
Did I understand you correctly, that your problem is thereby solved?

**Comment by Blackrose** [comment]
@laverman Right. It has been resolved.

**Comment by laverman** [comment]
Hi @kaushalkapadiya, 
if you want to connect your device directly to hawkBit, I'd recommend using the _Direct Device Integration_ (DDI) API (cf. [RESTdocs](https://www.eclipse.org/hawkbit/apis/ddi_api/)). 

To connect your device: 
1. In System Configuration, allow a device to authenticate with a _gateway security token_ (as described [here](https://www.eclipse.org/hawkbit/concepts/authentication/#gateway-security-token-authentication))
2. Let your device perform a HTTP-GET to `http://localhost:8080/default/controller/v1/{controllerId}` with the following header `Authorization: GatewayToken {yourGatewayTokenFromSystemConfiguration}`
3. After performing this request successfully, your device appears in the Management UI of your hawkBit instance.

In addition, I'd like to point you to our website [https://www.eclipse.org/hawkbit/](https://www.eclipse.org/hawkbit/) where you'll find the API documentation among other helpful things 😊

**Comment by kaushalkapadiya** [comment]
thanks, i am able to register the device
can you help me with, how to receive the update in silmulating device from hawkbit using http request from device

**Comment by kaushalkapadiya** [comment]
i tried to make http request using curl like,
curl -u admin:admin 'http://localhost:8080/default/controller/v1/ddiSimulated0' -i -X GET -H 'Accept: application/hal+json;Authorization: GatewayToken 3cbed112ef459f7bad2f5b50e71a437a'

but i am having error,
HTTP/1.1 401 Unauthorized
Date: Fri, 16 Nov 2018 16:44:44 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 0

**Comment by kaushalkapadiya** [comment]
> Hi @kaushalkapadiya,
> if you want to connect your device directly to hawkBit, I'd recommend using the _Direct Device Integration_ (DDI) API (cf. [RESTdocs](https://www.eclipse.org/hawkbit/apis/ddi_api/)).
> 
> To connect your device:
> 
>     1. In System Configuration, allow a device to authenticate with a _gateway security token_ (as described [here](https://www.eclipse.org/hawkbit/concepts/authentication/#gateway-security-token-authentication))
> 
>     2. Let your device perform a HTTP-GET to `http://localhost:8080/default/controller/v1/{controllerId}` with the following header `Authorization: GatewayToken {yourGatewayTokenFromSystemConfiguration}`
> 
>     3. After performing this request successfully, your device appears in the Management UI of your hawkBit instance.
> 
> 
> In addition, I'd like to point you to our website https://www.eclipse.org/hawkbit/ where you'll find the API documentation among other helpful things blush

i tried to make http request using curl like,
curl -u admin:admin 'http://localhost:8080/default/controller/v1/ddiSimulated0' -i -X GET -H 'Accept: application/hal+json;Authorization: GatewayToken 3cbed112ef459f7bad2f5b50e71a437a'

but i am having error,
HTTP/1.1 401 Unauthorized
Date: Fri, 16 Nov 2018 16:44:44 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 0

**Comment by schabdo** [comment]
@poppydhir your issue seems to be related to the use of certificate authentication. So not a general device connectivity issue as discussed here. May I ask you to file a new GitHub issue instead?
