### ISSUE TITLE
UI Authentication via OAuth 2

### ISSUE THREAD

**Issue by matoxp** [eclipse/hawkbit#686]
I'm trying to use OAuth 2.0 in the hawkBit UI via _org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure_. After some fiddling with my `security.oauth2.*` configuration properties I managed to get it almost working: Authentication works fine but the UI finally runs into an exception:

`java.lang.ClassCastException: java.lang.String cannot be cast to org.springframework.security.core.userdetails.UserDetails at org.eclipse.hawkbit.ui.common.UserDetailsFormatter.getCurrentUser(UserDetailsFormatter.java:191)`

Looking at the API docs for org.springframework.security.core.Authentication, getPrincipal **might** return a UserDetails object for **certain** authentication providers. In my case, it just returns a string holding my user name.

Are there any workarounds for this problem or is this possibly a bug in the UserDetailsFormatter?

**Comment by schabdo** [comment]
Great to hear that you got it almost running. It took a while to dig into the OAuth stuff but this should do the trick (without knowing your actual implementation):

```
@Override
public OAuth2Authentication loadAuthentication(final String accessToken) {
        
   OAuth2Request request = ...
   UserPrincipal principal = new UserPrincipal(...);
               
   UsernamePasswordAuthenticationToken token = new 
             UsernamePasswordAuthenticationToken(principal, ...);
                
   return new OAuth2Authentication(request, token);
}
```

**Comment by matoxp** [comment]
By providing my own implementation of UserInfoTokenServices and returning a _UserPrincipal_ from `getPrincipal()`, I came a bit further. However the hawkBit UI stays pretty blank (except for the header, footer and currently-logged-in user display at the top left corner). No exceptions showing up in the console log. My code now looks something like this:

```java
public class MyUserInfoTokenServices extends UserInfoTokenServices
{
    ...
    @Override
    protected Object getPrincipal(Map<String, Object> map) {
        return new UserPrincipal(
                map.get("preferred_username").toString(),
                "*****",
                map.get("first_name").toString(), 
                map.get("last_name").toString(),
                map.get("sub").toString(),
                map.get("email").toString(),
                "DEFAULT",
                PermissionUtils.createAllAuthorityList() // Grant all authorities for now
        );
    }
}
```

Wiring:
```java
    @Autowired
    private ResourceServerProperties sso;

    @Bean
    ResourceServerTokenServices userInfoTokenServices() {
        return new MyUserInfoTokenServices(sso.getUserInfoUri(), sso.getClientId());
    }
```
Any other hints?

**Comment by schabdo** [comment]
Thanks for sharing your implementation! It seems like the user doesn't have any permission so he's not allowed to see anything. Did you set a custom `AuthoritiesExtractor` to your `MyUserInfoTokenServices`? `UserInfoTokenServices` has a default one which is not aware of HakwBit permissions. 

Have a look at `UserInfoTokenServices#extractAuthentication(...)` it's a bit tricky that authorities are not taken from the principal:

```java
private OAuth2Authentication extractAuthentication(Map<String, Object> map) {

   Object principal = getPrincipal(map); 
   List<GrantedAuthority> authorities =
         this.authoritiesExtractor.extractAuthorities(map);
   OAuth2Request request =
         new OAuth2Request(null, this.clientId, null, true, null, null, null, null, null);
    UsernamePasswordAuthenticationToken token = 
         new UsernamePasswordAuthenticationToken(principal, "N/A", authorities);
    token.setDetails(map);

    return new OAuth2Authentication(request, token);
}
```

Hope this will help to get it running.

**Comment by schabdo** [comment]
@matoxp I assume provided hints are working for you, so I close this issue
