### ISSUE TITLE
Management API supports sorting distributionset by "createdAt"

### ISSUE THREAD

**Issue by charlyinalbon** [eclipse/hawkbit#687]
When executing the REST call to the Hawkbit Management API
`rest/v1/distributionsets?sort=createdAt%3ADESC`
I get the following response: 400 Bad Request
```
{
    "exceptionClass": "org.eclipse.hawkbit.rest.exception.SortParameterUnsupportedFieldException",
    "errorCode": "hawkbit.server.error.rest.param.invalidField",
    "message": "The given sort parameter field does not exist"
}
```
However, a similar call succeeds:
`rest/v1/distributionsets?sort=id%3ADESC`
Result is: 200 ok.

P.S: I have also tried `created_at`, `createdat`. Without success.

**Comment by laverman** [comment]
You are right. Unfortunately, HawkBit does not support sorting for all the fields in a response. If you want to know, which fields are supported, have a look here: [DistributionSetFields.java](https://github.com/eclipse/hawkbit/blob/master/hawkbit-core/src/main/java/org/eclipse/hawkbit/repository/DistributionSetFields.java).

If this is a requirement from you, I'd encourage you to consider a contribution, by adding the required fields to the enum. :-)

**Comment by charlyinalbon** [comment]
Wow, fast response! :-)
Thanks for the answer! I will consider to contribute, then.
