### ISSUE TITLE
How to view the detail logs of hawkbit server?

### ISSUE THREAD

**Issue by tonyho** [eclipse/hawkbit#695]
I'm trying to get my device update with hawkbit server, and I need to check the interaction between the hawkbit and my device swupdate, but I can't find the log at /var/log,  the program do not print the "hawkBit Direct Device Integration API" interaction content at console/terminal .

So my question is how can I get the detail logs of  interaction between the client and server ? 
For example, what json content did the swupdate or other client has upload to the server.

**Comment by laverman** [comment]
hi @tonyho 
the quickest way forward would be to adapt the logging level `LOGGING_LEVEL_ROOT=DEBUG` (cf. [docu](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#boot-features-custom-log-levels)).

**Comment by bfederau** [comment]
Hi.
Is it possible to reduce the debug output to the DDI API calls in the log? I mean like logging categories? Or do I have to grep in my log file for the DDI API calls?

**Comment by laverman** [comment]
hi @bfederau 
it is possible to configure the log levels according to your needs. 
To reduce to overall log output, you can set the `root` logging level to `ERROR` by setting the following property in the `application.properties` file: 
```
logging.level.root=ERROR
```

Now, to increase the logging level for DDI, add the following line: 
```
logging.level.org.eclipse.hawkbit.ddi=DEBUG
```
If you need more output, change to `TRACE`. 

Does this help?

**Comment by bfederau** [comment]
Hi @laverman 
Thanks that helps.
But I guess there is no way to get more logs on the web-ui finally. I mean the only thing I see is that a deployment has been failed in the action history on the deployment management page but not why it has failed on the target side.

**Comment by schabdo** [comment]
@bfederau it is up to the client (in this case `swupdate`) to report  intermediate status or detailed reasons why an update has failed. Only the device knows it's actually state so we just show in UI what we got from the device

**Comment by sbabic** [comment]
On 04/09/2018 09:45, Dominic Schabel wrote:
> @bfederau <https://github.com/bfederau> it is up to the client (in this
> case |swupdate|) to report intermediate status or detailed reasons why
> an update has failed. Only the device knows it's actually state so we
> just show in UI what we got from the device

Right - but SWUpdate writes its log to the console or to syslog (only if
syslog is activated). There is a loglevel in SWUpdate, I suggest to set
it at 5 (debug) or to start SWUpdate with the -v (verbose) switch. The
whole DDI is then logged.

Best regards,
Stefano Babic

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by schabdo** [comment]
@sbabic thanks for your support 👍
