### ISSUE TITLE
No hawkbit package(deb, rpm) installer at release

### ISSUE THREAD

**Issue by tonyho** [eclipse/hawkbit#696]
From the guide, to use hawkbit,  we can compile it or use the docker. The former takes long time for mvn to get dependences, whereas, the later is not updated as the master code(I guess) and depends on docker.

If there'er package installer, it would be more convenient to use it.

**Comment by laverman** [comment]
While this may extend the convenience of using hawkBit a bit more, it is currently not planned to go this way.

Regarding the **docker** images: true, there is no `latest` image. However, we provide images for releases as well as milestones.
