### ISSUE TITLE
not able to open url once deployed on aws

### ISSUE THREAD

**Issue by saumilsdk** [eclipse/hawkbit#697]
hello,
i have deployed hawkbit update server container using aws ECS FARGATE. I see the networking -> public IP but not able to open the URL with the given IP and 8080 port. I saw the logs and it says running on port 8080. Also I can see the following profile message " The following profiles are active: amqp" but can't connect using url. Please help

**Comment by laverman** [comment]
Hi @saumilsdk,
I'm afraid, from hawkBit side we can not be of much help on this issue, since it seems to be an AWS-ECS one.

**Comment by saumilsdk** [comment]
hi @laverman 
I am not sure if this problem only I am facing or is it consistent with aws ECS fargate server. Can you please confirm?

**Comment by laverman** [comment]
Hi @saumilsdk,
If you are able to start the hawkBit container, as confirmed by the logs, the application seems to run fine. However, if you are not able to reach the endpoint, either the ports of the container are not mapped correctly, or the IP may not be available correctly. These are some points I can think of.
Hope that helps.

**Comment by schabdo** [comment]
I'm not a Fargate expert but did you define port 8080 within you task definition? Otherwise it is not reachable from outside your container

**Comment by saumilsdk** [comment]
Yes you guys are right. I found that aws ECS fargate requires public subnets, gateway, security groups to open 8080 to outside world. After adding all network dependencies I am able to make cloudformation script to automatically create all aws infra for hawkbit server to run.
Here is the repo if anyone wants: https://github.com/saumilsdk/hawkbit-aws-cloudformation

**Comment by schabdo** [comment]
Awesome, thanks for the link. Might help the community to run HawkBit on AWS Fargate
