### ISSUE TITLE
Hawkbit multi tenantcy

### ISSUE THREAD

**Issue by kuzuilker** [eclipse/hawkbit#703]
Hello,

Does HawkBit support more than one user or multi tenant?

**Comment by schabdo** [comment]
I’m afraid, hawkBit doesn’t support multi-tenancy neither multi-user out of the box. However you can add more user easily: Have a look at [InMemoryUserPrincipalDetailsManager
](https://github.com/eclipse/hawkbit/blob/master/hawkbit-autoconfigure/src/main/java/org/eclipse/hawkbit/autoconfigure/security/InMemoryUserManagementAutoConfiguration.java#L84)

**Comment by kuzuilker** [comment]
Thank you for reply.
