### ISSUE TITLE
Comparing 2 controller attribute values

### ISSUE THREAD

**Issue by epoch1970** [eclipse/hawkbit#707]
Re: Gitter [July 16, 2018 4:14 PM](https://gitter.im/eclipse/hawkbit?at=5b4ca838582aaa630770ca38)
Using a client such as swupdate, it is possible to report attributes: A = "foo" ; B = "bar"
Using Hawkbit UI, the Filter manager works for expressions such as "attributes.A==foo"

This request is to make Filter manager work for expressions such as "attributes.A==attributes.B". Member attributes.B would need to be interpolated to its value.

Rationale: with plug-and-play registration, controller ID is derived from runtime information like serial numbers. 
When a new controller appears in the UI, when an old controller gets overdue, it is not easy to see whether the new controller is one more unit, or if it is an existing unit that was somehow altered.
Comparing attributes that represent "registered" values with attributes that represent "live" values could allow tracking the history of the controller.
A filter capable of picking up such changes, "if attributes.RegSN!=attributes.LiveSN", would be useful in the UI. 
Thanks!

**Comment by subhadippramanik** [comment]
Question: The ID with which you register to hawkBit is supposed to be unique and constant. IMO it is the identity of the device. Is in your case device identity gets altered?

**Comment by epoch1970** [comment]
Thanks for your interest.
The identity or nature of the device can change: it is an SBC (Raspberry Pi) and can receive accessories or the block device can be moved to another unit over time.
The Hawkbit ID is hence a combination of various IDs/Serial No’s. 
If the HB ID changes, a new program might need to be loaded, or some other action taken.
Let me know if this is not clear. Thanks again.

**Comment by subhadippramanik** [comment]
Thanks @epoch1970 for explaining the use case. In such scenario I would prefer to have some Id (may be serial number, mac id or some generated id) constant and use that for the whole fleet management.
I can compare this SBC as a mobile device..in case of mobile devices, the serial number, IMEI number are not changed in any condition..you may have multiple accessories or spares used or exchanged, but these numbers are not changed. These are the numbers used for registration as well.
Is it possible in your case to have certain fixed identity?

**Comment by epoch1970** [comment]
If the use case is valid, I will gladly adapt to the generic case. I don’t see how generating a device ID and storing it (in uboot env) would be a problem for me.
I think I chose to tie the ID to the current (changing) hw serial numbers only to make sure the device would  “pop up” on the HB GUI in case of hardware change. A custom filter would do that better I think, if comparing values becomes possible.

**Comment by subhadippramanik** [comment]
Well I had a similar use case where the Id is generated. I store that in an overlay file system so that during os update the id is persisted and available on both (active and inactive) partitions.

**Comment by strailov** [comment]
This looks like to be a non-common used feature and seems to be outdated
