### ISSUE TITLE
Allow targets to download artifacts without security credentials - not working

### ISSUE THREAD

**Issue by subhadippramanik** [eclipse/hawkbit#723]
hawkBit update server doesn't respect `Allow targets to download artifacts without security credentials`.
On version `0.2.1` 
- enabled the option from UI
- Saved
- moved to other page and came back to system configuration
Observation: the option is disabled

Used Mgmt API to set it
Request
```
PUT http://localhost:8080/rest/v1/system/configs/anonymous.download.enabled
BODY 
{
	"value": true
}
```
Response
```
{
    "value": true,
    "lastModifiedAt": 1534780418827,
    "lastModifiedBy": "admin",
    "createdAt": 1534780418827,
    "createdBy": "admin",
    "global": false,
    "_links": {
        "self": {
            "href": "http://localhost:8080/rest/v1/system/configs/anonymous.download.enabled"
        }
    }
}
```
Observation:
DDI Error `401`on `http://localhost:8080/default/controller/v1/my-device`

**Comment by schabdo** [comment]
Supplementing what @laverman already pointed out: The setting is only referring to the download of an artifact. If you'll try `/<yourControllerId>/softwaremodules/<yourSwId>/artifacts/....` instead, access should be granted without credentials

**Comment by subhadippramanik** [comment]
Thanks @laverman and @schabdo for clarifying this.
