### ISSUE TITLE
Rollout completes right after adding it

### ISSUE THREAD

**Issue by m2sillanpaa** [eclipse/hawkbit#735]
I'm new to hawkbit. And I'm trying to get it working with SWupdate.

I had rollout running for one device. It got 401 error (I've already changed the hawkbit.server.ddi.security.authentication.anonymous.enabled=true in application.properties) so tried another filter. I made another rollout with same target, distribution set and just different filter. And it changed its status right away to done even without the device running the update.

**Comment by schabdo** [comment]
Can you double check if there is already an assignment of this distribution set pending in the deployment view? Sounds like the distribution set is already installed on the device or there is a pending update. In this case there is nothing to do for the rollout thus it finish immediately.

May I ask you to provide a screenshot of the group view from the rollout?

**Comment by m2sillanpaa** [comment]
![capture](https://user-images.githubusercontent.com/16754008/45020426-9a1bc080-b037-11e8-8911-a96e72f8198a.png)

**Comment by m2sillanpaa** [comment]
The device with suricatta daemon/SWupdate has no network connectivity in case where the rollout completes.

**Comment by schabdo** [comment]
Thanks for the screenshot. Could you click on "AnotherRollout"? Is the group shown in gray color?

**Comment by m2sillanpaa** [comment]
The status bar you mean? It's green. Do you mean the group-1 text? it's same colour as other texts like the "rollout management" -header.

**Comment by schabdo** [comment]
The rollout named "AnotherRollout" so you'll see all the groups. Is there a group shown in gray color?

**Comment by acris5** [comment]
had the same issue after adding and starting rollout using rest api
![Screenshot (24)](https://user-images.githubusercontent.com/34268588/57763523-31c6c800-770a-11e9-997b-1fc10959e9d5.png)
 return request({
      'method': 'POST',
      'uri': app.host + '/rest/v1/softwaremodules',
      'json': true,
      body,
      auth,
      agentOptions
    }, (error, none, softwareModules) => {
      errorHandler(error, softwareModules)
      const softwareModuleId = softwareModules[0].id
      console.log(blue('Adding files...'))
      return readdir(resolvedPath, (error, files) => {
        errorHandler(error, files)
        const recursive = () => {
          const filename = files.shift()
          console.log(blue('File'), filename)
          console.log(blue('Uploading...'))
          const value = readFileSync(resolve(path, filename))
          const sha1sum = createHash('sha1').update(value).digest('hex')
          return request({
            'method': 'POST',
            'uri': app.host + `/rest/v1/softwaremodules/${softwareModuleId}/artifacts`,
            'json': true,
            'formData': {
              'file': {
                value,
                'options': {
                  filename
                }
              },
              sha1sum
            },
            auth,
            agentOptions
          }, (error, none, body) => {
            errorHandler(error, body)
            if (files.length === 0) {
              return next()
            }
            return recursive()
          })
        }
        const next = () => {
          console.log(blue('Adding distribution set...'))
          return request({
            'method': 'POST',
            'uri': app.host + '/rest/v1/distributionsets',
            'json': true,
            body,
            auth,
            agentOptions
          }, (error, none, distributionSets) => {
            errorHandler(error, distributionSets)
            const distributionSetId = distributionSets[0].id
            console.log(blue('Linking software module to distribution set...'))
            return request({
              'method': 'POST',
              'uri': app.host + `/rest/v1/distributionsets/${distributionSetId}/assignedSM`,
              'json': true,
              'body': [{
                'id': softwareModuleId
              }],
              auth,
              agentOptions
            }, (error, none, body) => {
              errorHandler(error, body)
              console.log(blue('Adding rollout...'))
              return request({
                'method': 'POST',
                'uri': app.host + '/rest/v1/rollouts',
                'json': true,
                'body': {
                  name,
                  distributionSetId,
                  'targetFilterQuery': 'id==testupdate*',
                  'amountGroups': 1
                },
                auth,
                agentOptions
              }, (error, none, rollout) => {
                errorHandler(error, rollout)
                const rolloutId = rollout.id
                console.log(blue('Waiting rollout...'))
                const next = () => {
                  console.log(blue('Starting rollout...'))
                  return request({
                    'method': 'POST',
                    'uri': app.host + `/rest/v1/rollouts/${rolloutId}/start`,
                    'json': true,
                    auth,
                    agentOptions
                  }, (error, none, body) => {
                    errorHandler(error, body)
                    console.log(green('The given update was posted successfully'))
                    done()
                  })
                }
                const pooling = setInterval(() => request({
                  'uri': app.host + `/rest/v1/rollouts/${rolloutId}/`,
                  'json': true,
                  auth,
                  agentOptions
                }, (error, none, body) => {
                  errorHandler(error, body)
                  if (body.status === 'ready') {
                    clearInterval(pooling)
                    return next()
                  }
                }), 2e3)
              })
            })
          })
        }
        return recursive()
      })
    })

**Comment by acris5** [comment]
it there any opportunity to make soft rollouts throught rest api? the problem was because my code made two same forse rollout requests at a time

**Comment by schabdo** [comment]
Yes indeed, just add `"type": "soft"` on top-level of the request body e.g.:

```json
{
  "distributionSetId" : 1,
  "type": "soft",
  "targetFilterQuery" : "id==*",
  .....
}
``` 
I'm sorry that this parameter is not mentioned in the docs. I filed issue https://github.com/eclipse/hawkbit/issues/843 to fix this. Meanwhile have a look [here](https://github.com/eclipse/hawkbit/blob/master/hawkbit-rest/hawkbit-mgmt-api/src/main/java/org/eclipse/hawkbit/mgmt/json/model/distributionset/MgmtActionType.java#L21) for all available types.
