### ISSUE TITLE
Controller file upload

### ISSUE THREAD

**Issue by epoch1970** [eclipse/hawkbit#742]
Original gitter thread [here](https://gitter.im/eclipse/hawkbit?at=5ba38586f4bd1056ac8e4458)

A feature by which an HB server could request a device to upload data back to the server. The device could refuse or comply, downloading and executing a payload capable of capturing the requested data. Upon completion, the device would send the data back to the HB server.
 
Use cases:

1. store locally generated data, such as user preferences, to allow complete reinstall (OS+apps+prefs) of a device in case of disaster.
2. receive logfiles from a device, allowing for remote troubleshooting.

The data would be stored in the HawkBit database and available to the HB GUI operator.

Case 1: the uploaded data could be ciphered. Data could be downloaded again _as-is_ to the same device (e.g. disaster recovery scenario) or possibly to other devices (e.g. adding new devices to a site, with site-wide presets taken from an existing device)

Thanks again for a great project.

**Comment by schabdo** [comment]
Thanks for raising this issue. Indeed hawkBit already has device authentication and a file store so it would make totally sense if devices could upload certain type of files in a separate space for e.g. troubleshooting

**Comment by strailov** [comment]
This seems not to be related to Software Update scenario, it does not match the use cases of hawkBit . 
Seems to be more related to a Device Management scenario.
