### ISSUE TITLE
CBOR format for DDI

### ISSUE THREAD

**Issue by zubairhamed** [eclipse/hawkbit#748]
Hi,

For small devices (e.g. M4 and less), its advantageous to send, receive and parse data in CBOR format instead of JSON. http://cbor.io/

HTTPS/TLS + Headers etc already puts a burden on a device where free RAM could be around 128KB or much less. CBOR allows a much smaller payload and an easier way of parsing DDI frames instead of requiring wasteful JSON libraries and unnecessary characters and whitespace in the payload.

**Comment by schabdo** [comment]
There is even a [CBOR Jackson extension](https://github.com/FasterXML/jackson-dataformats-binary/tree/master/cbor) available. Sounds pretty cool!

**Comment by zubairhamed** [comment]
Yep i noticed that too! I think it would be cool to have the DDI API be extended to various format matching various device target classes
