### ISSUE TITLE
"java.lang.OutOfMemoryError: Java heap space" for RabbitMQ connection.

### ISSUE THREAD

**Issue by BenniPlejd** [eclipse/hawkbit#751]
Hello!

The company I'm working for is setting up an Hawkbit Update Server (version 0.2.3) instance in our AWS cloud environment. However, whenever the instance tries to connect to an RabbitMQ instance we've setup we get the following error in our Hawkbit server's logs:
> 2018-10-11 09:20:34.875  INFO 24 --- [cTaskExecutor-1] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [\<ELB-ENVIRONMENT\>.eu-west-1.elasticbeanstalk.com:5672]
> 2018-10-11 09:20:35.557 ERROR 24 --- [0.5.106.35:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured
> 
> **java.lang.OutOfMemoryError: Java heap space**
> 	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:112)
> 	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
> 	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:571)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 2018-10-11 09:20:36.080 ERROR 24 --- [.5.105.165:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured
> 
> **java.lang.OutOfMemoryError: Java heap space**
> 	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:112)
> 	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
> 	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:571)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 2018-10-11 09:20:36.090 ERROR 24 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Failed to check/redeclare auto-delete queue(s).
> 
> org.springframework.amqp.AmqpIOException: java.io.IOException
> 	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:71)
> 	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:376)
> 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:573)
> 	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1436)
> 	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1417)
> 	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1393)
> 	at org.springframework.amqp.rabbit.core.RabbitAdmin.getQueueProperties(RabbitAdmin.java:336)
> 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.redeclareElementsIfNecessary(SimpleMessageListenerContainer.java:1209)
> 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1470)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.io.IOException: null
> 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:105)
> 	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:101)
> 	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:353)
> 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:909)
> 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:859)
> 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:799)
> 	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:356)
> 	... 8 common frames omitted
> Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
> 	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
> 	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
> 	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:372)
> 	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:297)
> 	... 12 common frames omitted
> Caused by: java.lang.OutOfMemoryError: Java heap space
> 	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:112)
> 	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
> 	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:571)
> 	... 1 common frames omitted

Both the Hawkbit Update Server and the RabbitMQ environments are AWS Elastic Beanstalk applications running through a Docker Solution Stack.

The Hawkbit Update Server application is initialized through the following command (in a start script called from our Dockerfile):
> java -jar hawkbit-update-server.jar **-Xms1024m -Xmx1024m** -XX:MaxMetaspaceSize=250m -XX:MetaspaceSize=250m -Xss300K -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError --spring.profiles.active=mysql --spring.jpa.database=MYSQL --spring.datasource.url=jdbc:$SPRING_DATASOURCE_URL --spring.datasource.username=$SPRING_DATASOURCE_USERNAME --spring.datasource.password=$SPRING_DATASOURCE_PASSWORD --spring.datasource.driverClassName=org.mariadb.jdbc.Driver --hawkbit.device.simulator.amqp.enabled=false --security.user.name=$SECURITY_USER_NAME --security.user.password=$SECURITY_USER_PASSWORD --spring.rabbitmq.host=$RABBITMQ_HOST --spring.rabbitmq.port=$RABBITMQ_PORT --spring.rabbitmq.username=$RABBITMQ_USERNAME --spring.rabbitmq.password=$RABBITMQ_PASSWORD

We've verified that the RabbitMQ endpoint on port 5672 is accessible from Hawkbits EC2 instance.

If we set don't specify the RabbitMQ settings (i.e. it falls back to localhost:5672) then the Hawkbit Update Server starts to work, although it seems that it continously trying to connect to the non-existent RabbitMQ connection causes a memory leak that crashes the application after a couple of days.

I'm a bit unsure why the Heap memory issue occurs, since it seems that 1 GB of heap memory should be more than enough for the RabbitMQ connection.

Thanks in advance!

**Comment by schabdo** [comment]
Hi Benjamin,

indeed 1 GB is more than sufficient. Do you have a heap dump in order to see (or at least a pointer) who is occupying all the memory? In the meanwhile in case you don't need DMF you could disable the connection attempts to RabbitMQ by setting property `hawkbit.dmf.rabbitmq.enabled=false`
