### ISSUE TITLE
Update of changes in the GUI

### ISSUE THREAD

**Issue by lnetwalker** [eclipse/hawkbit#753]
Hi all,

we want to use a hawkbit cluster and noticed that changes made over the DMF API or in the GUI are not automatically propagated to the other GUI instances. The changes are only visible if you do a reload in the GUI.
Is this the intended behaviour or do we have an error in our setup?

It would be very helpful if anybody could shed a light on how it is supposed to be.

Thanks you
Hartmut

**Comment by schabdo** [comment]
Hi Hartmut,

A browser refresh shouldn't be required to get latest changes. So it's definitely not intended. The reason why a reload is working properly is that fresh data is loaded from the database. It seems that events are not propagated from one node to the other within your cluster.
