### ISSUE TITLE
Monitoring HawkBit internals

### ISSUE THREAD

**Issue by lnetwalker** [eclipse/hawkbit#762]
Hi All,

we want to include some metrics from HawkBit in our standard monitoring solution Check_MK.
Currently we want to monitor the following values:
* Number of Targets total/online/offline
* Number of Targets in different states (In-Sync/Pending/Error/Registered/Unknown)
* Number of Deployment Sets 
* Number of Rollouts 

What would you propose to reach our goals ?
Is there currently an API available to get those values ?

Thanks for your hints

**Comment by schabdo** [comment]
Hi Hartmut,

> Is there currently an API available to get those values ?

Unfortunately there is no API available today that fulfills your needs. However some basic metrics e.g. memory and GC are already in place. You can have a look at `http://localhost:8080/metrics` what's already exposed. This endpoint is secured by default, for testing you could easily disable it by setting property `endpoints.sensitive=false` into `application.properties`.


> What would you propose to reach our goals ?

I would enhance the metrics endpoint mentioned above by your own custom metrics e.g. as you listed: "Number of Deployment Sets" and so on and so forth. There is an extension point available so you're able to show basically any kind of data at `/metrics`. For details have a look [here](https://docs.spring.io/spring-boot/docs/1.4.x/reference/html/production-ready-metrics.html#production-ready-recording-metrics).

Keep in mind that this extension point will be slidely different in near future as soon as we finished migration to Spring Boot 2.x. They changed the way of collecting and exposing metrics => see [here].(https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html#production-ready-recording-metrics)    

Hope this helps!
