### ISSUE TITLE
Create simulating device and get update from hawkbit

### ISSUE THREAD

**Issue by kaushalkapadiya** [eclipse/hawkbit#766]
I am creating a simulating device and i want to connect it to the hawkbit using http and i wanted to receive a file from hawkbit in simulating device using http, i am able to register a simulating device but i don't know how to receive a file from hawkbit in that simulating device.

**Comment by Sdcxv** [comment]
Try to overwrite this two properties.
```
hawkbit.artifact.url.protocols.download-http.hostname=[Your Hostname]
hawkbit.artifact.url.protocols.download-http.ip=[Your IP]
```
And start the server in this format.
```
java -jar hawkbit-update-server.jar --spring.config.location=path/to/your/properties
```

**Comment by kaushalkapadiya** [comment]
i tried to make http request using curl like,
curl -u admin:admin 'http://localhost:8080/default/controller/v1/ddiSimulated0' -i -X GET -H 'Accept: application/hal+json;Authorization: GatewayToken 3cbed112ef459f7bad2f5b50e71a437a'

but i am having error,
HTTP/1.1 401 Unauthorized
Date: Fri, 16 Nov 2018 16:44:44 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 0

i tried to put target token also then also but i am having same error,
 can you help me with this?

**Comment by laverman** [comment]
@kaushalkapadiya when providing the `GatewayToken` within the header, you can omit the `-u ` option.

**Comment by schabdo** [comment]
Indeed, I think the use of basic auth (`-u` option) is the reason for the HTTP 401 response
