### ISSUE TITLE
Will it work on Dynamic IP Address Device Enabled Connectivity ???

### ISSUE THREAD

**Issue by jaikeshsinghgithub** [eclipse/hawkbit#774]
Dear Sir,

We exploring HawkBit on our multiple data collector box (nothing but CPU box ) for patch update frequently , we able to test & upgrade patch on remote data collector box but on static IP only , but once device get registered at start it store IP address , however again next day IP address get change and issue is that any solution for dynamic enables ip devices how it's get registered and work.

Request you to help me in this regard

-Jaikesh Singh

**Comment by schabdo** [comment]
As far as I understood your case the Direct Device Integration API ([DDI](https://www.eclipse.org/hawkbit/apis/ddi_api)) should work. It is poll-based via HTTP/S so the IP address of the client doesn't matter at all. HawkBit is not actively calling the device by it's IP. Even massage based client communication via ([DMF API](https://www.eclipse.org/hawkbit/apis/dmf_api)) doesn't depend on IPs. Hope this helps to clarify your question.

**Comment by jaikeshsinghgithub** [comment]
Thanks for quick response

**Comment by schabdo** [comment]
Welcome! There is also a [community chat](https://gitter.im/eclipse/hawkbit) available for even faster response 😉 May I close this issue?
