### ISSUE TITLE
Mvn clean install failure on core

### ISSUE THREAD

**Issue by Zuendelmeister** [eclipse/hawkbit#778]
Hi all,

I'm trying to install hawkbit on my windows 10 machine. Unfortunately I get a"FAILURE" while the tests are running.

> [INFO]
    -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file C:\Work\Gits\hawkbit\hawkbit-core\target\surefire-reports\2019-01-08T16-23-42_641-jvmRun1.dumpstream
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for hawkBit :: Parent 0.3.0-SNAPSHOT:
[INFO]
[INFO] hawkBit :: Parent .................................. SUCCESS [ 45.841 s]
[INFO] hawkBit :: Core .................................... FAILURE [01:14 min]
[INFO] hawkBit :: Core Security ........................... SKIPPED
[INFO] hawkBit :: Repository .............................. SKIPPED
[INFO] hawkBit :: Repository :: API ....................... SKIPPED
[INFO] hawkBit :: Repository :: Core Implementation Support SKIPPED
[INFO] hawkBit :: Artifact Repository :: Filesystem ....... SKIPPED
[INFO] hawkBit :: Repository :: Test Utilities ............ SKIPPED
[INFO] hawkBit :: Repository :: JPA Implementation ........ SKIPPED
[INFO] hawkBit :: Security Integration .................... SKIPPED
[INFO] hawkBit :: HTTP Security ........................... SKIPPED
[INFO] hawkBit :: DMF ..................................... SKIPPED
[INFO] hawkBit :: DMF :: API .............................. SKIPPED
[INFO] hawkBit :: DMF :: RabbitMq Test module ............. SKIPPED
[INFO] hawkBit :: DMF :: AMQP 0.9 Implementation .......... SKIPPED
[INFO] hawkBit :: Mgmt UI ................................. SKIPPED
[INFO] hawkBit :: REST .................................... SKIPPED
[INFO] hawkBit :: REST :: DDI API ......................... SKIPPED
[INFO] hawkBit :: REST :: Core ............................ SKIPPED
[INFO] hawkBit :: REST :: DDI Resources ................... SKIPPED
[INFO] hawkBit :: REST :: Management API .................. SKIPPED
[INFO] hawkBit :: REST :: Management Resources ............ SKIPPED
[INFO] hawkBit :: Spring Boot Autoconfigure ............... SKIPPED
[INFO] hawkbit :: REST :: Documentation ................... SKIPPED
[INFO] hawkBit :: Test Report ............................. SKIPPED
[INFO] hawkBit :: Spring Boot Starters .................... SKIPPED
[INFO] hawkBit :: Spring Boot Starter DDI API ............. SKIPPED
[INFO] hawkBit :: Spring Boot Starter DMF API ............. SKIPPED
[INFO] hawkBit :: Spring Boot Starter Management API ...... SKIPPED
[INFO] hawkBit :: Spring Boot Starter Management UI ....... SKIPPED
[INFO] hawkBit :: Spring Boot Starter ..................... SKIPPED
[INFO] hawkBit :: Runtime ................................. SKIPPED
[INFO] hawkBit :: Runtime :: Update Server ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:49 min
[INFO] Finished at: 2019-01-08T16:23:44+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project hawkbit-core: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Work\Gits\hawkbit\hawkbit-core\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-11.0.1\bin\java" -javaagent:C:\\Users\\<NAME>\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.2\\org.jacoco.agent-0.8.2-runtime.jar=destfile=C:\\Work\\Gits\\hawkbit\\hawkbit-core\\..\\target\\jacoco-ut.exec,append=true --illegal-access=warn --add-modules=java.xml.bind org.apache.maven.surefire.booter.ForkedBooter C:\Users\<NAME>\AppData\Local\Temp\surefire10108807571442236079 2019-01-08T16-23-42_641-jvmRun1 surefire5842923005274919685tmp surefire_08775833666593776403tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-11.0.1\bin\java" -javaagent:C:\\Users\\<NAME>\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.2\\org.jacoco.agent-0.8.2-runtime.jar=destfile=C:\\Work\\Gits\\hawkbit\\hawkbit-core\\..\\target\\jacoco-ut.exec,append=true --illegal-access=warn --add-modules=java.xml.bind org.apache.maven.surefire.booter.ForkedBooter C:\Users\<NAME>\AppData\Local\Temp\surefire10108807571442236079 2019-01-08T16-23-42_641-jvmRun1 surefire5842923005274919685tmp surefire_08775833666593776403tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hawkbit-core

What did I do wrong?
Thanks!

Best regards,
Zuendelmeister

**Comment by schabdo** [comment]
As far as I can see in the log output you're using JDK 11 to run the tests. Unfortunately this is currently not possible. JDK 11 support is coming soon but we need a newer version of Vaadin to fully support it.

If you're using JDK 8 all tests will pass (see [here](https://github.com/eclipse/hawkbit#runtime-dependencies-and-support))

**Comment by Zuendelmeister** [comment]
And just like this everything works smoothly. Thank you for your fast help!

**Comment by schabdo** [comment]
Welcome! There is also a [chat available](https://gitter.im/eclipse/hawkbit) if you have more questions
