### ISSUE TITLE
Rest API is not working with large file upload

### ISSUE THREAD

**Issue by sachingupta141** [eclipse/hawkbit#779]
Hello,

I am trying hawkbit for quite some time.
By default It doesn't support upload of software artifact of more than 1 GB. So for that I have modified application-properties to make it support upload of more than 1 GB.
Now from UI, I am able to upload file of more than 1 GB size. But from REST API whenever I try to upload, it shows following error:
"java.lang.OutOfMemoryError: Java heap space". 

Here I am not able to understand, what needs to be provided in case of REST API or some code change is required?

**Comment by kaizimmerm** [comment]
It looked into this and it seems that the default Spring MVC MultiPart implementation stores the file in memory. I consider this s bug, hawkBit should not use that implementation.

I will dig a bit further and see what we can do.

**Comment by kaizimmerm** [comment]
It seems that Jetty interprets Springs MultiPart config for file to disk as never instead of always. You can fit this my setting the property `spring.http.multipart.file-size-threshold=1MB` . We will make this the default with 0.3

**Comment by schabdo** [comment]
Fixed by https://github.com/eclipse/hawkbit/pull/721
