### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by schabdo** [eclipse/hawkbit#784]
# Preconditions
- [x] Migrate to Vaadin 8 (https://github.com/eclipse/hawkbit/pull/980)
- [x] Bump Vaadin version to 8.11.x (https://github.com/eclipse/hawkbit/pull/1010)
- [x] Migrate to Spring Boot 2.3.x (https://github.com/eclipse/hawkbit/pull/1018)
- [x] EclipseLink version upgrade will brake SQLServer support (https://github.com/eclipse/hawkbit/issues/1045)

# Release PRE steps
- [x] Check for missing CQs
- [x] Create [project plan](http://www.eclipse.org/projects/handbook/#release)
- [x] Request PMC approval
- [x] Generate IP Log

# Release
- [x] Check that all CQs are completed
- [x] Complete [Release Review](http://www.eclipse.org/projects/handbook/#release)
- [x] Technical Release 0.3.0 on Maven Central
- [x] Update release notes and docker setup

**Comment by zyga** [comment]
Is there a plan to finish 0.3.0 anytime this year?
