### ISSUE TITLE
Management API inteface issue

### ISSUE THREAD

**Issue by khaleelarya** [eclipse/hawkbit#798]
I'm a new-bee to hawk bit, I can able to login to management ui    with http://localhost:8080/UI
But i can't able to login  to management api interface http://localhost:8080/rest/v1.
I have tried with docker as well as building hawkbit  in my pc, but results  are same as below.

> This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Feb 12 15:52:18 GMT 2019
There was an unexpected error (type=Not Found, status=404).
Not Found

can any one help me out.

**Comment by schabdo** [comment]
Glad to hear that your're trying out hawkBit! `http://localhost:8080/rest/v1` is the base URL for the Management API so there is actually no resource. Have a look [here](https://www.eclipse.org/hawkbit/apis/management_api): You'll have to add another resource path e.g. `/targets` or `/distributionsets` to get a valid response instead of a HTTP 404.

So for example a full URL looks like  `http://localhost:8080/rest/v1/targets`. Don't forget to add basic auth to your request.

**Comment by khaleelarya** [comment]
can you please guide me how to add this resource.

**Comment by khaleelarya** [comment]
I'm trying to register my device(imx6) to hawkbit server (which is running in my pc) with below curl command
curl 'http://192.168.1.203:8080/1234/controller/v1/imx6q' -i -X GET -H 'Accept: application/hal+json;Authorization: GatewayToken d412135d7e0970195210746360a448b7'

But in return i'm getting 401 error

> HTTP/1.1 401 Unauthorized
Date: Wed, 13 Feb 2019 09:31:53 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 0

Is this issue related to management api  as i mention above?

**Comment by schabdo** [comment]
Replace `1234` with `DEFAULT`. So URL should look like `http://192.168.1.203:8080/DEFAULT/controller/v1/imx6q`

**Comment by khaleelarya** [comment]
I quickly tried that but unfortunately the result is same
curl 'http://192.168.1.203:8080/default/controller/v1/imx6q' -i -X GET -H 'Accept: application/hal+json;Authorization: GatewayToken f1375b92bfe2fe4a6d76644ca32581e8'

> HTTP/1.1 401 Unauthorized
Date: Wed, 13 Feb 2019 10:27:53 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 0

 will this work with out management api resource?

**Comment by schabdo** [comment]
I think the issue is related to combined headers. You have to separate them into two parameters for curl like `-H 'Accept: application/hal+json'` and `-H 'Authorization: GatewayToken f1375b92bfe2fe4a6d76644ca32581e8'` so curl command looks like: 

```bash
curl -X GET http://192.168.1.203:8080/DEFAULT/controller/v1/imx6q -H 'Authorization: GatewayToken 3b4868b9aec5c44a056020e9680255fe' -H 'Accept: application/hal+json'
```

**Comment by khaleelarya** [comment]
@schabdo 
Thank you
with the help of above command my device can able to connect to hawkbit.

Now im facing some issue when uploading an image into repository

> 2019-02-14 15:23:13.042  INFO 2515 --- [qtp167013780-16] .h.u.a.u.FileTransferHandlerVaadinUpload : Uploading file zImage-phyboard-mira-imx6-3.bin:images:r2
2019-02-14 15:23:13.042  INFO 2515 --- [qtp167013780-16] o.e.h.u.a.u.AbstractFileTransferHandler  : Upload started for file zImage-phyboard-mira-imx6-3.bin:images:r2
2019-02-14 15:23:13.044  INFO 2515 --- [executor-pool-4] o.e.h.u.a.u.AbstractFileTransferHandler  : Transfering file zImage-phyboard-mira-imx6-3.bin directly to repository
2019-02-14 15:23:14.026  INFO 2515 --- [executor-pool-4] o.e.h.u.a.u.AbstractFileTransferHandler  : Upload succeeded for file zImage-phyboard-mira-imx6-3.bin:images:r2
2019-02-14 15:23:14.029  INFO 2515 --- [executor-pool-4] o.e.h.u.a.u.AbstractFileTransferHandler  : Upload finished for file zImage-phyboard-mira-imx6-3.bin:images:r2
2019-02-14 15:23:14.037 ERROR 2515 --- [qtp167013780-18] o.e.h.u.c.HawkbitUIErrorHandler          : Error in UI: 

org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext

**Comment by schabdo** [comment]
You need different credentials for Management API. Default user is `admin` with password `admin` (for reference see [here](https://www.eclipse.org/hawkbit/concepts/authentication))

**Comment by khaleelarya** [comment]
Every time when i stop and restart the hawkbit-update-server, the contents in the hawkbit repository(software modules and distribution sets ) are clearing.
Are there any steps which required for storing all the software modules and distribution sets created?

**Comment by stschake** [comment]
You need to configure an external database, if you are just starting the jar, it will simply use an in-memory database that vanishes when you stop the server. You can use one of the docker-compose examples as a starting point:

https://github.com/eclipse/hawkbit/tree/master/hawkbit-runtime/docker
