### ISSUE TITLE
Upload file software error

### ISSUE THREAD

**Issue by longdangdhv** [eclipse/hawkbit#814]
Hi All, I have issue when i upload file about 1 GB via GUI hawkbit, it's normal
But i post file  about 300MB via API hawkbit use CURL have error: "exception":"java.lang.OutOfMemoryError"
The same error when i use request post of python post file

Please support me, thanks

**Comment by schabdo** [comment]
Which version of hawkBit are you using? I'm asking because in 0.3.0M1 there is a fix for OOM https://github.com/eclipse/hawkbit/issues/779
