### ISSUE TITLE
Migration from 0.2.0M4 to 0.2.0 yields errors

### ISSUE THREAD

**Issue by libussa** [eclipse/hawkbit#826]
Hello,
we have had an update server running for a while on 0.2.0M4.
updated it to 0.2.0, the goal being to migrate all the way to 0.2.5/0.3.0.
Before I could do `curl https://domain.tld/default/controller/v1/<controller_id>` , that returned expected results.
Since the upgrade I get a 401. Did something change?

**Comment by schabdo** [comment]
Not that I'm aware of. Which authentication mechanism are you using? Do you provide either `GatewayToken` or `TargetToken`? Please also double-check if the use of both is enabled within the system config panel

**Comment by libussa** [comment]
I'm not using any authentication at the moment for testing. This is a straight up upgrade, no parmaters changed.
I tried ticking the box "Allow targets to download artifacts without security credentials" but it doen't change anything. For what it's worth, the box is unticked on the old server and everything works (without auth)

**Comment by schabdo** [comment]
> Allow targets to download artifacts without security credentials

This setting is only for anonymous download of files. 

The only way to get access without credentials (or client certificate) I can think of is via setting `hawkbit.server.ddi.security.authentication.anonymous.enabled=true`. But the default is `false` in 0.2.0M4 and 0.2.0. I'm not sure how you managed to get access without providing credentials before

**Comment by libussa** [comment]
Well I'm not exactly sure how it happened, but setting that to true made it work in 0.2.0!
So issue resolved I guess.
