### ISSUE TITLE
Can not config TLS version for hawkbit

### ISSUE THREAD

**Issue by huynq0911** [eclipse/hawkbit#839]
I'm trying to upgrade TLSv1.2 to TLSv1.3 for Hawkbit server. Below is the process I did.
**1. Generate key:**
Follow this guide: [https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html](https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html)
```
------Generating Keys and Certificates with OpenSSL
root@vietkuber:/var/www/hawkbit/hawkbit-runtime/hawkbit-update-server# openssl genrsa -aes128 -out jetty.key
root@vietkuber:/var/www/hawkbit/hawkbit-runtime/hawkbit-update-server# openssl req -new -x509 -newkey rsa:2048 -sha256 -key jetty.key -out jetty.crt

------Loading Keys and Certificates with keytool  into a keystore
root@vietkuber:/var/www/hawkbit/hawkbit-runtime/hawkbit-update-server# keytool -keystore keystore -import -alias jetty -file jetty.crt -trustcacerts
root@vietkuber:/var/www/hawkbit/hawkbit-runtime/hawkbit-update-server# openssl pkcs12 -inkey jetty.key -in jetty.crt -export -out jetty.pkcs12

------Result:
root@vietkuber:/var/www/hawkbit/hawkbit-runtime/hawkbit-update-server# ls
jetty.crt  jetty.key  jetty.pkcs12  keystore  pom.xml  README.md  src  target

```

**2. Hawkbit config:**
/var/www/hawkbit/hawkbit-runtime/hawkbit-update-server/src/main/resources/application.properties
```
# User Security
security.user.name=admin
security.user.password=admin
spring.main.allow-bean-definition-overriding=true

# DDI authentication configuration
hawkbit.server.ddi.security.authentication.anonymous.enabled=true
hawkbit.server.ddi.security.authentication.targettoken.enabled=true
hawkbit.server.ddi.security.authentication.gatewaytoken.enabled=true

# Optional events
hawkbit.server.repository.publish-target-poll-event=false

## Configuration for DMF/RabbitMQ integration
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

hawkbit.artifact.url.protocols.download-http.protocol=https
hawkbit.artifact.url.protocols.download-http.port=8443
security.require-ssl=true
server.use-forward-headers=true 

server.port=8443
server.ssl.key-store=/var/www/hawkbit/hawkbit-runtime/hawkbit-update-server/jetty.pkcs12
server.ssl.key-store-password=12345678
server.ssl.key-password=12345678

server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3
```

**3. Start hawkbit:**
```
root@vietkuber:/var/www/hawkbit/hawkbit-runtime# mvn clean install
root@vietkuber:/var/www/hawkbit/hawkbit-runtime# java -jar /var/www/hawkbit/hawkbit-runtime/hawkbit-update-server/target/hawkbit-update-server-0.3.0-SNAPSHOT.jar

```
**4. Result:**
TLS is still v1.2. What am I missing?
![https://i.imgur.com/FkfQnxV.png](https://i.imgur.com/FkfQnxV.png)

**Comment by huynq0911** [comment]
I think the problems from Java version. Currently, Hawkbit is supported in Java 8, while TLSv1.3 is supported from Java 11. [https://en.wikipedia.org/wiki/Java_version_history](https://en.wikipedia.org/wiki/Java_version_history)
I have tried to upgrade Java to 11 and re-install hawkbit, it failed.

**Comment by schabdo** [comment]
Your browser is showing only current connection details - not all possible connection option offered by the server. Indeed TLSv1.3 is available since [JDK 11](http://openjdk.java.net/jeps/332) and your browser version has to support it as well. In your case it seem that at least [Firefox 63](https://blog.mozilla.org/security/2018/08/13/tls-1-3-published-in-firefox-today) is required.

> I have tried to upgrade Java to 11 and re-install hawkbit, it failed

Due to an old version of Vaadin, hawkBit is not yet able to be compiled based on Java 11 (source level). Instead just try to run an already compiled version on JRE 11.

**Comment by huynq0911** [comment]
@schabdo : Hi, I have successfully to upgrade TLSv1.3 for Hawkbit. I don't know the reason why but I think some component of Hawkbit has been upgraded, it made success. 
The important thing is only to upgrade to Java 11. Below are the steps to do:
1. Upgrade to Java JDK 11 (included JRE)
- Install:
```
sudo  add-apt-repository ppa:linuxuprising/java
sudo apt-get update
sudo apt-get install  oracle-java11-installer
```
- Set alternatives java version:
```
sudo   update-alternatives --config java
```
-> Select /usr/lib/jvm/java-11-oracle/bin/java
```
sudo   update-alternatives --config javac
```
-> Select /usr/lib/jvm/java-11-oracle/bin/javac

2. Re-build and run Hawkbit:
```
mvn clean install
java -jar /var/www/hawkbit/hawkbit-runtime/hawkbit-update-server/target/hawkbit-update-server-0.3.0-SNAPSHOT.jar
```
3. Result
![https://i.imgur.com/CTDhhpp.png](https://i.imgur.com/CTDhhpp.png)
