### ISSUE TITLE
Logging of rollout group status is too verbose

### ISSUE THREAD

**Issue by patrickschlebusch** [eclipse/hawkbit#846]
We're currently seeing a large amount of log messages being generated about the status of our rollouts and after reviewing the logs, the messages don't seem very useful for operating the system.

Here are some example entries I am seeing:
`hawkbit_1   | 2019-05-24 13:42:48.005  INFO 1 --- [executor-pool-1] .StartNextGroupRolloutGroupSuccessAction : No actions to start for next rolloutgroup of parent 1 group-1
hawkbit_1   | 2019-05-24 13:42:48.016  INFO 1 --- [executor-pool-1] o.e.h.r.jpa.JpaRolloutManagement         : Rolloutgroup RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=null, finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-1, getId()=1], finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-2, getId()=2] is finished, starting next group
hawkbit_1   | 2019-05-24 13:42:48.020  INFO 1 --- [executor-pool-1] .StartNextGroupRolloutGroupSuccessAction : No actions to start for next rolloutgroup of parent 2 group-2
hawkbit_1   | 2019-05-24 13:42:48.028  INFO 1 --- [executor-pool-1] o.e.h.r.jpa.JpaRolloutManagement         : Rolloutgroup RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=null, finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-1, getId()=1], finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-2, getId()=2], finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-3, getId()=3] is finished, starting next group
hawkbit_1   | 2019-05-24 13:42:48.032  INFO 1 --- [executor-pool-1] .StartNextGroupRolloutGroupSuccessAction : No actions to start for next rolloutgroup of parent 3 group-3
hawkbit_1   | 2019-05-24 13:42:48.042  INFO 1 --- [executor-pool-1] o.e.h.r.jpa.JpaRolloutManagement         : Rolloutgroup RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=null, finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-1, getId()=1], finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-2, getId()=2], finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-3, getId()=3], finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-4, getId()=4] is finished, starting next group
hawkbit_1   | 2019-05-24 13:42:48.046  INFO 1 --- [executor-pool-1] .StartNextGroupRolloutGroupSuccessAction : No actions to start for next rolloutgroup of parent 4 group-4
hawkbit_1   | 2019-05-24 13:42:48.055  INFO 1 --- [executor-pool-1] o.e.h.r.jpa.JpaRolloutManagement         : Rolloutgroup RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=RolloutGroup [rollout=1, status=RUNNING, rolloutTargetGroup={IndirectList: not instantiated}, parent=null, finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-1, getId()=1], finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-2, getId()=2], finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-3, getId()=3], finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-4, getId()=4], finishCondition=THRESHOLD, finishExp=0, errorCondition=THRESHOLD, errorExp=50, getName()=group-5, getId()=5] is finished, starting next group
hawkbit_1   | 2019-05-24 13:42:48.059  INFO 1 --- [executor-pool-1] .StartNextGroupRolloutGroupSuccessAction : No actions to start for next rolloutgroup of parent 5 group-5`

These messages are written periodically every 2 seconds. The above example shows messages for a single active rollout with 5 rollout groups which are started, but not finished yet. This is a typical situation for our production environment, where we use soft rollouts and see a certain amount of devices per group which might be offline or have automated updates disabled.

I wanted to start a discussion on whether the amount of messages can be reduced or whether those messages should be written with a different log level.

**Comment by schabdo** [comment]
Totally agree, we should definitely reduce the amount of output 👍

**Comment by schabdo** [comment]
Fixed by #847
