### ISSUE TITLE
Redirect escapes TLS termination

### ISSUE THREAD

**Issue by ghost** [eclipse/hawkbit#850]
We run hawkbit and a number of other services behind TLS termination. That way we do not need to consider the specific TLS configuration of each service, but can add TLS to all services in a uniform way. This does not work with hawkbit, unfortunately.

When running hawkbit behind TLS termination, it is problematic that hawkbit redirects requests for `https://<hostname>:<port>/` to `http://<host>:<port>/UI/`. I.e. effectively `https` is replaced by `http` and `UI/` is appended instead of using a relative redirect to `UI` only. Then the browser tries to connect to the HTTPS port using HTTP, which fails, of course.

**Comment by laverman** [comment]
Hi @selobosi
You setup sounds some what similar to our sandbox deployment ([hawkbit.eclipse.org](https://hawkbit.eclipse.org)), where hawkBit runs behind a TLS-termination proxy.

Therefore, we configured `hawkbit.server.security.require-ssl=true` as well as `server.use-forward-headers=true` (cf. [application-cloudsandbox.properties](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/hawkbit-update-server/src/main/resources/application-cloudsandbox.properties)).

Does this solution work in your environment as well?

**Comment by selobosi** [comment]
Thanks, @laverman! Unfortunately, adding these properties did not fix the issue for me. We are still using version 2.5. I will try to upgrade to 3.0.M3 or later and see if the problem persists with that version.

Does you nginx do any rewriting of the Location headers returned by hawkbit to fix the issue?

**Comment by selobosi** [comment]
> Does you nginx do any rewriting of the Location headers returned by hawkbit to fix the issue?

Any update on this?

We also tried with hawkBit 0.3.0-M3 - same problem there. The only difference is that when we go to `https://<host>:<port>/UI/login` directly, we can access the web UI. On 2.5, accessing `https://<host>:<port>/UI/login` redirects to the same location indefinitely.

**Comment by laverman** [comment]
No, our NGINX does not do rewriting. You can see the full (docker-based) setup here: 
[eclipse/hawkbit/master/hawkbit-runtime/.sandbox](https://github.com/eclipse/hawkbit/tree/master/hawkbit-runtime/.sandbox). 

There are two stacks: 
One is running an [Nginx + Let's encrypt](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/.sandbox/stacks/proxy/docker-compose-stack.yml) the other is running the [hawkBit stuff](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/.sandbox/stacks/sandbox/docker-compose-stack.yml). 

And the respective Spring profile configuration can be found here: [application-cloudsandbox.properties ](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/hawkbit-update-server/src/main/resources/application-cloudsandbox.properties).

That's all we do. Would you mind describing where your setup differs?

**Comment by selobosi** [comment]
Thanks for providing those details!

The [Sandbox stack](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/.sandbox/stacks/proxy/docker-compose-stack.yml) uses [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) that has an `HTTPS_METHOD` variable that defaults to `redirect` as mentioned in the [docs](https://github.com/jwilder/nginx-proxy#how-ssl-support-works) and visible in the code in [line 212](https://github.com/jwilder/nginx-proxy/blob/3a9de2d51126b50d20fd6aa01ce6352d246bba5c/nginx.tmpl#L212) and [line 241](https://github.com/jwilder/nginx-proxy/blob/3a9de2d51126b50d20fd6aa01ce6352d246bba5c/nginx.tmpl#L241): the nginx proxy is configured to listen on port 80, too, and redirects all requests to port 443. I.e. there is no URL rewriting, but redirection.

We only open port 8443 for HTTPS and do not need port 80 (or 8080) and hence do not do redirection. I guess that's the difference between our installation and the sandbox.
