### ISSUE TITLE
Custom target filters: basic operator != (not equal) not working with targets with multiple tags

### ISSUE THREAD

**Issue by jdallaglio** [eclipse/hawkbit#870]
While creating custom target filters in the hawkBit sandbox I noticed that if multiple tags are assigned to a target, it doesn't get filtered out as expected.
For example let's say we have two targets in an instance of the sandbox:
- **target1** has tags _test_ and _test1_
- **target2** has tag _test_
Now let's create some custom filters:
- tag=="_test1_" filters only **target1**
- tag=="_test_" filters both **target1** and **target2**
but
- tag!="_test1_" filters bot **target1** and **target2**, while I would expect only **target2** to show up
- tag!="_test_" filters **target1**, while the result should be an empty set

I also would like to mention that if we add other targets with no tags assigned to our sandbox instance, they are not filtered out by the not equal operator. One needs to extend the filter expression as follows
- _expression_ or tag=""
to have the filter include targets with no tags assigned.

Thanks!

**Comment by schabdo** [comment]
Thanks for reporting this. Indeed the `!=` operator seems to be broken in case of multiple tags assigned to a target. I think the SQL statement is not generated correctly:

```sql
SELECT DISTINCT t1.id AS a1, t1.tenant AS a2, t1.address AS a3, t1.controller_id AS a4, t1.created_at AS a5, t1.created_by AS a6, t1.description AS a7, t1.install_date AS a8, t1.last_modified_at AS a9, t1.last_modified_by AS a10, t1.last_target_query AS a11, t1.name AS a12, t1.optlock_revision AS a13, t1.request_controller_attributes AS a14, t1.sec_token AS a15, t1.update_status AS a16, t1.assigned_distribution_set AS a17, t1.installed_distribution_set AS a18 
FROM {sp_target t1 LEFT OUTER JOIN (sp_target_target_tag t2 JOIN sp_target_tag t0 ON (t0.id = t2.tag)) ON (t2.target = t1.id)} 
WHERE (UPPER(t0.name) NOT LIKE ? ESCAPE ? AND (t1.tenant = ?)) 
ORDER BY t1.id ASC LIMIT ? OFFSET ?
```

**Comment by danielesergio** [comment]
It seems that the following cases aren't working (tested in sandbox):
1. tag!="test1" filters bot target1 and target2, while I would expect only target2 to show up
2. tag!="test" filters target1, while the result should be an empty set
