### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by xyklex** [eclipse/hawkbit#878]
Documentation website contains reference to files in an specific user directory.

https://www.eclipse.org/hawkbit/apis/mgmt/targets/

**Comment by laverman** [comment]
Thanks for the quick feedback 👍 . I'm already working on it. Sorry for the inconveniences this is causing. I'll let you know, as soon as this is fixed.

**Comment by laverman** [comment]
@xyklex links are fixed. 👍

**Comment by xyklex** [comment]
@laverman Thank you.
