### ISSUE TITLE
DDI API dowload links not configured for HTTPS 

### ISSUE THREAD

**Issue by YoLieR** [eclipse/hawkbit#879]
Hi,

we currently have the problem that the Hawkbit Direct Device Integration API doesn't generate https links for the `deploymentBase` and `configData`. We run hawkbit behind TLS termination and need Https links in order to reach the deployments from another service.
If we query the DDI API the responses currently look somehow like this:

```
{
  "config": {
    "polling": {
      "sleep": "00:05:00"
    }
  },
  "_links": {
    "deploymentBase": {
      "href": "http://localhost:8080/DEFAULT/controller/v1/edgy01/deploymentBase/1?c=411629670"
    },
    "configData": {
      "href": "http://localhost:8080/DEFAULT/controller/v1/edgy01/configData"
    }
  }
}
```

We configured the Hawkbit Update Manager to generate HTTPS links. We followed the instructions provided in issue #831. 
If we follow the deployementBase link the download-links correctly use https as protocol:

```
"_links": {
              "https": {
                "href": "https://hawkbit.prod.aaiot-cloud.com/DEFAULT/controller/v1/edgy01/softwaremodules/1/artifacts/Azure_cmds.txt"
              },
              "md5sum-http": {
                "href": "https://hawkbit.prod.aaiot-cloud.com/DEFAULT/controller/v1/edgy01/softwaremodules/1/artifacts/Azure_cmds.txt.MD5SUM"
              }
          }
```

How can we configure the Hawkbit DDI API to generate HTTPS links as well?

**Comment by schabdo** [comment]
> How can we configure the Hawkbit DDI API to generate HTTPS links as well?

Sorry for the late reply. I guess you mean instead of `http://localhost:8080` you'd like to have `https://localhost:8080`, right? This is Spring Boot config. We're doing exactly the same with our [sandbox](https://hawkbit.eclipse.org). You'll find the config [here](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/hawkbit-update-server/src/main/resources/application-cloudsandbox.properties). Your proxy just needs to send the correct forwarding headers

**Comment by SijmenHuizenga** [comment]
For any future travelers arriving here through almighty google, let me try to shorten your journey. You need:
```
server.forward-headers-strategy=NATIVE
hawkbit.artifact.url.protocols.download-http.protocol=https
```
If you want to configure the latter using environment variables, use: 
```
SPRING_APPLICATION_JSON="{ \"hawkbit.artifact.url.protocols.download-http.protocol\": \"https\" }"
```
