### ISSUE TITLE
DDI wrong deplyomentBase with double slash

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/hawkbit#892]
Found it in KUKSA; but maybe can be fixed upstream

https://github.com/eclipse/kuksa.invehicle/issues/107

in DDI, when there is an extra slash at the beginning of an URL

```
http://hawkbit:8080//default/controller/v1/kuksa_demodongle
```

deplyomentBase URL returned is wrong (doubled parts):

```
http://hawkbit:8080/default/controller/v1/kuksa_demodongle/default/controller/v1/kuksa_demodongle/deploymentBase/742?c=1095928940
```

I would expect either an explicit error or a correct URL. Tested with latest docker image

**Comment by schabdo** [comment]
Thanks for reporting this. Unfortunately I was not able to reproduce this. Neither locally (docker as well as plain application) nor on hawkBit sandbox. I created a device and assigned a distribution set to it:

```
curl -H "Authorization: TargetToken 8fa9cc289b2d537653d3d599fe9e0d69" https://hawkbit.eclipse.org//default/controller/v1/simulated1
```
```
curl -H "Authorization: TargetToken 8fa9cc289b2d537653d3d599fe9e0d69" https://hawkbit.eclipse.org//default/controller/v1/simulated1/deploymentBase/2
```
I always get `The request was rejected because the URL was not normalized`. I guess that mentioned env variable `HAWKBIT_SERVER=http://a.b.c.d:8080/` is related to Kuksa since hawkBit is using `HAWKBIT_SERVER_URL` as property

**Comment by schabdo** [comment]
Please reach out if you're still able to reproduce this issue. Steps to reproduce would be helpful

**Comment by SebastianSchildt** [comment]
I did some tests, and it looks fine. Until it doesn't 

Baseline test
```docker run -d -p 8080:8080 hawkbit/hawkbit-update-server```

Then

- Create target test in gui
-  Create software module myapp (Application type), upload random file
- Create distribution mydist (Apps only) contaioning the App
- Assign mydist (forced) to dest)
- Settings: Allow targets to authenticate directly with their securty token

When using DDI everything looks fine.

with kuksa-appmamanager: 
```HAWKBIT_SERVER=http://127.0.0.1:8080 HAWKBIT_TENANT=default HAWKBIT_DEVICE=test HAWKBIT_TOKEN=f72b1188974174fac5fc81718b8f9e43  python3 -u -m kuksa.appmanager```

Flow for correct request
```
GET /default/controller/v1/test HTTP/1.1
```
Ok so this ^^ GET is fine
```
Host: 127.0.0.1:8080
User-Agent: python-requests/2.20.0
Accept-Encoding: gzip, deflate
Accept: application/json
Connection: keep-alive
Authorization: TargetToken f72b1188974174fac5fc81718b8f9e43

HTTP/1.1 200 OK
Date: Wed, 27 Nov 2019 17:08:40 GMT
Content-Type: application/json;charset=utf-8
ETag: "08fd809c2148c5db6abdd80b5fd768ea9"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 160

{"config":{"polling":{"sleep":"00:05:00"}},"_links":{"deploymentBase":{"href":"http://127.0.0.1:8080/default/controller/v1/test/deploymentBase/3?c=413446921"}}}GET /default/controller/v1/test/deploymentBase/3 HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: python-requests/2.20.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Authorization: TargetToken f72b1188974174fac5fc81718b8f9e43
```
 etc. etc. Client downloads and is happy.

Now the same creating a wrong request with an extra slash.
If testing with KUKSA appmanager remove the hotfix in line 42 of __main.py__
in kuksa_appmanager

```server=__get_config_value('HAWKBIT_SERVER').rstrip("/")```

becomes

```server=__get_config_value('HAWKBIT_SERVER') ```

and with kuksa-appamanager (if you are not familar with it, it is probably easier to just whip such a request up with python requests)

```HAWKBIT_SERVER=http://127.0.0.1:8080/ HAWKBIT_TENANT=default HAWKBIT_DEVICE=test HAWKBIT_TOKEN=f72b1188974174fac5fc81718b8f9e43  python3 -u -m kuksa.appmanager```

gets a 500 now

```
GET //default/controller/v1/test HTTP/1.1
```
^^Here the client sends a wrong request
```
Host: 127.0.0.1:8080
User-Agent: python-requests/2.20.0
Accept-Encoding: gzip, deflate
Accept: application/json
Connection: keep-alive
Authorization: TargetToken f72b1188974174fac5fc81718b8f9e43

HTTP/1.1 500 Server Error
Content-Type: application/json;charset=utf-8
Connection: close

{"timestamp":"2019-11-27T17:18:38.424+0000","status":500,"error":"Internal Server Error","message":"org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.","path":"//default/controller/v1/test"}
```
It gets a 500 with a clear explanation -> fine.


However this is not what I observed before, so I tried again against a publicly hosted instance (On Azure by Bosch SI, I do not want to share the information here, maybe @eriksven knows what is different)

This happens

```
GET //default/controller/v1/test HTTP/1.1
```
ok, this ^^ is wrong again
```
Host: **REDACTED***:8080
User-Agent: python-requests/2.20.0
Accept-Encoding: gzip, deflate
Accept: application/json
Connection: keep-alive
Authorization: TargetToken b14f4a3052ecc31ec558715f53e0a743
```

But look what happens now, no 500 but:

```
HTTP/1.1 200 OK
Date: Wed, 27 Nov 2019 17:29:02 GMT
X-Application-Context: application:mysql
Content-Type: application/json;charset=UTF-8
ETag: "0b9227a341474bbd3b82bf658c082e00f"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 376

{"config":{"polling":{"sleep":"00:00:30"}},"_links":{"deploymentBase":{"href":"http://**REDACTED***:8080/default/controller/v1/test/default/controller/v1/test/deploymentBase/374?c=756073212"},"configData":{"href":"http://**REDACTED***:8080/default/controller/v1/test/default/controller/v1/test/configData"}}}
```
in this case I do not get the (expected) 500, but a rubbish URI, notice the duplication of `default/controller/v1/test`
```
GET /default/controller/v1/test/default/controller/v1/test/deploymentBase/374 HTTP/1.1
Host: **REDACTED***:8080
User-Agent: python-requests/2.20.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Authorization: TargetToken b14f4a3052ecc31ec558715f53e0a743

HTTP/1.1 404 Not Found
Date: Wed, 27 Nov 2019 17:29:02 GMT
X-Application-Context: application:mysql
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked

{"timestamp":1574875742332,"status":404,"error":"Not Found","message":"Not Found","path":"/default/controller/v1/test/default/controller/v1/test/deploymentBase/374"}
```

Of course this fails. 
The version "should" be the latest stable, but I have no idea how to check the version from the web UI. @eriksven: Can you find out?

If it is a bug that has been fixed, this should be closed, but if it is some weird interference with some load balancers we better find out what is going on.

I do have Wireshark traces.
