### ISSUE TITLE
Provide architectural and technical documentation

### ISSUE THREAD

**Issue by kaizimmerm** [eclipse/hawkbit#90]
We should explain how hawkBit works including:

- Security
- Datamodel
- APIs
- Core functionality and use cases

**Comment by kaizimmerm** [comment]
Started here: https://github.com/eclipse/hawkbit/wiki

Security is still missing though

**Comment by kartben** [comment]
Management API doc links to Bosch SI Rollouts doc

**Comment by kaizimmerm** [comment]
Yes I know. Unfortunately that is the only documentation we have. Those links are better than nothing imho.

**Comment by kaizimmerm** [comment]
https://github.com/eclipse/hawkbit/wiki/Security is now also there. I think the documentation covers everything I wanted to have as part of this issue. However, there of course lots of room for improvement but I guess the wiki has now the critical mass to get started,
