### ISSUE TITLE
i want know this error,

### ISSUE THREAD

**Issue by chscholar** [eclipse/hawkbit#908]
![image](https://user-images.githubusercontent.com/7938994/68263904-2e414780-0082-11ea-8f7a-79851badae4b.png)

in this porject , i build has more error,like this in picture, this class is not static class, why more place to visiste this class private attribute value using class name

**Comment by schabdo** [comment]
Entity classes with suffix "_" will be generated by a maven build run (e.g `mvn clean install`). Location for generated classes will be `/hawkbit-repository-jpa/target/generated-sources/apt` so please make sure this path is considered as additional source location path by your IDE after files were generated.

**Comment by schabdo** [comment]
Please reach out if you need further help. Meanwhile I close this issue
