### ISSUE TITLE
Provide getting started guide

### ISSUE THREAD

**Issue by kaizimmerm** [eclipse/hawkbit#91]
In addition to the README.md we should provide getting started guide in the wiki. Maybe influenced by @michahirsch EclipseCon demo.

**Comment by ddewaele** [comment]
I would also add the minimum dependencies to get up and running (RabbitMQ / CouchDB) to the README.

Lots of people start with the README (That contains the commands to start the components).

**Comment by michahirsch** [comment]
Thanks for the hint @ddewaele, I see that's missing currently so see that the dependent services are missing a little bit in the getting-started guide. It would also helpful to have a kind of docker based getting-started which starts hawkBit and necessary services to play with which covers the issue https://github.com/eclipse/hawkbit/issues/93

**Comment by kaizimmerm** [comment]
Done, README contains lots of hints and we have a docker setup now
