### ISSUE TITLE
"Custom Filter" list doesn't update after creating new filter

### ISSUE THREAD

**Issue by Informatic** [eclipse/hawkbit#916]
Hey, just a quick UI-related bug report.

After creating a new filter on "Target Filters" page, I don't see a newly created filter on "Custom Filter" side of "Deployment" page, unless I refresh the page.

**Comment by schabdo** [comment]
Thanks for filing an issue for that. Indeed custom filters are not displayed at the "Deployment" page right away after they have been created. It seems that the custom filter component is the only part of this page which is not yet push enabled (by means automatically refreshed on entity changes)

**Comment by schabdo** [comment]
Thanks for tackling this bug, highly appreciated! 

@bogdan-bondar may I asked you to have a look at the PR and provide feedback?
