### ISSUE TITLE
Enable https on Hawkbit Update server

### ISSUE THREAD

**Issue by sravya070** [eclipse/hawkbit#948]
Hi,

I am running Hawkbit as docker containers . How can I enable https for this setup ? 

Thanks
Sravya K

**Comment by schabdo** [comment]
We do exactly that for the [hawkBit sandbox](https://hawkbit.eclipse.org) based on Let's encrypt and Nginx. You can have a look at the proxy setup [here](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/.sandbox/stacks/proxy/docker-compose-stack.yml) and the hawkBit related stuff is configured [here](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/.sandbox/stacks/sandbox/docker-compose-stack.yml). Hope this helps to get you started

**Comment by jln-ho** [comment]
Is there a way to configure the hawkbit container to use a JKS keystore? We are running a few other spring boot applications, so our certificate and key management toolchain is heavily leaning towards JKS keystores and we don't want to use an nginx reverse proxy.

What's the easiest way of adding the following configuration options to the container's `application.properties`?

```
server.ssl.key-store=/path/to/keystore.jks
server.ssl.key-store-passsword=password
server.ssl.key-password=key-password
server.ssl.enabled-protocols=TLSv1.2
```

**Comment by schabdo** [comment]
@jln-ho I see, fair enough!

> Is there a way to configure the hawkbit container to use a JKS keystore?

Sure, properties you listed above are applicable in a container setup as well. It's just a bit more tricky to setup 

> What's the easiest way of adding the following configuration options to the container's application.properties

I assume that you're using the pre-built container - so no option to add them directly into `application.properties`, right? Having this said I see only two options: 
* Provide environment variables during startup of container (`docker run -e ....`) 
* Mount a custom `application.properties` file next to the jar-file (cf. [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files))

**Comment by schabdo** [comment]
I assume that you got it working so I close this issue
