### ISSUE TITLE
set artifact download URL 

### ISSUE THREAD

**Issue by ctenruh-phytec** [eclipse/hawkbit#957]
Hi,

I am using hawkBit with a ssl reverse proxy for authentication via certificates.

I saw in one of your older issues  #173  that I need to edit the artifact download properties for it to download the artifact using the correct URL.

Is there any way to set the correct URL without having to edit the properties?

thanks.

**Comment by schabdo** [comment]
Well, in case of a reverse proxy in place you can try to just set property `server.use-forward-headers=true`. If headers a correctly send by your proxy hawkBit should respond with correct URLs

**Comment by ctenruh-phytec** [comment]
Hi,
thanks for the reply. I have only set two headers, the common name of my client certificate and the issuer hash which are needed for the target authentication. The target authentication works fine so i assume that the two headers are send correctly. The problem is that my target tries to download the artifact directly from the hawkBit server instead of the proxy Server, which handles the authentication. Do i need to set a special header and forward it to hawkBit for it to respond with the correct artifact download URL?

**Comment by schabdo** [comment]
> Do i need to set a special header and forward it to hawkBit

No, this should be done by your proxy automatically. If proxy injects correct "proxy headers" (`X-Forwarded-Proto`,  `X-Forwarded-For` and `X-Forwarded-Host`) into the request, hawkBit will honor them and respond with correct download URLs

But of course this will only work if `server.use-forward-headers=true` property is set in hawkBit

**Comment by ctenruh-phytec** [comment]
The hostname and port in the URL are now set by the forwarded header. Only the  `X-Forwarded-Proto` header seems to be ignored. In the `hawkbit-artifactdl-defaults.properties `the URL is build like this:
`hawkbit.artifact.url.protocols.download-http.ref={protocol}://{hostnameRequest}:{portRequest}/{tenant}/controller/v1/{controllerId}/softwaremodules/{softwareModuleId}/artifacts/{artifactFileName}`
both hostname and port seem to be set by the request. Is that possible for the protocol too? or does it needs to be set in the properties?
thanks.

**Comment by schabdo** [comment]
> Is that possible for the protocol too? or does it needs to be set in the properties?

I think the code could be smart enough but I'm afraid as of now you need to set the property for the protocol. At least we do this on our sandbox as well (cf. [here](https://github.com/eclipse/hawkbit/blob/master/hawkbit-runtime/hawkbit-update-server/src/main/resources/application-cloudsandbox.properties#L18))

**Comment by ctenruh-phytec** [comment]
alright, thank you.

**Comment by schabdo** [comment]
I close this issue for now. Feel free to reopen it at any time if the property is not working for you
