### ISSUE TITLE
Request for Help. Logs in JSON format.

### ISSUE THREAD

**Issue by Antiarchitect** [eclipse/hawkbit#958]
Today I've faced the problem that Hawkbit crashing in the loop has generated 200k log entries per minute for my Elasticsearch. They were all error messages so increasing log level up to WARN or even ERROR will not help. Is there any way to compactify Hawkbit logs. It would be perfect if one exception is packed in a JSON string.

**Comment by schabdo** [comment]
Do I understand correctly that you want to switch the log format to JSON? 

I'm not quite sure what you mean by:
>  Is there any way to compactify Hawkbit logs

I guess this is more pointing towards layout of the message

**Comment by Antiarchitect** [comment]
Yep, I want to switch to JSON format in order to have one event, request and error (with stacktrace) as one JSON line

**Comment by schabdo** [comment]
Ok, I see. This will require modification of `logback-spring.xml` and different encoder. Have a look at this project here: https://github.com/logstash/logstash-logback-encoder

**Comment by Antiarchitect** [comment]
Thank you @schabdo, closing - will investigate further by myself :)
