### ISSUE TITLE
UI references dead link

### ISSUE THREAD

**Issue by dns2utf8** [eclipse/hawkbit#962]
Hi all

What I did:

0. Setup some test data
1. Under Deployment
2. I dragged a distribution onto my target
3. Then pressed the :question: icon next to the "use maintainance window" checkbox and it sent me to a 404 page:

I found the link in the file `hawkbit-ui/src/main/resources/hawkbit-ui-defaults.properties` on line **26**:
```
hawkbit.server.ui.links.documentation.maintenance-window-view=http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html
```

Has the content been migrated? Is it in the wiki?
The web archive has an old version:
https://web.archive.org/web/20181004130918/http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html

Cheers,
Stefan

**Comment by schabdo** [comment]
Thanks for your detailed report. It seems that the link has changed. I'll have a look ...

**Comment by schabdo** [comment]
@dns2utf8 link should be fixed now on master
