### ISSUE TITLE
Permissions documentation

### ISSUE THREAD

**Issue by Informatic** [eclipse/hawkbit#966]
Hello.

It seems like [documentation regarding authorization and permissions](https://www.eclipse.org/hawkbit/concepts/authorization/) seems to be somewhat outdated. I've managed to recreate current permissions in my Keycloak deployment based on [SpPermission](https://github.com/eclipse/hawkbit/blob/master/hawkbit-security-core/src/main/java/org/eclipse/hawkbit/im/authentication/SpPermission.java) code.

When attempting to create "rollout manager"-style role (usecase "Assign DS to target through a Rollout, i.e. Rollout creation and start" listed in Concepts/Authorization documentation) I stumble upon an "Error: Access is denied" message in bottom right corner of UI when trying to enter Rollouts tab. Here's an exception I am getting in server logs: https://gist.github.com/2b53f0d9cf77e1aa1dc864ccdf6347a7

I am granting following permissions/roles on Keycloak side:
```
        "READ_REPOSITORY",
        "APPROVE_ROLLOUT",
        "READ_TARGET",
        "READ_ROLLOUT",
        "UPDATE_TARGET",
        "UPDATE_ROLLOUT",
        "DELETE_ROLLOUT",
        "CREATE_ROLLOUT",
        "HANDLE_ROLLOUT"
```

User with all possible permissions granted works just fine. It somewhat seems like a bug, because all other permissions seem to give too much privilege besides rollouts. I'll try to pin down to which one is missing in that case.

When I manage to figure everything out, I can sit down and update the docs.

**Comment by Informatic** [comment]
Giving a user `TENANT_CONFIGURATION` permission (besides all the ones listed above) seems to fix this problem. This seems like a bug.

I haven't changed anything in "System Config" tab. This is pretty much a clean installation, running off Docker image `hawkbit/hawkbit-update-server:0.3.0M6-mysql@sha256:074b978a4f1b0b8b4a1abc860744b85ba7ee85394a02344fc8998569658c2291` with following environment variables:
```
        - name: HAWKBIT_ARTIFACT_URL_PROTOCOLS_DOWNLOAD-HTTP_PORT
          value: "443"
        - name: HAWKBIT_ARTIFACT_URL_PROTOCOLS_DOWNLOAD-HTTP_PROTOCOL
          value: https
        - name: HAWKBIT_SERVER_DDI_SECURITY_AUTHENTICATION_ANONYMOUS_ENABLED
          value: "true"
        - name: HAWKBIT_URL
          value: [...]:443
        - name: SECURITY_REQUIRE_SSL
          value: "true"
        - name: SERVER_USE-FORWARD-HEADERS
          value: "true"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ...
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mariadb:3306/hawkbit?useUnicode=true&characterEncoding=UTF-8&useMysqlMetadata=true
        - name: SPRING_DATASOURCE_USERNAME
          value: hawkbit
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_RABBITMQ_PASSWORD
          value: ...
        - name: SPRING_RABBITMQ_USERNAME
          value: hawkbit
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER-URI
          value: https://[...]auth/realms/master
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT-ID
          value: [...]
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT-SECRET
          value: [...]
        - name: SPRING_SECURITY_USER_PASSWORD
          value: '{noop}...'
```

**Comment by Informatic** [comment]
Ah. Just noticed this might have just been fixed in #937. Outdated documentation (my original issue) still stands.

**Comment by schabdo** [comment]
Totally right, the listed permission `ROLLOUT_MANAGEMENT` does not existing (anymore). Seems like it was splitted up into more fine grained permissions as you already stated above

**Comment by schabdo** [comment]
I updated permission matrix and use cases for rollouts within the documentation. Please let me know in case I missed something
