### ISSUE TITLE
workspace setup

### ISSUE THREAD

**Issue by harikarthikPC87** [eclipse/hawkbit#967]
Hello Everyone, 

I am new to hawkbit and currently setting up the workspace in eclipse(Orion). I am not sure, the sequence (mvn clean install - which one to run first) that i need to follow to make the workspace up and running.

Kindly share me documents if any, or the sequence of steps to be followed, to make the workspace up. Thank you.

**Comment by schabdo** [comment]
You'll find the getting started guide [here](https://www.eclipse.org/hawkbit/gettingstarted). `clean` and `install` are both maven goals and you can chain them together in one command so `mvn clean install` should be all you need for setup

**Comment by harikarthikPC87** [comment]
It worked seamless. Thanks a lot :)
