### ISSUE TITLE
How to configure rabbitmq CA certificate

### ISSUE THREAD

**Issue by gongzhao2** [eclipse/hawkbit#969]
Hi there,
we try to use hawkbit which connect to rabbitmq through amqps, but I don't know how to configure the CA of rabbitmq in hawkbit.
Is there any configuration like below can let me to configure the CA certificate of rabbitmq?
```
## Configuration for DMF/RabbitMQ integration
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
```

**Comment by schabdo** [comment]
Sure, the regular Spring properties apply to `AMQPs` as well. Haven't tried myself but this should do the trick (in addition to the listed properties above):

```
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.ssl.trustStore=<your store with CA>
spring.rabbitmq.ssl.trustStoreType=JKS
spring.rabbitmq.ssl.trustStorePassword=< your password>
```

**Comment by gongzhao2** [comment]
thanks schabdo,

I will try to test this feature and will come back to close this issue.

**Comment by schabdo** [comment]
I close this issue for now. Please feel free to reopen it at any time if you have tested it and it didn't work
