### ISSUE TITLE
DMF API message property reply_to seems to be mandatory

### ISSUE THREAD

**Issue by stegmajo** [eclipse/hawkbit#972]
The [documentation for the device management federation API](https://www.eclipse.org/hawkbit/apis/dmf_api/) describes all properties and payloads that are required to send messages to hawkBit.

It is described how to create a thing in hawkBit under:
-  title **Messages sent to hawkBit (Client -> hawkBit)**
- subtitle **THING_CREATED**

The message property "reply_to" is marked as non mandatory. However, when I try to create a thing without setting this message property, nothing is happening in hawkBit. But when I try to create a thing with this message property explicitly set, it is working. I have the impression, that the documentation is wrong and this message property is mandatory.

If the documentation is correct, then there is a bug in hawkBit itself.
PS: It would make sense to add anchors to the documentation page, so better referencing is possible.

**Comment by schabdo** [comment]
Glad to see you play around with DMF and taking the time to file an issue. Let's phrase it as a bug in the documentation :smile:
The `reply_to` is only required within the `THING_CREATED` message (as a starting point) for further communicationbased on the value of `replay_to`.

While I was on the way I found another issue. Seems like tenant is required as well:
```
AmqpRejectAndDontRequeueException: Invalid message! tenant and type header are mandatory!
```

I'll try to fix both right away.

> It would make sense to add anchors to the documentation page, so better referencing is possible

Totally agree. May I encourage you to help here out and file a PR for that? This would be highly appreciated! Docs are located [here](https://github.com/eclipse/hawkbit/tree/master/docs)
