### ISSUE TITLE
REST Management API authentication with OpenID Connect enabled

### ISSUE THREAD

**Issue by Informatic** [eclipse/hawkbit#974]
Hello.

With OpenID authentication enabled on management interface side, I don't seem to be able to (somewhat understandably) authenticate to REST API. Is there any way of generating some sort of REST API authentication token off OpenID session?

**Comment by schabdo** [comment]
The token authentication is in place on management REST API only. You need to fetch a token via OAuth2 flow directly from your identity provider's token endpoint (same provider as you configured for hawkBit). Depending on your provider you'll find the endpoints via `/.well-known/openid-configuration` or something similar. After you got the token, you're able to send the token as authorization header along with your request to the management API. I admit that there is a lack of documentation especially about the tokens. Hope this helps to get you started
