### ISSUE TITLE
Unable to build with mvn clean install

### ISSUE THREAD

**Issue by hoang519** [eclipse/hawkbit#987]
Unable to build using steps on https://github.com/eclipse/hawkbit

I was having trouble two weeks ago and put the project on hold, tried it again last week and it worked fine.  Trying to do it again this week on a different machine and it's back to failing again.  

It's failing during testing of hawkbit-runtime-jpa.  I have no idea what made it start to work last week.  I need to have a build process created for a document to hand over to the IT department.  Please let me know what other information is needed.

java -version output
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)

mvn --version output
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: E:\apache-maven-3.6.3\bin\..
Java version: 1.8.0_221, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_221\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by hoang519** [comment]
Build Output:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:10 min
[INFO] Finished at: 2020-07-30T15:07:54-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project hawkbit-repository-jpa: There are test failures.
[ERROR]
[ERROR] Please refer to E:\hawkbit\hawkbit-repository\hawkbit-repository-jpa\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :hawkbit-repository-jpa

**Comment by schabdo** [comment]
> [ERROR] Please refer to E:\hawkbit\hawkbit-repository\hawkbit-repository-jpa\target\surefire-reports for the individual test results

A detailed reason why and which tests are failing would be helpful

**Comment by hoang519** [comment]
> > [ERROR] Please refer to E:\hawkbit\hawkbit-repository\hawkbit-repository-jpa\target\surefire-reports for the individual test results
> 
> A detailed reason why and which tests are failing would be helpful

I'm sorry I don't know how to give you this info.  This is all that comes out of the command prompt.  Perhaps you can assist me in finding you what you need?  Like I said originally, the build worked fine with mvn clean install 2 weeks (now) ago.  It just stopped working again when I wanted to try repeated builds.

Please let me know what you need from me.  The log directory it outputs have xml and txt files that say failures: 0 in them so I'm not sure what I have to give you.

**Comment by hoang519** [comment]
Shoot I'm sorry I missed a file somehow, just did a find in files in notepad and found this one.

org.eclipse.hawkbit.repository.jpa.autocleanup.AutoActionCleanupTest.txt

-------------------------------------------------------------------------------
Test set: org.eclipse.hawkbit.repository.jpa.autocleanup.AutoActionCleanupTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.428 s <<< FAILURE! - in org.eclipse.hawkbit.repository.jpa.autocleanup.AutoActionCleanupTest
canceledAndFailedActionsAreCleanedUp(org.eclipse.hawkbit.repository.jpa.autocleanup.AutoActionCleanupTest)  Time elapsed: 0.359 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[1]L> but was:<[2]L>
	at org.eclipse.hawkbit.repository.jpa.autocleanup.AutoActionCleanupTest.canceledAndFailedActionsAreCleanedUp(AutoActionCleanupTest.java:119)

**Comment by schabdo** [comment]
Never mind. That's strange it seems that in your case `autoActionCleanup.run()` did not cleanup the action. I run the test locally and double-checked master, test is never failing. Are you able to reproduce exactly this test failure? Do you have any local changes or modifications?
