### ISSUE TITLE
Refactor module structure for DDI and mgmt. API

### ISSUE THREAD

**Issue by kaizimmerm** [eclipse/hawkbit#99]
Currently Artifact download, DDI and mgmt. API are mixed in the the two "rest" modules. We should split this in DDI and mgmt. API and in addition name the modules correctly to a avoid confusing our users.

Module naming proposal:
- hawkbit-ddi-api
- hawkbit-ddi-resource
- hawkbit-ddi-dl-api (for the download part)
- hawkbit-ddi-dl-resource (for the download part)
- hawkbit-mgmt-api
- hawkbit-mgmt-resource

While at it we should rename the UI module to management-ui.

**Comment by SirWayne** [comment]
I would merge the hawkbit-ddi-resource and hawkbit-ddi-dl-resource to 1 project.
