### ISSUE TITLE
maxSizeIssue While Uploading Artifact in Hawkbit Server

### ISSUE THREAD

**Issue by damontheimpulsive** [eclipse/hawkbit#995]
I have a custom application.properties file which is I am deploying through Docker Container. In my application.properties file I am writing like this.
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

This property should set the value with unlimited size. but while uploading the artifact of more than 1 GB I am getting a maxSize issue error. Any Suggestions?

**Comment by laverman** [comment]
Hi 
I assume you also need to override the DOS quotas (org.eclipse.hawkbit.repository.PropertiesQuotaManagement):

```
hawkbit.server.security.dos.maxArtifactSize= // the maximum size of artifacts in bytes:
hawkbit.server.security.dos.maxArtifactStorage= // the accumulated maximum size of all artifacts in bytes
```

**Comment by damontheimpulsive** [comment]
let me try this property and I will let u know

**Comment by flyingKenny** [comment]
I struggled today with the same issue. I **fixed it** by adding these three options into my docker env.

```code
SPRING_APPLICATION_JSON='{
          "spring.servlet.multipart.max-file-size": "4092MB",
          "spring.http.multipart.max-file-size": "4092MB",
          "hawkbit.server.security.dos.maxArtifactSize": "4294967296",
          ...
```

**Comment by DarshanChandegara** [comment]
Whenever i try to upload my rauc artifact ,which is 450 MB on screen upload forbidden message prints .
In logs i found this ,

hawkbit-simple-ui-1  | 2025-07-22T09:44:16.416Z  WARN 1 --- [spring.application.name_IS_UNDEFINED] [:] [io-8088-exec-10] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.multipart.MaxUploadSizeExceededException: Maximum upload size exceeded]

In Dockerfile, i add this in this file 'docker-compose-monolith-with-simple-ui-mysql'
      - 'SPRING_APPLICATION_JSON={"hawkbit.server.mgmtUrl": "http://hawkbit:8080","spring.servlet.multipart.max-file-size": "1024MB", "spring.http.multipart.max-file-size": "1024MB", "multipart.maxFileSize": "1073741824", "multipart.maxRequestSize": "1073741824"}'

Still facing the same isue. 
Can you help  me ?
